name: Bug Report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >
        **PLEASE READ**: If you have a support contract with Google, please
        create an issue in the [support
        console](https://cloud.google.com/support/) instead of filing on GitHub.
        This will ensure a timely response. Otherwise, please make sure to
        follow the steps below.
  - type: checkboxes
    attributes:
      label: Please make sure you have searched for information in the following
        guides.
      options:
        - label: "Search the issues already opened:
            https://github.com/GoogleCloudPlatform/google-cloud-node/issues"
          required: true
        - label: "Search StackOverflow:
            http://stackoverflow.com/questions/tagged/google-cloud-platform+nod\
            e.js"
          required: true
        - label: "Check our Troubleshooting guide:
            https://googlecloudplatform.github.io/google-cloud-node/#/docs/guid\
            es/troubleshooting"
          required: true
        - label: "Check our FAQ:
            https://googlecloudplatform.github.io/google-cloud-node/#/docs/guid\
            es/faq"
          required: true
        - label: "Check our libraries HOW-TO:
            https://github.com/googleapis/gax-nodejs/blob/main/client-libraries\
            .md"
          required: true
        - label: "Check out our authentication guide:
            https://github.com/googleapis/google-auth-library-nodejs"
          required: true
        - label: "Check out handwritten samples for many of our APIs:
            https://github.com/GoogleCloudPlatform/nodejs-docs-samples"
          required: true
  - type: textarea
    attributes:
      label: >
        A screenshot that you have tested with "Try this API".
      description: > 
        As our client libraries are mostly autogenerated, we kindly request
        that you test whether your issue is with the client library, or with the
        API itself. To do so, please search for your API
        here: https://developers.google.com/apis-explorer and attempt to
        reproduce the issue in the given method. Please include a screenshot of
        the response in "Try this API". This response should NOT match the current
        behavior you are experiencing. If the behavior is the same, it means
        that you are likely experiencing a bug with the API itself. In that
        case, please submit an issue to the API team, either by submitting an
        issue in its issue tracker https://cloud.google.com/support/docs/issue-trackers, or by
        submitting an issue in its linked tracker in the .repo-metadata.json
        file        
    validations:
      required: true
  - type: input
    attributes:
      label: >
        Link to the code that reproduces this issue. A link to a **public** Github Repository or gist with a minimal
        reproduction.
      description: >
        **Skipping this or providing an invalid link will result in the issue being closed**        
    validations:
      required: true
  - type: textarea
    attributes:
      label: >
        A step-by-step description of how to reproduce the issue, based on
        the linked reproduction.
      description: >
        Screenshots can be provided in the issue body below.
      placeholder: |
        1. Start the application in development (next dev)
        2. Click X
        3. Y will happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: A clear and concise description of what the bug is, and what you
        expected to happen.
      placeholder: Following the steps from the previous section, I expected A to
        happen, but I observed B instead
    validations:
      required: true

  - type: textarea
    attributes:
      label: A clear and concise description WHY you expect this behavior, i.e., was it a recent change, there is documentation that points to this behavior, etc. ** 
      placeholder: 'Documentation here(link) states that B should happen instead of A'
    validations:
      required: true
