/**
 * Copyright 2014 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var Multipart = require('multipart-stream');

/**
 * Create and make a request to the Google API
 * @param {object}   context  self from the context of the method calling this
 * @param {object}   params   parameters passed from the method call
 * @param {object}   options  options generated by the method call
 * @param {Boolean}  isMedia  whether the request requires media upload
 * @param {Function} callback Callback function
 * @return {Request} request  The request object created
 */
function createAPIRequest(context, params, options, isMedia, callback) {
  var req;
  var auth;
  options = options || {};

  /**
   * If the params are not present, and callback was passed instead,
   * use params as the callback and create empty params.
   */
  if (typeof(params) === 'function') {
    callback = params;
    params = {};
  } else {
    params = params || {};
  }

  if (!params.auth) {
    auth = {};
  } else if (typeof params.auth === 'string') {
    auth = { apiKey: params.auth }; // API KEY
  } else {
    auth = { authClient: params.auth }; // Auth Client
  }

  delete params.auth;

  /**
   * If apiKey is set in auth, use it as a the API KEY only
   * if it hasn't already been set in params.key
   */
  if (auth.apiKey && !params.key) {
    params.key = auth.apiKey; // set key as param if present
  }

  if (isMedia) {
    var media = params.media || {};
    delete params.media;

    /**
     * Create a boundary identifier and multipart read stream
     * @type {string}
     */
    var boundary = Math.random().toString(36).slice(2);
    var mp = new Multipart(boundary);

    params.uploadType = 'multipart';

    options.headers = {
      'Content-Type': 'multipart/related; boundary="' + boundary + '"'
    };

    // Add parts to multipart request
    mp.addPart({
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(media.metadata || {})
    });

    mp.addPart({
      headers: {
        'Content-Type': media.metadata && media.metadata.mimeType || 'application/octet-stream'
      },
      body: media.data || '' // data can be a readable stream! :D
    });
  }
  else {
    options.json = params.resource || true;
  }

  delete params.resource;

  options.qs = params;

  // create request (using authClient or otherwise and return request obj)
  if (auth.authClient) {
    req = auth.authClient.request(options, callback);
  } else {
    req = context.google.transporter.request(options, callback);
  }

  if (mp) mp.pipe(req);

  return req;
}

/**
 * Export only this function
 * @type {Function}
 */
module.exports = createAPIRequest;
