{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/agentregistry.read-only": {
          "description": "See your Google Cloud Agent Registry data and the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/agentregistry.read-write": {
          "description": "See, edit, configure, and delete your Google Cloud Agent Registry data and see the email address for your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://agentregistry.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Agent Registry",
  "description": "Agent Registry is a centralized, unified catalog that lets you store, discover, and govern Model Context Protocol (MCP) servers, tools, and AI agents within Google Cloud.",
  "discoveryVersion": "v1",
  "documentationLink": "https://docs.cloud.google.com/agent-registry/overview",
  "fullyEncodeReservedExpansion": true,
  "id": "agentregistry:v1alpha",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://agentregistry.mtls.googleapis.com/",
  "name": "agentregistry",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "projects": {
      "resources": {
        "locations": {
          "methods": {
            "get": {
              "description": "Gets information about a location.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}",
              "httpMethod": "GET",
              "id": "agentregistry.projects.locations.get",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/agentregistry.read-write",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "list": {
              "description": "Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the [ListLocationsRequest.name] field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other pr[...]",
              "flatPath": "v1alpha/projects/{projectsId}/locations",
              "httpMethod": "GET",
              "id": "agentregistry.projects.locations.list",
              "path": "v1alpha/{+name}/locations",
              "scopes": [
                "https://www.googleapis.com/auth/agentregistry.read-write",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            }
          },
          "resources": {
            "agents": {
              "methods": {
                "get": {
                  "description": "Gets details of a single Agent.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents/{agentsId}",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.agents.get",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                },
                "list": {
                  "description": "Lists Agents in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.agents.list",
                  "path": "v1alpha/{+parent}/agents",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                }
              }
            },
            "endpoints": {
              "methods": {
                "get": {
                  "description": "Gets details of a single Endpoint.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/endpoints/{endpointsId}",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.endpoints.get",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                },
                "list": {
                  "description": "Lists Endpoints in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/endpoints",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.endpoints.list",
                  "path": "v1alpha/{+parent}/endpoints",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                }
              }
            },
            "mcpServers": {
              "methods": {
                "get": {
                  "description": "Gets details of a single McpServer.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers/{mcpServersId}",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.mcpServers.get",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                },
                "list": {
                  "description": "Lists McpServers in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.mcpServers.list",
                  "path": "v1alpha/{+parent}/mcpServers",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                }
              }
            },
            "operations": {
              "methods": {
                "cancel": {
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it be[...]",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "httpMethod": "POST",
                  "id": "agentregistry.projects.locations.operations.cancel",
                  "path": "v1alpha/{+name}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "delete": {
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "DELETE",
                  "id": "agentregistry.projects.locations.operations.delete",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "get": {
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.operations.get",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "list": {
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.operations.list",
                  "path": "v1alpha/{+name}/operations",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            },
            "services": {
              "methods": {
                "create": {
                  "description": "Creates a new Service in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services",
                  "httpMethod": "POST",
                  "id": "agentregistry.projects.locations.services.create",
                  "path": "v1alpha/{+parent}/services",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "delete": {
                  "description": "Deletes a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "httpMethod": "DELETE",
                  "id": "agentregistry.projects.locations.services.delete",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "get": {
                  "description": "Gets details of a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.services.get",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                },
                "list": {
                  "description": "Lists Services in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.services.list",
                  "path": "v1alpha/{+parent}/services",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                },
                "patch": {
                  "description": "Updates the parameters of a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "httpMethod": "PATCH",
                  "id": "agentregistry.projects.locations.services.patch",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "revision": "20260318",
  "rootUrl": "https://agentregistry.googleapis.com/",
  "servicePath": "",
  "title": "Agent Registry API",
  "version": "v1alpha",
  "version_module": true
}