{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Google Analytics Admin",
  "description": "",
  "discoveryVersion": "v1",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "fullyEncodeReservedExpansion": true,
  "id": "analyticsadmin:v1beta",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "name": "analyticsadmin",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "description": "Returns summaries of all accounts accessible by the caller.",
          "flatPath": "v1beta/accountSummaries",
          "httpMethod": "GET",
          "id": "analyticsadmin.accountSummaries.list",
          "path": "v1beta/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "accounts": {
      "methods": {
        "delete": {
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "flatPath": "v1beta/accounts/{accountsId}",
          "httpMethod": "DELETE",
          "id": "analyticsadmin.accounts.delete",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "description": "Lookup for a single Account.",
          "flatPath": "v1beta/accounts/{accountsId}",
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.get",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "list": {
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "flatPath": "v1beta/accounts",
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.list",
          "path": "v1beta/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "description": "Updates an account.",
          "flatPath": "v1beta/accounts/{accountsId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "provisionAccountTicket": {
          "description": "Requests a ticket for creating an account.",
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1beta/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "searchChangeHistoryEvents": {
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        }
      }
    },
    "properties": {
      "methods": {
        "acknowledgeUserDataCollection": {
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or via this API) before MeasurementProtocolSecret resources may be created.",
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "create": {
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "flatPath": "v1beta/properties",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.create",
          "path": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "delete": {
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "flatPath": "v1beta/properties/{propertiesId}",
          "httpMethod": "DELETE",
          "id": "analyticsadmin.properties.delete",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "description": "Lookup for a single \"GA4\" Property.",
          "flatPath": "v1beta/properties/{propertiesId}",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.get",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "getDataRetentionSettings": {
          "description": "Returns the singleton data retention settings for this property.",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "flatPath": "v1beta/properties",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.list",
          "path": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "description": "Updates a property.",
          "flatPath": "v1beta/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.patch",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "updateDataRetentionSettings": {
          "description": "Updates the singleton data retention settings for this property.",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        }
      },
      "resources": {
        "conversionEvents": {
          "methods": {
            "create": {
              "description": "Creates a conversion event with the specified attributes.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "path": "v1beta/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "description": "Deletes a conversion event in a property.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "description": "Retrieve a single conversion event.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "path": "v1beta/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "customDimensions": {
          "methods": {
            "archive": {
              "description": "Archives a CustomDimension on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "path": "v1beta/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "description": "Creates a CustomDimension.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.create",
              "path": "v1beta/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "description": "Lookup for a single CustomDimension.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.get",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "description": "Lists CustomDimensions on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.list",
              "path": "v1beta/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "description": "Updates a CustomDimension on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "description": "Archives a CustomMetric on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1beta/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "description": "Creates a CustomMetric.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.create",
              "path": "v1beta/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "description": "Lookup for a single CustomMetric.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.get",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "description": "Lists CustomMetrics on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.list",
              "path": "v1beta/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "description": "Updates a CustomMetric on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "dataStreams": {
          "methods": {
            "create": {
              "description": "Creates a DataStream.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.dataStreams.create",
              "path": "v1beta/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "description": "Deletes a DataStream on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "description": "Lookup for a single DataStream.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.get",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "description": "Lists DataStreams on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.list",
              "path": "v1beta/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "description": "Updates a DataStream on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "DELETE",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "get": {
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "list": {
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "patch": {
                  "description": "Updates a measurement protocol secret.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                }
              }
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "create": {
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1beta/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "description": "Deletes a FirebaseLink on a property",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "path": "v1beta/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "description": "Creates a GoogleAdsLink.",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "description": "Deletes a GoogleAdsLink on a property",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists GoogleAdsLinks on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        }
      }
    }
  },
  "revision": "20221214",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "servicePath": "",
  "title": "Google Analytics Admin API",
  "version": "v1beta",
  "version_module": true
}