{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.policy": {
          "description": "See, edit, create or delete policies applied to Chrome OS and Chrome Browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.policy.readonly": {
          "description": "See policies applied to Chrome OS and Chrome Browsers managed within your organization"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://chromepolicy.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Chrome Policy",
  "description": "The Chrome Policy API is a suite of services that allows Chrome administrators to control the policies applied to their managed Chrome OS devices and Chrome browsers.",
  "discoveryVersion": "v1",
  "documentationLink": "http://developers.google.com/chrome/policy",
  "fullyEncodeReservedExpansion": true,
  "id": "chromepolicy:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://chromepolicy.mtls.googleapis.com/",
  "name": "chromepolicy",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "customers": {
      "resources": {
        "policies": {
          "methods": {
            "resolve": {
              "description": "Gets the resolved policy values for a list of policies that match a search query.",
              "flatPath": "v1/customers/{customersId}/policies:resolve",
              "httpMethod": "POST",
              "id": "chromepolicy.customers.policies.resolve",
              "path": "v1/{+customer}/policies:resolve",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ]
            }
          },
          "resources": {
            "orgunits": {
              "methods": {
                "batchInherit": {
                  "description": "Modify multiple policy values that are applied to a specific org unit so that they now inherit the value from a parent (if applicable). All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.",
                  "flatPath": "v1/customers/{customersId}/policies/orgunits:batchInherit",
                  "httpMethod": "POST",
                  "id": "chromepolicy.customers.policies.orgunits.batchInherit",
                  "path": "v1/{+customer}/policies/orgunits:batchInherit",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ]
                },
                "batchModify": {
                  "description": "Modify multiple policy values that are applied to a specific org unit. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.",
                  "flatPath": "v1/customers/{customersId}/policies/orgunits:batchModify",
                  "httpMethod": "POST",
                  "id": "chromepolicy.customers.policies.orgunits.batchModify",
                  "path": "v1/{+customer}/policies/orgunits:batchModify",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ]
                }
              }
            }
          }
        },
        "policySchemas": {
          "methods": {
            "get": {
              "description": "Get a specific policy schema for a customer by its resource name.",
              "flatPath": "v1/customers/{customersId}/policySchemas/{policySchemasId}",
              "httpMethod": "GET",
              "id": "chromepolicy.customers.policySchemas.get",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ]
            },
            "list": {
              "description": "Gets a list of policy schemas that match a specified filter value for a given customer.",
              "flatPath": "v1/customers/{customersId}/policySchemas",
              "httpMethod": "GET",
              "id": "chromepolicy.customers.policySchemas.list",
              "path": "v1/{+parent}/policySchemas",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ]
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "description": "Creates an enterprise file from the content provided by user. Returns a public download url for end user.",
          "flatPath": "v1/customers/{customersId}/policies/files:uploadPolicyFile",
          "httpMethod": "POST",
          "id": "chromepolicy.media.upload",
          "path": "v1/{+customer}/policies/files:uploadPolicyFile",
          "scopes": [
            "https://www.googleapis.com/auth/chrome.management.policy"
          ],
          "supportsMediaUpload": true
        }
      }
    }
  },
  "revision": "20220305",
  "rootUrl": "https://chromepolicy.googleapis.com/",
  "servicePath": "",
  "title": "Chrome Policy API",
  "version": "v1",
  "version_module": true
}