{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Cloud Search",
  "description": "Cloud Search provides cloud-based search capabilities over Google Workspace data. The Cloud Search API allows indexing of non-Google Workspace data into Cloud Search.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/cloud-search/docs/guides/",
  "fullyEncodeReservedExpansion": true,
  "id": "cloudsearch:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://cloudsearch.mtls.googleapis.com/",
  "name": "cloudsearch",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "debug": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "methods": {
                "checkAccess": {
                  "description": "Checks whether an item is accessible by specified principal. Principal must be a user; groups and domain values aren't supported. **Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                  "httpMethod": "POST",
                  "id": "cloudsearch.debug.datasources.items.checkAccess",
                  "path": "v1/debug/{+name}:checkAccess",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                },
                "searchByViewUrl": {
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided in the request. **Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                  "httpMethod": "POST",
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl",
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              },
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "description": "List all unmapped identities for a specific item. **Note:** This API requires an admin account to execute.",
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "httpMethod": "GET",
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                      "path": "v1/debug/{+parent}/unmappedids",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "identitysources": {
          "resources": {
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "description": "Lists names of items associated with an unmapped identity. **Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "httpMethod": "GET",
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                  "path": "v1/debug/{+parent}/items:forunmappedidentity",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            },
            "unmappedids": {
              "methods": {
                "list": {
                  "description": "Lists unmapped user identities for an identity source. **Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids",
                  "httpMethod": "GET",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list",
                  "path": "v1/debug/{+parent}/unmappedids",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "methods": {
            "deleteSchema": {
              "description": "Deletes the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "httpMethod": "DELETE",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "path": "v1/indexing/{+name}/schema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "getSchema": {
              "description": "Gets the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "httpMethod": "GET",
              "id": "cloudsearch.indexing.datasources.getSchema",
              "path": "v1/indexing/{+name}/schema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "updateSchema": {
              "description": "Updates the schema of a data source. This method does not perform incremental updates to the schema. Instead, this method updates the schema by overwriting the entire schema. **Note:** This API requires an admin or service account to execute.",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "httpMethod": "PUT",
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "path": "v1/indexing/{+name}/schema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            }
          },
          "resources": {
            "items": {
              "methods": {
                "delete": {
                  "description": "Deletes Item resource for the specified resource name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "httpMethod": "DELETE",
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "path": "v1/indexing/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "deleteQueueItems": {
                  "description": "Deletes all items in a queue. This method is useful for deleting stale items. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems",
                  "path": "v1/indexing/{+name}/items:deleteQueueItems",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "get": {
                  "description": "Gets Item resource by item name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.indexing.datasources.items.get",
                  "path": "v1/indexing/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "index": {
                  "description": "Updates Item ACL, metadata, and content. It will insert the Item if it does not exist. This method does not support partial updates. Fields with no provided values are cleared out in the Cloud Search index. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "path": "v1/indexing/{+name}:index",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "list": {
                  "description": "Lists all or a subset of Item resources. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items",
                  "httpMethod": "GET",
                  "id": "cloudsearch.indexing.datasources.items.list",
                  "path": "v1/indexing/{+name}/items",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "poll": {
                  "description": "Polls for unreserved items from the indexing queue and marks a set as reserved, starting with items that have the oldest timestamp from the highest priority ItemStatus. The priority order is as follows: ERROR MODIFIED NEW_ITEM ACCEPTED Reserving items ensures that polling from other threads cannot create overlapping sets. After handling the reserved items, the client should put items back into the unreserved state, either by calling index, or by calling push wit[...]",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "path": "v1/indexing/{+name}/items:poll",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "push": {
                  "description": "Pushes an item onto a queue for later polling and updating. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "path": "v1/indexing/{+name}:push",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "unreserve": {
                  "description": "Unreserves all items from a queue, making them all eligible to be polled. This method is useful for resetting the indexing queue after a connector has been restarted. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "path": "v1/indexing/{+name}/items:unreserve",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "upload": {
                  "description": "Creates an upload session for uploading item content. For items smaller than 100 KB, it's easier to embed the content inline within an index request. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.upload",
                  "path": "v1/indexing/{+name}:upload",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "description": "Uploads media for indexing. The upload endpoint supports direct and resumable upload protocols and is intended for large items that can not be [inlined during index requests](https://developers.google.com/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent). To index large content: 1. Call indexing.datasources.items.upload with the item name to begin an upload session and retrieve the UploadItemRef. 1. Call media.upload to upload the content, as a[...]",
          "flatPath": "v1/media/{mediaId}",
          "httpMethod": "POST",
          "id": "cloudsearch.media.upload",
          "path": "v1/media/{+resourceName}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ],
          "supportsMediaUpload": true
        }
      }
    },
    "operations": {
      "methods": {
        "get": {
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "id": "cloudsearch.operations.get",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ]
        }
      },
      "resources": {
        "lro": {
          "methods": {
            "list": {
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
              "flatPath": "v1/operations/{operationsId}/lro",
              "httpMethod": "GET",
              "id": "cloudsearch.operations.lro.list",
              "path": "v1/{+name}/lro",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.debug",
                "https://www.googleapis.com/auth/cloud_search.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            }
          }
        }
      }
    },
    "query": {
      "methods": {
        "debugSearch": {
          "description": "Returns Debug information for Cloud Search Query API provides the search method. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
          "flatPath": "v1/query:debugSearch",
          "httpMethod": "POST",
          "id": "cloudsearch.query.debugSearch",
          "path": "v1/query:debugSearch",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ]
        },
        "removeActivity": {
          "description": "Provides functionality to remove logged activity for a user. Currently to be used only for Chat 1p clients **Note:** This API requires a standard end user account to execute. A service account can't perform Remove Activity requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
          "flatPath": "v1/query:removeActivity",
          "httpMethod": "POST",
          "id": "cloudsearch.query.removeActivity",
          "path": "v1/query:removeActivity",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ]
        },
        "search": {
          "description": "The Cloud Search Query API provides the search method, which returns the most relevant results from a user query. The results can come from Google Workspace apps, such as Gmail or Google Drive, or they can come from data that you have indexed from a third party. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide [...]",
          "flatPath": "v1/query/search",
          "httpMethod": "POST",
          "id": "cloudsearch.query.search",
          "path": "v1/query/search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ]
        },
        "suggest": {
          "description": "Provides suggestions for autocompleting the query. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
          "flatPath": "v1/query/suggest",
          "httpMethod": "POST",
          "id": "cloudsearch.query.suggest",
          "path": "v1/query/suggest",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ]
        }
      },
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "description": "Returns list of sources that user can use for Search and Suggest APIs. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
              "flatPath": "v1/query/sources",
              "httpMethod": "GET",
              "id": "cloudsearch.query.sources.list",
              "path": "v1/query/sources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ]
            }
          }
        }
      }
    },
    "settings": {
      "methods": {
        "getCustomer": {
          "description": "Get customer settings. **Note:** This API requires an admin account to execute.",
          "flatPath": "v1/settings/customer",
          "httpMethod": "GET",
          "id": "cloudsearch.settings.getCustomer",
          "path": "v1/settings/customer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ]
        },
        "updateCustomer": {
          "description": "Update customer settings. **Note:** This API requires an admin account to execute.",
          "flatPath": "v1/settings/customer",
          "httpMethod": "PATCH",
          "id": "cloudsearch.settings.updateCustomer",
          "path": "v1/settings/customer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ]
        }
      },
      "resources": {
        "datasources": {
          "methods": {
            "create": {
              "description": "Creates a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources",
              "httpMethod": "POST",
              "id": "cloudsearch.settings.datasources.create",
              "path": "v1/settings/datasources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "delete": {
              "description": "Deletes a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "httpMethod": "DELETE",
              "id": "cloudsearch.settings.datasources.delete",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "get": {
              "description": "Gets a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.datasources.get",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "list": {
              "description": "Lists datasources. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.datasources.list",
              "path": "v1/settings/datasources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "patch": {
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "httpMethod": "PATCH",
              "id": "cloudsearch.settings.datasources.patch",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "update": {
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "httpMethod": "PUT",
              "id": "cloudsearch.settings.datasources.update",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            }
          }
        },
        "searchapplications": {
          "methods": {
            "create": {
              "description": "Creates a search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications",
              "httpMethod": "POST",
              "id": "cloudsearch.settings.searchapplications.create",
              "path": "v1/settings/searchapplications",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "delete": {
              "description": "Deletes a search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "DELETE",
              "id": "cloudsearch.settings.searchapplications.delete",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "get": {
              "description": "Gets the specified search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.searchapplications.get",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "list": {
              "description": "Lists all search applications. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.searchapplications.list",
              "path": "v1/settings/searchapplications",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "patch": {
              "description": "Updates a search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "PATCH",
              "id": "cloudsearch.settings.searchapplications.patch",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "reset": {
              "description": "Resets a search application to default settings. This will return an empty response. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset",
              "httpMethod": "POST",
              "id": "cloudsearch.settings.searchapplications.reset",
              "path": "v1/settings/{+name}:reset",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "update": {
              "description": "Updates a search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "PUT",
              "id": "cloudsearch.settings.searchapplications.update",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            }
          }
        }
      }
    },
    "stats": {
      "methods": {
        "getIndex": {
          "description": "Gets indexed item statistics aggreggated across all data sources. This API only returns statistics for previous dates; it doesn't return statistics for the current day. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/index",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getIndex",
          "path": "v1/stats/index",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getQuery": {
          "description": "Get the query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/query",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getQuery",
          "path": "v1/stats/query",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getSearchapplication": {
          "description": "Get search application stats for customer. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/searchapplication",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getSearchapplication",
          "path": "v1/stats/searchapplication",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getSession": {
          "description": "Get the # of search sessions, % of successful sessions with a click query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/session",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getSession",
          "path": "v1/stats/session",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getUser": {
          "description": "Get the users statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/user",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getUser",
          "path": "v1/stats/user",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        }
      },
      "resources": {
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "description": "Gets indexed item statistics for a single data source. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.index.datasources.get",
                  "path": "v1/stats/index/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ]
                }
              }
            }
          }
        },
        "query": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "description": "Get the query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.query.searchapplications.get",
                  "path": "v1/stats/query/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ]
                }
              }
            }
          }
        },
        "session": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "description": "Get the # of search sessions, % of successful sessions with a click query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.session.searchapplications.get",
                  "path": "v1/stats/session/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ]
                }
              }
            }
          }
        },
        "user": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "description": "Get the users statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.user.searchapplications.get",
                  "path": "v1/stats/user/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "v1": {
      "methods": {
        "initializeCustomer": {
          "description": "Enables `third party` support in Google Cloud Search. **Note:** This API requires an admin account to execute.",
          "flatPath": "v1:initializeCustomer",
          "httpMethod": "POST",
          "id": "cloudsearch.initializeCustomer",
          "path": "v1:initializeCustomer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ]
        }
      }
    }
  },
  "revision": "20240710",
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "schemas": {
    "Action": {
      "id": "Action",
      "properties": {
        "title": {
          "description": "[Required] Title of the action.",
          "type": "string"
        },
        "url": {
          "description": "[Optional] Url of the action.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "AuditLoggingSettings": {
      "description": "Represents the settings for Cloud audit logging",
      "id": "AuditLoggingSettings",
      "properties": {
        "logAdminReadActions": {
          "description": "Indicates whether audit logging is on/off for admin activity read APIs i.e. Get/List DataSources, Get/List SearchApplications etc.",
          "type": "boolean"
        },
        "logDataReadActions": {
          "description": "Indicates whether audit logging is on/off for data access read APIs i.e. ListItems, GetItem etc.",
          "type": "boolean"
        },
        "logDataWriteActions": {
          "description": "Indicates whether audit logging is on/off for data access write APIs i.e. IndexItem etc.",
          "type": "boolean"
        },
        "project": {
          "description": "The resource name of the GCP Project to store audit logs. Cloud audit logging will be enabled after project_name has been updated through CustomerService. Format: projects/{project_id}",
          "type": "string"
        }
      },
      "type": "object"
    },
    "BackgroundColoredText": {
      "id": "BackgroundColoredText",
      "properties": {
        "backgroundColor": {
          "description": "[Optional] Color of the background. The text color can change depending on the selected background color, and the client does not have control over this. If missing, the background will be WHITE.",
          "enum": [
            "UNKNOWN_COLOR",
            "WHITE",
            "YELLOW",
            "ORANGE",
            "GREEN",
            "BLUE",
            "GREY"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        },
        "text": {
          "description": "[Required] The text to display.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "BandWidthRangeKbps": {
      "id": "BandWidthRangeKbps",
      "properties": {
        "percentile10": {
          "format": "int32",
          "type": "integer"
        },
        "percentile50": {
          "format": "int32",
          "type": "integer"
        },
        "percentile90": {
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "BooleanOperatorOptions": {
      "description": "Used to provide a search operator for boolean properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "BooleanOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the boolean property. For example, if operatorName is *closed* and the property's name is *isClosed*, then queries like *closed:<value>* show results only where the value of the property named *isClosed* matches *<value>*. By contrast, a search that uses the same *<value>* without an operator returns all items where *<value>* matches the value of any String properties or text within the content field [...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "BooleanPropertyOptions": {
      "description": "The options for boolean properties.",
      "id": "BooleanPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "BooleanOperatorOptions",
          "description": "If set, describes how the boolean should be used as a search operator."
        }
      },
      "type": "object"
    },
    "CheckAccessResponse": {
      "id": "CheckAccessResponse",
      "properties": {
        "hasAccess": {
          "description": "Returns true if principal has access. Returns false otherwise.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "ClientOptInContext": {
      "description": "Represents the user's current opt-in status on the current device related to features such as Google Now, App and Web History, Device State and Content. Each opt-in status includes an eligibility status, which depends on the type of account (Dasher, etc.), country, language, and device specifics. Next id: 38 Note: if the proto is changed, please also update the code that converts it to corresponding logs proto (they are in the same name but incompatible so manual conversion[...]",
      "id": "ClientOptInContext",
      "properties": {
        "ambientEnrollmentStatus": {
          "description": "Enrollment status for Ambient Mode feature go/assistant-ambient-mode",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "ambientPhotoEnrollmentStatus": {
          "description": "Enrollment status for PhotoFrame feature in Ambient Mode. This is different from PhotoFrame enrollment in other features such as Dreamliner. go/assistant-ambient-mode",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "assistantOnLockscreenStatus": {
          "description": "Whether the user has opted into enabling Assistant on Lockscreen. go/iris-newperm-prd",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "audioHistoryStatus": {
          "$ref": "OptInStatus",
          "description": "Audio History. Used to improve speech recognition and hotword triggering. https://sites.google.com/a/google.com/android-speech/projects/audio-history"
        },
        "bluetoothAudioRecordingStatus": {
          "description": "Whether the user has opted into bluetooth audio recording setting.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "chromeSyncStatus": {
          "$ref": "OptInStatus",
          "description": "Set to true iff the user is signed into Chrome with the same account as GSA and has Chrome sync enabled (as reported by Chrome to GSA). This can be used to serve personalized suggestions based on the user's browsing history."
        },
        "deviceAppsStatus": {
          "$ref": "OptInStatus",
          "description": "Allows Google to upload device app information."
        },
        "deviceContactsStatus": {
          "$ref": "OptInStatus",
          "description": "Allows Google to upload contact information from device."
        },
        "deviceStateAndContentStatus": {
          "$ref": "OptInStatus",
          "description": "User allows Google to upload state (aka settings) and content (documents and media) from their device. See https://goto.google.com/device-consents"
        },
        "disabledIcingSourceApps": {
          "description": "List of Android package names the user disabled from appearing in the autocomplete suggestions on their device. ",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "disabledIcingSources": {
          "description": "List of Android packages and corpora that the user disabled. This replaces disabled_icing_source_apps and allows disabling a single corpus for a particular package.",
          "items": {
            "$ref": "DisabledIcingPackageCorpus"
          },
          "type": "array"
        },
        "headphonePersonalResultsStatus": {
          "description": "Whether the user has opted into headphone personal results setting. go/enable-pr-with-headset",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "hotwordEnrollmentStatus": {
          "$ref": "OptInStatus",
          "description": "Enrollment status for Hotword any-screen/always-on. This information is sent to the server-side to know that the user can run Hotword. For example, in go/gsa-voice-feature-tips using this information, the user will be shown Voice Tips that will take the user directly to the enrollment and guide them to move to the next level of Voice Features experience."
        },
        "locationHistoryStatus": {
          "$ref": "OptInStatus",
          "description": "User allows Google to upload location history from their device. See https://goto.google.com/gcore-ulr"
        },
        "lockscreenPersonalResponseStatus": {
          "description": "Whether the user has opted into showing personal response on Lockscreen.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "lockscreenSearchBluetoothStatus": {
          "description": "Whether the user has opted into lockscreen queries via bluetooth headsets setting.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "lockscreenSearchWiredHeadsetStatus": {
          "description": "Whether the user has opted into lockscreen queries via wired headsets setting.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "nowNotificationStatus": {
          "$ref": "OptInStatus",
          "description": "Google Now push notifications."
        },
        "nowStatus": {
          "$ref": "OptInStatus",
          "description": "Google Now activation."
        },
        "nowTosVersion": {
          "description": "Google Now marks each release with a TOS version, so it can ask users to opt in again if the terms change from release to release.",
          "format": "int32",
          "type": "integer"
        },
        "opaEligibility": {
          "description": "User's eligibility to use the Assistant.",
          "enum": [
            "NOT_ELIGIBLE",
            "ELIGIBLE_PREBUILT",
            "ELIGIBLE_FOR_UPGRADE",
            "ELIGIBLE_UPGRADING",
            "ELIGIBLE_UPGRADED",
            "ELIGIBLE_UPGRADED_BYPASS"
          ],
          "enumDescriptions": [
            "User is not eligible for OPA",
            "User is eligible for OPA because their device came with OPA.",
            "User is eligible to upgrade to OPA after their formerly-ineligible device received an update to AGSA >= 6.13 and received the proper config flags.",
            "User is eligible to upgrade, AND has started the upgrade, but NOT finished it. By definition, a user who is ELIGIBLE_UPGRADING was ELIGIBLE_FOR_UPGRADE at some point prior.",
            "User is eligible for OPA after completing the upgrade flow. By definition, a user who is ELIGIBLE_UPGRADED was ELIGIBLE_UPGRADING at some point prior.",
            "User is eligible for OPA and bypassed some screens in onboarding to complete the upgrade flow. By definition, a user who is ELIGIBLE_UPGRADED_BYPASS is an OPA upgraded user and was ELIGIBLE_UPGRADING at some point prior."
          ],
          "type": "string"
        },
        "opaEmailOptInStatus": {
          "description": "Has the user opted-in to receiving emails for OPA? This is set when the user opts-in during the OPA upgrade flow. It has an UNKNOWN value otherwise. Note that this bit isn't updated if the user changes their email opt-in status through settings or unsubscribing in the email.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "opaExperienceType": {
          "description": "The Opa experience type. As of Feb 2019, it is only used to check whether the user is in the Try Before You Buy experience.",
          "enum": [
            "OPA_EXPERIENCE_TYPE_UNKNOWN",
            "OPA_EXPERIENCE_INELIGIBLE",
            "OPA_EXPERIENCE_NOT_STARTED",
            "OPA_EXPERIENCE_TRY_BEFORE_YOU_BUY",
            "OPA_EXPERIENCE_COMPLETED_ONBOARDING"
          ],
          "enumDescriptions": [
            "Default value. AGSA 9.27-: all users AGSA 9.27+ 9.66-: all users but TBYB users AGSA 9.66+: not used",
            "OPA-ineligible users (AGSA 9.66+ only)",
            "The initial state of OPA-eligible users (AGSA 9.66+ only)",
            "TBYB users (AGSA 9.27+ only)",
            "OOBE-completed users (AGSA 9.66+ only)"
          ],
          "type": "string"
        },
        "opaPartialExperienceReason": {
          "description": "The reason why user enters the OPA \"signed-out mode\" partial experience (go/opa-signed-out-everywhere). Note that the value only means how the user entered the partial experience. For example, if a user enters TBYB and becomes a full-experience user, this value will remain as TBYB. To check the current experience type, you should read opa_experience_type instead.",
          "enum": [
            "OPA_PARTIAL_EXPERIENCE_REASON_UNKNOWN",
            "OPA_TRY_BEFORE_YOU_BUY",
            "OPA_UDC_OPT_OUT_FLOW"
          ],
          "enumDescriptions": [
            "Default value",
            "User enters OPA \"siged-out mode\" partial experience due to the try-before-you-buy (TBYB) experiment go/opa-tbyb-experiment-plan",
            "User enters OPA \"siged-out mode\" partial experience due to the \"UDC opt-out flow\" experiment (go/opa-udc-opt-out-ux-flow)"
          ],
          "type": "string"
        },
        "opaUdcConsentStatus": {
          "description": "Has the user opted in to OPA's UDC requirements? \"OPA UDC consent\" is a one-time opt-in to the set of required UDC opt-in bits. If the user has already granted all required UDC opt-ins, then we automatically mark them as consented. We require that users grant OPA UDC consent before using OPA for the first time. Note: The user does not revoke OPA UDC consent if they turn off one of the UDC opt-in bits from Settings; for such users, the server either offers a degraded e[...]",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "opaUserEnabledStatus": {
          "description": "A user-configurable global on/off switch for the Assistant; the user can completely disable the assistant (go/opa-enabled-ss). Defaults to enabled. This setting is completely independent from the user's opa_eligibility; they can be eligible, but OPA disabled. There users are by definition not making Assistant queries, so this value is a signal of the population size.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "proactivePersonalResponseStatus": {
          "description": "Whether the user has opted into showing proactive personal suggestions on lock screen before asking. This is the proactive sub-bit for lockscreen_personal_response_status.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "screenContextOptInStatus": {
          "description": "Has the user granted permission for Google to read the contents of their screen. Note that in OPA, training hotword automatically opts the user into screen context.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "skipVoiceRecognitionStatus": {
          "description": "Whether the user has opted into skipping voice recognition. go/iris-newperm-prd",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "speakerModelStatus": {
          "description": "Whether the user has enrolled the Speaker ID model.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "thirdPartyDisclosureStatus": {
          "description": "Whether the user has acknowledged the third party disclosure.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "warmActionsAlarmsTimersEnrollmentStatus": {
          "description": "Whether the user has opted into alarms/timers context for Quick phrases.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "warmActionsCallsEnrollmentStatus": {
          "description": "Whether the user has opted into calls context for Quick phrases.",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "warmActionsEnrollmentStatus": {
          "description": "Whether the user has opted into at least one Mobile Warm Words/Quick Phrases context. go/mww-prd",
          "enum": [
            "OPA_OPT_IN_STATUS_UNKNOWN",
            "OPA_OPT_IN_STATUS_DISABLED",
            "OPA_OPT_IN_STATUS_ENABLED"
          ],
          "enumDescriptions": [
            "The user has never been prompted with this opt-in.",
            "The user has rejected the opt-in.",
            "The user has accepted the opt-in."
          ],
          "type": "string"
        },
        "webAndAppHistoryStatus": {
          "$ref": "OptInStatus",
          "description": "User allows Google to upload usage history from their device. This field can be set to true iff web_history_status is set to true. Historically, this used to be called \"Supplemental Search History\". See https://goto.google.com/device-consents"
        },
        "webHistoryStatus": {
          "$ref": "OptInStatus",
          "description": "User allows Google to log interactions with Search from their device. Historically, this used to be called \"Search History\". See https://goto.google.com/device-consents"
        }
      },
      "type": "object"
    },
    "CloudsearchEmailAddress": {
      "description": "A person's email address.",
      "id": "CloudsearchEmailAddress",
      "properties": {
        "emailAddress": {
          "description": "The email address.",
          "type": "string"
        },
        "primary": {
          "description": "Indicates if this is the user's primary email. Only one entry can be marked as primary.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "CloudsearchFilter": {
      "description": "Generic way of expessing filters. It support two ways. 1. Setting name and the value. The name has to be an operator_name defined in schema. 2. Setting the operator and filters. The sub filters will be evaluated using the operator.",
      "id": "CloudsearchFilter",
      "properties": {
        "filters": {
          "description": "Sub filters. If present, the operator must be set.",
          "items": {
            "$ref": "CloudsearchFilter"
          },
          "type": "array"
        },
        "name": {
          "description": "The operator_name that we apply to the query, e.g. price_greater_than. It can be either case, 1. operator_name in schema. We will filter the results with the property that matches the value. 2. greater_than_operator_name or less_than_operator_name in schema. We will filter the results that property is greater than or less than the given value.",
          "type": "string"
        },
        "operator": {
          "description": "The operator of the filter.",
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "enumDescriptions": [
            "Logical operators, can only be applied to a sub filters.",
            "",
            "NOT can only be appiled on a single sub filters."
          ],
          "type": "string"
        },
        "value": {
          "$ref": "CloudsearchValue",
          "description": "The value to check. If present, the name must be set."
        }
      },
      "type": "object"
    },
    "CloudsearchFilterSuggestion": {
      "description": "A filter suggestion.",
      "id": "CloudsearchFilterSuggestion",
      "properties": {
        "filter": {
          "$ref": "CloudsearchFilter",
          "description": "The filter suggestion. It can be 1. A value filter, e.g. type:documents 2. A composite filter before:today and after:yesterday"
        },
        "suggestionMatchInfo": {
          "$ref": "CloudsearchSnippet",
          "description": "This field contains the suggestion match information returned by the backend after escaping the HTML in the suggestion string. The areas that we might like to extract from the suggestion string returned by the backend are marked using the match_ranges field inside Snippet. For example, if the snippet string inside suggestion_match_info is: \"google search\", and the keyword \"goog\" is supposed to be bolded, the match_ranges is the list of range of indexes in the snippe[...]"
        },
        "type": {
          "enum": [
            "NONE",
            "OPERATOR",
            "LABEL"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "CloudsearchGroup": {
      "description": "Object to represent a group.",
      "id": "CloudsearchGroup",
      "properties": {
        "emailAddresses": {
          "description": "The group's email addresses",
          "items": {
            "$ref": "CloudsearchEmailAddress"
          },
          "type": "array"
        },
        "groupNames": {
          "description": "Group's names",
          "items": {
            "$ref": "CloudsearchName"
          },
          "type": "array"
        },
        "name": {
          "description": "The resource name of the group to provide information about. See People.get from Google People API.",
          "type": "string"
        },
        "obfuscatedId": {
          "description": "Obfuscated GAIA ID of a google group. Used by first party Cloud Search clients.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "CloudsearchImage": {
      "description": "Image returned with suggestion; eg: person's photo or document thumbnail.",
      "id": "CloudsearchImage",
      "properties": {
        "source": {
          "description": "Specifies the source from where the photo is fetched.",
          "enum": [
            "CONTACT_DATA_SOURCE_UNSPECIFIED",
            "CONTACT_DATA_SOURCE_PROFILE",
            "CONTACT_DATA_SOURCE_DOMAIN_PROFILE",
            "CONTACT_DATA_SOURCE_CONTACT",
            "CONTACT_DATA_SOURCE_DOMAIN_CONTACT",
            "CONTACT_DATA_SOURCE_AFFINITY"
          ],
          "enumDescriptions": [
            "Data source for the contact is not specified.",
            "This is where a Google user keeps and edits information about themself. They can decide who (what other Google users) can view which parts of it. Since it is information a user is managing about themselves, it is considered to be the most up-to-date.",
            "Google-For-Work Profile. The domain profile data source describes Google profile data that is populated/edited by the admin of a Google Workspace organization.",
            "Where a Google user keeps contact information about others, like phone numbers, emails and more. The user owns and edits this information. It could be out of date or incorrect. Users are generally only allowed to read their own contacts. Contacts are typically synced to mobile devices and used in apps like Gmail and Hangouts.",
            "Domain shared contact. An entity that is owned by a domain and represents a person, but is not a user in the domain. For more details see https://support.google.com/a/answer/9281635.",
            "Device contacts that are used in interaction ranking, but have not been uploaded to Google. These are synthesized people from interaction data."
          ],
          "type": "string"
        },
        "url": {
          "description": "The URL of the photo.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "CloudsearchMatchRange": {
      "description": "Matched range of a snippet [start, end). The \"start\" and \"end\" positions are 0 indexed. For example, if the snippet string is \"google search\" and the string to be matched is \"goog\", the MatchRange is [0, 4).",
      "id": "CloudsearchMatchRange",
      "properties": {
        "end": {
          "description": "1 + index of the ending position of the match in the snippet.",
          "format": "int32",
          "type": "integer"
        },
        "start": {
          "description": "Index of the starting position of the match in the snippet.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "CloudsearchName": {
      "description": "A person or group's name.",
      "id": "CloudsearchName",
      "properties": {
        "displayName": {
          "description": "The read-only display name formatted according to the locale specified by the viewer's account or the Accept-Language HTTP header.",
          "type": "string"
        },
        "source": {
          "description": "Specifies the source from where the name is fetched.",
          "enum": [
            "CONTACT_DATA_SOURCE_UNSPECIFIED",
            "CONTACT_DATA_SOURCE_PROFILE",
            "CONTACT_DATA_SOURCE_DOMAIN_PROFILE",
            "CONTACT_DATA_SOURCE_CONTACT",
            "CONTACT_DATA_SOURCE_DOMAIN_CONTACT",
            "CONTACT_DATA_SOURCE_AFFINITY"
          ],
          "enumDescriptions": [
            "Data source for the contact is not specified.",
            "This is where a Google user keeps and edits information about themself. They can decide who (what other Google users) can view which parts of it. Since it is information a user is managing about themselves, it is considered to be the most up-to-date.",
            "Google-For-Work Profile. The domain profile data source describes Google profile data that is populated/edited by the admin of a Google Workspace organization.",
            "Where a Google user keeps contact information about others, like phone numbers, emails and more. The user owns and edits this information. It could be out of date or incorrect. Users are generally only allowed to read their own contacts. Contacts are typically synced to mobile devices and used in apps like Gmail and Hangouts.",
            "Domain shared contact. An entity that is owned by a domain and represents a person, but is not a user in the domain. For more details see https://support.google.com/a/answer/9281635.",
            "Device contacts that are used in interaction ranking, but have not been uploaded to Google. These are synthesized people from interaction data."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "CloudsearchPeopleSuggestion": {
      "description": "A person suggestion.",
      "id": "CloudsearchPeopleSuggestion",
      "properties": {
        "emailNameMatchInfo": {
          "$ref": "CloudsearchSnippet",
          "description": "This field contains the suggestion information returned by the backend after escaping the HTML in the suggestion string. The areas that we might like to extract from the suggestion string returned by the backend are marked using the match_ranges field inside Snippet. For example, if the snippet string inside email_name_match_info is: \"John Doe - johndoe@google.com\", and the keyword \"doe\" should be matched, the match_ranges is: [[5, 8), [15, 18)]."
        },
        "googleGroup": {
          "$ref": "CloudsearchGroup"
        },
        "person": {
          "$ref": "CloudsearchPerson"
        }
      },
      "type": "object"
    },
    "CloudsearchPerson": {
      "description": "Object to represent a person.",
      "id": "CloudsearchPerson",
      "properties": {
        "emailAddresses": {
          "description": "The person's email addresses",
          "items": {
            "$ref": "CloudsearchEmailAddress"
          },
          "type": "array"
        },
        "name": {
          "description": "The resource name of the person to provide information about. See People.get from Google People API.",
          "type": "string"
        },
        "obfuscatedId": {
          "description": "Obfuscated GAIA ID of a person. Used by first party Cloud Search client, to build a hangout link.",
          "type": "string"
        },
        "personNames": {
          "description": "The person's names",
          "items": {
            "$ref": "CloudsearchName"
          },
          "type": "array"
        },
        "photos": {
          "description": "A person's read-only photo. A picture shown next to the person's name to help others recognize the person in search results.",
          "items": {
            "$ref": "CloudsearchImage"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "CloudsearchQuerySuggestion": {
      "id": "CloudsearchQuerySuggestion",
      "properties": {
        "suggestionMatchInfo": {
          "$ref": "CloudsearchSnippet",
          "description": "This field contains the suggestion match information returned by the backend after escaping the HTML in the suggestion string. The areas that we might like to extract from the suggestion string returned by the backend are marked using the match_ranges field inside Snippet. For example, if the snippet string inside suggestion_match_info is: \"google search\", and the keyword \"goog\" is supposed to be bolded, the match_ranges is the list of range of indexes in the snippe[...]"
        }
      },
      "type": "object"
    },
    "CloudsearchSnippet": {
      "description": "Snippet of the suggestion, which summarizes the content of the resulting page.",
      "id": "CloudsearchSnippet",
      "properties": {
        "matchRanges": {
          "description": "The matched ranges in the snippet.",
          "items": {
            "$ref": "CloudsearchMatchRange"
          },
          "type": "array"
        },
        "snippet": {
          "description": "The snippet of the document.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "CloudsearchSource": {
      "description": "Define a source to query suggest/search APIs. Source is set in the STMixer request params.",
      "id": "CloudsearchSource",
      "properties": {
        "anyThirdPartySource": {
          "description": "If set to true, all 3p sources will be considered",
          "type": "boolean"
        },
        "name": {
          "description": "Source name of contents that indexed by Index API",
          "type": "string"
        },
        "predefinedSource": {
          "description": "Predefined source for Google Apps.",
          "enum": [
            "GENERIC",
            "GROUPS",
            "QUERY_HISTORY",
            "PEOPLE",
            "GOOGLE_DRIVE",
            "GOOGLE_GMAIL",
            "GOOGLE_SITES",
            "GOOGLE_GROUPS",
            "GOOGLE_CALENDAR",
            "GOOGLE_CHAT",
            "GOOGLE_KEEP",
            "ENGDOC",
            "GOOGLE_ATARI",
            "GOOGLE_JOTSPOT",
            "GOOWIKI",
            "MOMA_GLOSSARY",
            "MOMA_UAR",
            "ENGDOC_RESTRICTED",
            "GKMS",
            "X20",
            "YAQS",
            "ENTERPRISE_ASSIST",
            "FILTER"
          ],
          "enumDescriptions": [
            "Default source.",
            "",
            "People API source. Used for suggest API only. Ignored in search API.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "CloudsearchSuggestResponseDebugInfo": {
      "id": "CloudsearchSuggestResponseDebugInfo",
      "properties": {
        "completeServerInfo": {
          "$ref": "CloudsearchSuggestResponseDebugInfoCompleteServerInfo"
        },
        "starlightInfo": {
          "$ref": "CloudsearchSuggestResponseDebugInfoStarlightInfo"
        }
      },
      "type": "object"
    },
    "CloudsearchSuggestResponseDebugInfoCompleteServerInfo": {
      "id": "CloudsearchSuggestResponseDebugInfoCompleteServerInfo",
      "properties": {
        "completeserverHostname": {
          "type": "string"
        },
        "psuggestDoNotCache": {
          "type": "boolean"
        },
        "results": {
          "items": {
            "$ref": "CloudsearchSuggestResponseDebugInfoCompleteServerInfoSuggestResult"
          },
          "type": "array"
        },
        "starlightHostname": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "CloudsearchSuggestResponseDebugInfoCompleteServerInfoSuggestResult": {
      "id": "CloudsearchSuggestResponseDebugInfoCompleteServerInfoSuggestResult",
      "properties": {
        "suggestedQuery": {
          "type": "string"
        },
        "suggestionType": {
          "enum": [
            "UNKNOWN",
            "GMAIL_SUBJECT",
            "CONTACT",
            "PERSON",
            "GMAIL_LABEL",
            "DRIVE_TITLE",
            "GMAIL_OPERATOR",
            "QUERY_PREFIX",
            "GMAIL_QUERY",
            "WEB_QUERY",
            "YOUTUBE_QUERY",
            "MAPS_QUERY",
            "MAPS_FEATURE",
            "MAPS_PLACE_LIST",
            "PHOTO_PERSON",
            "PHOTO_PLACE",
            "PHOTO_THING",
            "PHOTO_ALBUM",
            "PHOTO_DATE",
            "PHOTO_APP_PAGE",
            "PHOTO_OTHER",
            "PHOTO_MEDIA_TYPE",
            "GENERIC_QUERY",
            "PHOTO_CAMERA",
            "CHROME_HISTORY",
            "DEVICE_CONTACT",
            "CONTACT_GROUP",
            "IMAGE_QUERY",
            "LAST_URL",
            "SERP_CLICK",
            "PLAY_STORE_QUERY",
            "PODCASTS_QUERY",
            "CHAT_QUERY",
            "DRIVE_QUERY",
            "CALENDAR_QUERY",
            "TOPAZ_QUERY",
            "SHOPPING_QUERY",
            "WEB_MAPS_FEATURE",
            "LENS_QUERY",
            "IGA_HISTORY",
            "EXPERIMENTAL_QUERY"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "The original query prefix.",
            "",
            "Personalized web query.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Contact label.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "CloudsearchSuggestResponseDebugInfoStarlightInfo": {
      "id": "CloudsearchSuggestResponseDebugInfoStarlightInfo",
      "properties": {
        "compareRankingsScore": {
          "description": "Position-weighted measurement of the difference between the two result sets. See go/search-experiments-glossary - CR Score.",
          "format": "double",
          "type": "number"
        },
        "starlightHostname": {
          "type": "string"
        },
        "suggestResults": {
          "description": "List of suggestion results returned from Starlight for dark launch.",
          "items": {
            "$ref": "CloudsearchSuggestResult"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "CloudsearchSuggestResult": {
      "description": "One suggestion result. next_id: 16",
      "id": "CloudsearchSuggestResult",
      "properties": {
        "encryptedResultDebugId": {
          "type": "string"
        },
        "extension": {
          "$ref": "MessageSet"
        },
        "filterSuggestion": {
          "$ref": "CloudsearchFilterSuggestion"
        },
        "matchedTextInQueryInfo": {
          "description": "Indicates the matches between the suggestion and the user's query. For example, if the user types \"isac xx\" and the returned suggestion is \"Isaac Elias\" then the match is on the token \"isaac\" after spell correction. Note that \"isac\" in user's query matched with \"isaac\" in the suggestion because of spell correction. Also note that spell correction may or may not happen. In this example, matched_text_in_query_info.size() is 1, matched_text_in_query_info(0).snipp[...]",
          "items": {
            "$ref": "CloudsearchSnippet"
          },
          "type": "array"
        },
        "name": {
          "description": "The name of the suggestion. This is unique identifier of the suggestion.",
          "type": "string"
        },
        "peopleSuggestion": {
          "$ref": "CloudsearchPeopleSuggestion"
        },
        "querySuggestion": {
          "$ref": "CloudsearchQuerySuggestion"
        },
        "score": {
          "description": "Final score returned by superroot for this suggestion.",
          "format": "double",
          "type": "number"
        },
        "source": {
          "$ref": "CloudsearchSource"
        },
        "subScores": {
          "$ref": "CloudsearchSuggestionScores"
        },
        "subType": {
          "enum": [
            "NONE",
            "CONTENT_TEXT_SUGGESTION",
            "OPERATOR_NAME_SUGGESTION",
            "OPERATOR_VALUE_SUGGESTION",
            "NL_ENTITY_SUGGESTION",
            "PEOPLE_SUGGESTION"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        },
        "suggestedQuery": {
          "description": "The suggested query that will be used for search, when the user clicks on the suggestion",
          "type": "string"
        },
        "suggestionOrigin": {
          "enum": [
            "DEFAULT",
            "HISTORY",
            "SEARCH_OPERATOR"
          ],
          "enumDescriptions": [
            "Suggestion with default type.",
            "Personal query history.",
            "Suggestion is from search operator index."
          ],
          "type": "string"
        },
        "type": {
          "enum": [
            "UNKNOWN",
            "QUERY_HISTORY",
            "SOURCE_CONTENT",
            "PEOPLE",
            "FILTER",
            "GROUP",
            "USER_QUERY"
          ],
          "enumDescriptions": [
            "Type is not known.",
            "Suggestion from user search history.",
            "Suggestion from content/source.",
            "Suggestion is a person.",
            "Suggestion is a filter.",
            "Suggestion is a group.",
            "User's own query returned as a suggestion"
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "CloudsearchSuggestionScores": {
      "description": "Signals that contribute to the final score.",
      "id": "CloudsearchSuggestionScores",
      "properties": {
        "completeServerInternalScores": {
          "$ref": "CloudsearchSuggestionScoresCompleteServerInternalScores"
        },
        "completeserverInternalScores": {
          "$ref": "CloudsearchSuggestionScoresInternalScores"
        },
        "personalizedBoost": {
          "description": "How frequent is the suggestion within this user.",
          "format": "float",
          "type": "number"
        },
        "popularity": {
          "description": "How popular is the suggestion among all users.",
          "format": "float",
          "type": "number"
        },
        "sectionBoost": {
          "description": "Amount by which a section is boosted based on heuristics.",
          "format": "float",
          "type": "number"
        },
        "sourceScaleFactor": {
          "description": "Scale factor of the datasource its coming from.",
          "format": "float",
          "type": "number"
        },
        "starlightInternalScores": {
          "$ref": "CloudsearchSuggestionScoresInternalScores"
        }
      },
      "type": "object"
    },
    "CloudsearchSuggestionScoresCompleteServerInternalScores": {
      "id": "CloudsearchSuggestionScoresCompleteServerInternalScores",
      "properties": {
        "contactsGroup": {
          "description": "Contacts group score (i.e. if the string is a name of a group).",
          "format": "float",
          "type": "number"
        },
        "emailAutocompleteScore": {
          "description": "Score for email autocomplete. Corresponds to DAS affinity PERSONAL_SUGGEST_EMAIL_AUTOCOMPLETE_SCORE.",
          "format": "float",
          "type": "number"
        },
        "focusOutboundEmailCount": {
          "description": "Outbound email count as read from FBS.",
          "format": "float",
          "type": "number"
        },
        "gmailHistory": {
          "description": "Frequency based score of a query from the user's gmail search history",
          "format": "float",
          "type": "number"
        },
        "gmailHistoryMediumTermQueryTime": {
          "format": "float",
          "type": "number"
        },
        "gmailHistoryShortTermQueryTime": {
          "description": "Both the gmail query_time scores below are based on the time of the last query event. Basically the score is (query_time - (model_time - PERIOD)) / PERIOD Where PERIOD is 1 & 14 days for short and medium term.",
          "format": "float",
          "type": "number"
        },
        "gmailLabel": {
          "description": "Gmail label score, as received from Gmail through PbUI.",
          "format": "float",
          "type": "number"
        },
        "gmailOperator": {
          "description": "Score for gmail operators.",
          "format": "float",
          "type": "number"
        },
        "gmailText": {
          "description": "Score for text entities extracted from gmail subjects.",
          "format": "float",
          "type": "number"
        },
        "matchScore": {
          "description": "The score of the match. The score is in the range [0, num_matching_tokens]. This means that a query with many tokens can have matches with higher score.",
          "format": "double",
          "type": "number"
        },
        "score": {
          "description": "Final score from CompleteServer. This either corresponds to Starlight score or Muppet score (for Generic Suggest suggestions) based on the CompleteServer backend. This is a combination of query dependent and independent components. The scores related to suggestion types like email_autocomplete_score & gmail_text are query independent whereas the match_score is query dependent.",
          "format": "double",
          "type": "number"
        }
      },
      "type": "object"
    },
    "CloudsearchSuggestionScoresInternalScores": {
      "description": "Internal scores from CompleteServer/Starlight. NOTE: This proto message is also being used for storing scores from calling Starlight directly instead from CompleteServer.",
      "id": "CloudsearchSuggestionScoresInternalScores",
      "properties": {
        "contactsGroup": {
          "description": "Contacts group score (i.e. if the string is a name of a group).",
          "format": "float",
          "type": "number"
        },
        "emailAutocompleteScore": {
          "description": "Score for email autocomplete. Corresponds to DAS affinity PERSONAL_SUGGEST_EMAIL_AUTOCOMPLETE_SCORE.",
          "format": "float",
          "type": "number"
        },
        "focusOutboundEmailCount": {
          "description": "Outbound email count as read from FBS.",
          "format": "float",
          "type": "number"
        },
        "gmailHistory": {
          "description": "Frequency based score of a query from the user's gmail search history",
          "format": "float",
          "type": "number"
        },
        "gmailHistoryMediumTermQueryTime": {
          "format": "float",
          "type": "number"
        },
        "gmailHistoryShortTermQueryTime": {
          "description": "Both the gmail query_time scores below are based on the time of the last query event. Basically the score is (query_time - (model_time - PERIOD)) / PERIOD Where PERIOD is 1 & 14 days for short and medium term.",
          "format": "float",
          "type": "number"
        },
        "gmailLabel": {
          "description": "Gmail label score, as received from Gmail through PbUI.",
          "format": "float",
          "type": "number"
        },
        "gmailOperator": {
          "description": "Score for gmail operators.",
          "format": "float",
          "type": "number"
        },
        "gmailText": {
          "description": "Score for text entities extracted from gmail subjects.",
          "format": "float",
          "type": "number"
        },
        "matchScore": {
          "description": "The score of the match. The score is in the range [0, num_matching_tokens]. This means that a query with many tokens can have matches with higher score.",
          "format": "double",
          "type": "number"
        },
        "score": {
          "description": "Final score from CompleteServe / Starlight. This either corresponds to Starlight score or Muppet score (for Generic Suggest suggestions) based on the CompleteServer backend. This is a combination of query dependent and independent components. The scores related to suggestion types like email_autocomplete_score & gmail_text are query independent whereas the match_score is query dependent.",
          "format": "double",
          "type": "number"
        }
      },
      "type": "object"
    },
    "CloudsearchValue": {
      "description": "Definition of a single value with generic type. LINT.IfChange",
      "id": "CloudsearchValue",
      "properties": {
        "booleanValue": {
          "type": "boolean"
        },
        "dateValue": {
          "$ref": "Date"
        },
        "doubleValue": {
          "format": "double",
          "type": "number"
        },
        "integerValue": {
          "format": "int64",
          "type": "string"
        },
        "stringValue": {
          "type": "string"
        },
        "timestampValue": {
          "format": "google-datetime",
          "type": "string"
        }
      },
      "type": "object"
    },
    "CompositeFilter": {
      "id": "CompositeFilter",
      "properties": {
        "logicOperator": {
          "description": "The logic operator of the sub filter.",
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "enumDescriptions": [
            "Logical operators, which can only be applied to sub filters.",
            "",
            "NOT can only be applied on a single sub filter."
          ],
          "type": "string"
        },
        "subFilters": {
          "description": "Sub filters.",
          "items": {
            "$ref": "Filter"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "Content": {
      "id": "Content",
      "properties": {
        "actions": {
          "description": "[Optional] Actions for this card.",
          "items": {
            "$ref": "Action"
          },
          "type": "array"
        },
        "description": {
          "$ref": "SafeHtmlProto",
          "description": "[Optional] Description of the card."
        },
        "subtitle": {
          "$ref": "BackgroundColoredText",
          "description": "[Optional] Subtitle of the card."
        },
        "title": {
          "$ref": "BackgroundColoredText",
          "description": "[Optional] Title of the card."
        }
      },
      "type": "object"
    },
    "Context": {
      "id": "Context",
      "properties": {
        "app": {
          "description": "[Optional] App where the card should be shown. If missing, the card will be shown in TOPAZ.",
          "items": {
            "enum": [
              "UNKNOWN_APP",
              "TOPAZ",
              "MOMA"
            ],
            "enumDescriptions": [
              "",
              "",
              ""
            ],
            "type": "string"
          },
          "type": "array"
        },
        "dayOfWeek": {
          "description": "[Optional] Day of week when the card should be shown, where 0 is Monday.",
          "items": {
            "format": "int32",
            "type": "integer"
          },
          "type": "array"
        },
        "endDateSec": {
          "description": "[Optional] Date (in seconds since epoch) when the card should stop being shown. If missing, end_date_sec will be set to Jan 1st, 2100.",
          "format": "int64",
          "type": "string"
        },
        "endDayOffsetSec": {
          "description": "[Optional] End time in seconds, within a day, when the card should stop being shown if it's within [start_date_sec, end_date_sec]. If missing, this is set to 86400 (24 hours x 3600 sec/hour), i.e., midnight next day.",
          "format": "int64",
          "type": "string"
        },
        "locale": {
          "description": "[Optional] The locales for which the card should be triggered (e.g., en_US and en_CA). If missing, the card is going to show to clients regardless of their locale.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "location": {
          "description": "[Optional] Text-free locations where the card should be shown. This is expected to match the user's location in focus. If no location is specified, the card will be shown for any location.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "query": {
          "description": "[Required only for Answer and RHS cards - will be ignored for Homepage] cards. It's the exact case-insensitive queries that will trigger the Answer or RHS card.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "startDateSec": {
          "description": "[Optional] Date (in seconds since epoch) when the card should start being shown. If missing, start_date_sec will be Jan 1st, 1970 UTC.",
          "format": "int64",
          "type": "string"
        },
        "startDayOffsetSec": {
          "description": "[Optional] Start time in seconds, within a day, when the card should be shown if it's within [start_date_sec, end_date_sec]. If 0, the card will be shown from 12:00am on.",
          "format": "int64",
          "type": "string"
        },
        "surface": {
          "description": "[Optional] Surface where the card should be shown in. If missing, the card will be shown in any surface.",
          "items": {
            "enum": [
              "UNKNOWN_SURFACE",
              "DESKTOP",
              "ANDROID",
              "IOS",
              "MOBILE",
              "ANY"
            ],
            "enumDescriptions": [
              "",
              "",
              "",
              "",
              "Any mobile device.",
              ""
            ],
            "type": "string"
          },
          "type": "array"
        },
        "type": {
          "description": "[Required] Type of the card (homepage, Answer or RHS).",
          "items": {
            "enum": [
              "UNKNOWN_CARD_TYPE",
              "HOMEPAGE_CARD",
              "ANSWER_CARD",
              "RHS_CARD"
            ],
            "enumDescriptions": [
              "",
              "",
              "",
              ""
            ],
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ContextAttribute": {
      "description": "A named attribute associated with an item which can be used for influencing the ranking of the item based on the context in the request.",
      "id": "ContextAttribute",
      "properties": {
        "name": {
          "description": "The name of the attribute. It should not be empty. The maximum length is 32 characters. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The name will be normalized (lower-cased) before being matched.",
          "type": "string"
        },
        "values": {
          "description": "Text values of the attribute. The maximum number of elements is 10. The maximum length of an element in the array is 32 characters. The value will be normalized (lower-cased) before being matched.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "CustomerIndexStats": {
      "description": "Aggregation of items by status code as of the specified date.",
      "id": "CustomerIndexStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which statistics were calculated."
        },
        "itemCountByStatus": {
          "description": "Number of items aggregrated by status code.",
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "CustomerQueryStats": {
      "id": "CustomerQueryStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which query stats were calculated. Stats calculated on the next day close to midnight are returned."
        },
        "queryCountByStatus": {
          "items": {
            "$ref": "QueryCountByStatus"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "CustomerSearchApplicationStats": {
      "description": "Search application stats for a customer for the given date.",
      "id": "CustomerSearchApplicationStats",
      "properties": {
        "count": {
          "description": "The count of search applications for the date.",
          "format": "int64",
          "type": "string"
        },
        "date": {
          "$ref": "Date",
          "description": "The date for which search application stats were calculated."
        }
      },
      "type": "object"
    },
    "CustomerSessionStats": {
      "id": "CustomerSessionStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned."
        },
        "searchSessionsCount": {
          "description": "The count of search sessions on the day",
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "CustomerSettings": {
      "description": "Represents settings at a customer level.",
      "id": "CustomerSettings",
      "properties": {
        "auditLoggingSettings": {
          "$ref": "AuditLoggingSettings",
          "description": "Audit Logging settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request."
        },
        "vpcSettings": {
          "$ref": "VPCSettings",
          "description": "VPC SC settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request."
        }
      },
      "type": "object"
    },
    "CustomerUserStats": {
      "id": "CustomerUserStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which session stats were calculated. Stats calculated on the next day close to midnight are returned."
        },
        "oneDayActiveUsersCount": {
          "description": "The count of unique active users in the past one day",
          "format": "int64",
          "type": "string"
        },
        "sevenDaysActiveUsersCount": {
          "description": "The count of unique active users in the past seven days",
          "format": "int64",
          "type": "string"
        },
        "thirtyDaysActiveUsersCount": {
          "description": "The count of unique active users in the past thirty days",
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DataSource": {
      "description": "Datasource is a logical namespace for items to be indexed. All items must belong to a datasource. This is the prerequisite before items can be indexed into Cloud Search. ",
      "id": "DataSource",
      "properties": {
        "disableModifications": {
          "description": "If true, sets the datasource to read-only mode. In read-only mode, the Indexing API rejects any requests to index or delete items in this source. Enabling read-only mode does not stop the processing of previously accepted data.",
          "type": "boolean"
        },
        "disableServing": {
          "description": "Disable serving any search or assist results.",
          "type": "boolean"
        },
        "displayName": {
          "description": "Required. Display name of the datasource The maximum length is 300 characters.",
          "type": "string"
        },
        "indexingServiceAccounts": {
          "description": "List of service accounts that have indexing access.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "itemsVisibility": {
          "description": "This field restricts visibility to items at the datasource level. Items within the datasource are restricted to the union of users and groups included in this field. Note that, this does not ensure access to a specific item, as users need to have ACL permissions on the contained items. This ensures a high level access on the entire datasource, and that the individual items are not shared outside this visibility.",
          "items": {
            "$ref": "GSuitePrincipal"
          },
          "type": "array"
        },
        "name": {
          "description": "The name of the datasource resource. Format: datasources/{source_id}. The name is ignored when creating a datasource.",
          "type": "string"
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "returnThumbnailUrls": {
          "description": "Can a user request to get thumbnail URI for Items indexed in this data source.",
          "type": "boolean"
        },
        "shortName": {
          "description": "A short name or alias for the source. This value will be used to match the 'source' operator. For example, if the short name is *<value>* then queries like *source:<value>* will only return results for this source. The value must be unique across all datasources. The value must only contain alphanumeric characters (a-zA-Z0-9). The value cannot start with 'google' and cannot be one of the following: mail, gmail, docs, drive, groups, sites, calendar, hangouts, gplus, keep[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DataSourceIndexStats": {
      "description": "Aggregation of items by status code as of the specified date.",
      "id": "DataSourceIndexStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which index stats were calculated. If the date of request is not the current date then stats calculated on the next day are returned. Stats are calculated close to mid night in this case. If date of request is current date, then real time stats are returned."
        },
        "itemCountByStatus": {
          "description": "Number of items aggregrated by status code.",
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "DataSourceRestriction": {
      "description": "Restriction on Datasource.",
      "id": "DataSourceRestriction",
      "properties": {
        "filterOptions": {
          "description": "Filter options restricting the results. If multiple filters are present, they are grouped by object type before joining. Filters with the same object type are joined conjunctively, then the resulting expressions are joined disjunctively. The maximum number of elements is 20. NOTE: Suggest API supports only few filters at the moment: \"objecttype\", \"type\" and \"mimetype\". For now, schema specific filters cannot be used to filter suggestions.",
          "items": {
            "$ref": "FilterOptions"
          },
          "type": "array"
        },
        "source": {
          "$ref": "Source",
          "description": "The source of restriction."
        }
      },
      "type": "object"
    },
    "Date": {
      "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.",
      "id": "Date",
      "properties": {
        "day": {
          "description": "Day of month. Must be from 1 to 31 and valid for the year and month.",
          "format": "int32",
          "type": "integer"
        },
        "month": {
          "description": "Month of date. Must be from 1 to 12.",
          "format": "int32",
          "type": "integer"
        },
        "year": {
          "description": "Year of date. Must be from 1 to 9999.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "DateOperatorOptions": {
      "description": "Optional. Provides a search operator for date properties. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "DateOperatorOptions",
      "properties": {
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the date property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:<value>* show results only where the value of the property named *closeDate* is later than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the date property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:<value>* show results only where the value of the property named *closeDate* is earlier than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        },
        "operatorName": {
          "description": "Indicates the actual string required in the query in order to isolate the date property. For example, suppose an issue tracking schema object has a property named *closeDate* that specifies an operator with an operatorName of *closedon*. For searches on that data, queries like *closedon:<value>* show results only where the value of the *closeDate* property matches *<value>*. By contrast, a search that uses the same *<value>* without an operator returns all items where *[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DatePropertyOptions": {
      "description": "The options for date properties.",
      "id": "DatePropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "DateOperatorOptions",
          "description": "If set, describes how the date should be used as a search operator."
        }
      },
      "type": "object"
    },
    "DateValues": {
      "description": "List of date values.",
      "id": "DateValues",
      "properties": {
        "values": {
          "items": {
            "$ref": "Date"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "DebugOptions": {
      "description": "Shared request debug options for all cloudsearch RPC methods.",
      "id": "DebugOptions",
      "properties": {
        "enableDebugging": {
          "description": "If you are asked by Google to help with debugging, set this field. Otherwise, ignore this field.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "DebugResponse": {
      "description": "Debug Search Response.",
      "id": "DebugResponse",
      "properties": {
        "gsrRequest": {
          "description": "Serialized string of GenericSearchRequest.",
          "format": "byte",
          "type": "string"
        },
        "gsrResponse": {
          "description": "Serialized string of GenericSearchResponse.",
          "format": "byte",
          "type": "string"
        },
        "searchResponse": {
          "$ref": "SearchResponse",
          "description": "Search response."
        }
      },
      "type": "object"
    },
    "DefaultBlockingDataProto": {
      "description": "Next ID: 3",
      "id": "DefaultBlockingDataProto",
      "properties": {
        "types": {
          "items": {
            "enum": [
              "BLOCKING_TYPE_UNSPECIFIED",
              "BLOCKING_TYPE_DEFAULT_BLOCKED",
              "BLOCKING_TYPE_DEFAULT_BLOCKED_NON_TYPE_COUNTRY"
            ],
            "enumDescriptions": [
              "The default value. Not actually used by IPGeo/Oolong.",
              "Under go/embargo.",
              "A feature that is not a TYPE_COUNTRY and is under go/embargo. Discouraged."
            ],
            "type": "string"
          },
          "type": "array"
        },
        "version": {
          "description": "Version ID of the current list of blocked countries and sanctions areas, based on which the types field was computed.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "DeleteQueueItemsRequest": {
      "id": "DeleteQueueItemsRequest",
      "properties": {
        "connectorName": {
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "queue": {
          "description": "The name of a queue to delete items from.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DisabledIcingPackageCorpus": {
      "id": "DisabledIcingPackageCorpus",
      "properties": {
        "corpusName": {
          "description": "The name of an individual corpus within the given app. When unset, this means that all corpora for the given package are disabled.",
          "type": "string"
        },
        "packageName": {
          "description": "The package name of an app that the user disabled. This is required.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DisplayedProperty": {
      "description": "A reference to a top-level property within the object that should be displayed in search results. The values of the chosen properties is displayed in the search results along with the display label for that property if one is specified. If a display label is not specified, only the values is shown.",
      "id": "DisplayedProperty",
      "properties": {
        "propertyName": {
          "description": "The name of the top-level property as defined in a property definition for the object. If the name is not a defined property in the schema, an error is given when attempting to update the schema.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DoubleOperatorOptions": {
      "description": "Used to provide a search operator for double properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "DoubleOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to use the double property in sorting or as a facet. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DoublePropertyOptions": {
      "description": "The options for double properties.",
      "id": "DoublePropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "DoubleOperatorOptions",
          "description": "If set, describes how the double should be used as a search operator."
        }
      },
      "type": "object"
    },
    "DoubleValues": {
      "description": "List of double values.",
      "id": "DoubleValues",
      "properties": {
        "values": {
          "items": {
            "format": "double",
            "type": "number"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "DriveFollowUpRestrict": {
      "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\").",
      "id": "DriveFollowUpRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "FOLLOWUP_SUGGESTIONS",
            "FOLLOWUP_ACTION_ITEMS"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "DriveLocationRestrict": {
      "description": "Drive location search restricts (e.g. \"is:starred\").",
      "id": "DriveLocationRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "TRASHED",
            "STARRED"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "DriveMimeTypeRestrict": {
      "description": "Drive mime-type search restricts (e.g. \"type:pdf\").",
      "id": "DriveMimeTypeRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "PDF",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "FORM",
            "DRAWING",
            "SCRIPT",
            "MAP",
            "IMAGE",
            "AUDIO",
            "VIDEO",
            "FOLDER",
            "ARCHIVE",
            "SITE"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "DriveTimeSpanRestrict": {
      "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
      "id": "DriveTimeSpanRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "TODAY",
            "YESTERDAY",
            "LAST_7_DAYS",
            "LAST_30_DAYS",
            "LAST_90_DAYS"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Not Enabled",
            "Not Enabled"
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EmailAddress": {
      "description": "A person's email address.",
      "id": "EmailAddress",
      "properties": {
        "customType": {
          "description": "If the value of type is custom, this property contains the custom type string.",
          "type": "string"
        },
        "emailAddress": {
          "description": "The email address.",
          "type": "string"
        },
        "emailUrl": {
          "description": "The URL to send email.",
          "type": "string"
        },
        "primary": {
          "description": "Indicates if this is the user's primary email. Only one entry can be marked as primary.",
          "type": "boolean"
        },
        "type": {
          "description": "The type of the email account. Acceptable values are: \"custom\", \"home\", \"other\", \"work\".",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazFrontendTeamsLink": {
      "id": "EnterpriseTopazFrontendTeamsLink",
      "properties": {
        "type": {
          "description": "The identifying link type",
          "type": "string"
        },
        "url": {
          "$ref": "SafeUrlProto"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazFrontendTeamsPersonCorePhoneNumber": {
      "id": "EnterpriseTopazFrontendTeamsPersonCorePhoneNumber",
      "properties": {
        "phoneNumber": {
          "description": "Phone number in no particular format (as comes from the Focus profile).",
          "type": "string"
        },
        "phoneUrl": {
          "$ref": "SafeUrlProto",
          "description": "Phone number URL"
        },
        "type": {
          "enum": [
            "UNKNOWN",
            "MOBILE",
            "OFFICE",
            "OTHER"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAgendaEntry": {
      "description": "An AgendaEntry, e.g., a Calendar Event.",
      "id": "EnterpriseTopazSidekickAgendaEntry",
      "properties": {
        "agendaItemUrl": {
          "description": "URL of the agenda item.",
          "type": "string"
        },
        "chronology": {
          "description": "The chronology from the present.",
          "enum": [
            "STALE",
            "ALL_DAY",
            "PAST",
            "RECENTLY_PAST",
            "PRESENT",
            "NEAR_FUTURE",
            "FUTURE"
          ],
          "enumDescriptions": [
            "Stale.",
            "All day.",
            "Past.",
            "Recently past.",
            "Present.",
            "Near future.",
            "Future."
          ],
          "type": "string"
        },
        "creator": {
          "$ref": "EnterpriseTopazSidekickPerson",
          "description": "Person who created the event."
        },
        "currentUserAttendingStatus": {
          "description": "Attendance status for the current user making the request. This is a convenience data member in order to avoid figuring out the same by iterating the invitee list above on the caller side.",
          "enum": [
            "AWAITING",
            "YES",
            "NO",
            "MAYBE"
          ],
          "enumDescriptions": [
            "Awaiting for the user to set the status.",
            "Attending.",
            "Not attending.",
            "Tentatively attending."
          ],
          "type": "string"
        },
        "description": {
          "description": "Description of the agenda item (i.e., typically, summary in calendar event).",
          "type": "string"
        },
        "document": {
          "description": "Items related to the current AgendaEntry. E.g., related drive/mail/groups documents.",
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonDocument"
          },
          "type": "array"
        },
        "endDate": {
          "description": "End date \"Friday, August 26\" in the user's timezone.",
          "type": "string"
        },
        "endTime": {
          "description": "End time (HH:mm) in the user's timezone.",
          "type": "string"
        },
        "endTimeMs": {
          "description": "End time in milliseconds",
          "format": "int64",
          "type": "string"
        },
        "eventId": {
          "description": "Event id provided by Calendar API.",
          "type": "string"
        },
        "guestsCanInviteOthers": {
          "description": "Whether the guests can invite other guests.",
          "type": "boolean"
        },
        "guestsCanModify": {
          "description": "Whether the guests can modify the event.",
          "type": "boolean"
        },
        "guestsCanSeeGuests": {
          "description": "Whether the guests of the event can be seen. If false, the user is going to be reported as the only attendee to the meeting, even though there may be more attendees.",
          "type": "boolean"
        },
        "hangoutId": {
          "description": "Hangout meeting identifier.",
          "type": "string"
        },
        "hangoutUrl": {
          "description": "Absolute URL for the Hangout meeting.",
          "type": "string"
        },
        "invitee": {
          "description": "People attending the meeting.",
          "items": {
            "$ref": "EnterpriseTopazSidekickPerson"
          },
          "type": "array"
        },
        "isAllDay": {
          "description": "Whether the entry lasts all day.",
          "type": "boolean"
        },
        "lastModificationTimeMs": {
          "description": "Last time the event was modified.",
          "format": "int64",
          "type": "string"
        },
        "location": {
          "description": "Agenda item location.",
          "type": "string"
        },
        "notifyToUser": {
          "description": "Whether this should be notified to the user.",
          "type": "boolean"
        },
        "otherAttendeesExcluded": {
          "description": "Whether guest list is not returned because number of attendees is too large.",
          "type": "boolean"
        },
        "requesterIsOwner": {
          "description": "Whether the requester is the owner of the agenda entry.",
          "type": "boolean"
        },
        "showFullEventDetailsToUse": {
          "description": "Whether the details of this entry should be displayed to the user.",
          "type": "boolean"
        },
        "startDate": {
          "description": "Start date \"Friday, August 26\" in the user's timezone.",
          "type": "string"
        },
        "startTime": {
          "description": "Start time (HH:mm) in the user's timezone.",
          "type": "string"
        },
        "startTimeMs": {
          "description": "Start time in milliseconds.",
          "format": "int64",
          "type": "string"
        },
        "timeZone": {
          "description": "User's calendar timezone;",
          "type": "string"
        },
        "title": {
          "description": "Title of the agenda item.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAgendaGroupCardProto": {
      "id": "EnterpriseTopazSidekickAgendaGroupCardProto",
      "properties": {
        "agendaItem": {
          "items": {
            "$ref": "EnterpriseTopazSidekickAgendaItem"
          },
          "type": "array"
        },
        "context": {
          "$ref": "EnterpriseTopazSidekickAgendaGroupCardProtoContext"
        },
        "currentAgendaItem": {
          "$ref": "EnterpriseTopazSidekickAgendaItem"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAgendaGroupCardProtoContext": {
      "description": "The context that resulted in the generation of the card.",
      "id": "EnterpriseTopazSidekickAgendaGroupCardProtoContext",
      "properties": {
        "context": {
          "description": "User friendly free text that describes the context of the card (e.g. \"Next meeting with Bob\"). This is largely only applicable when the card is generated from a query.",
          "type": "string"
        },
        "date": {
          "description": "Localized free text that describes the dates represented by the card. Currently, the card will only represent a single day.",
          "type": "string"
        },
        "eventsRestrict": {
          "description": "Represents restrictions applied to the events requested in the user's query.",
          "enum": [
            "NONE",
            "NEXT_MEETING"
          ],
          "enumDescriptions": [
            "No specific event was requested.",
            "The next meeting was requested."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAgendaItem": {
      "id": "EnterpriseTopazSidekickAgendaItem",
      "properties": {
        "conflictedGroup": {
          "$ref": "EnterpriseTopazSidekickConflictingEventsCardProto"
        },
        "gapBefore": {
          "$ref": "EnterpriseTopazSidekickGap"
        },
        "meeting": {
          "$ref": "EnterpriseTopazSidekickAgendaEntry"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAnswerAnswerList": {
      "description": "A list of answers represented as free text.",
      "id": "EnterpriseTopazSidekickAnswerAnswerList",
      "properties": {
        "labeledAnswer": {
          "description": "Answers that have a corresponding label.",
          "items": {
            "$ref": "EnterpriseTopazSidekickAnswerAnswerListLabeledAnswer"
          },
          "type": "array"
        },
        "type": {
          "description": "Answer type.",
          "enum": [
            "UNKNOWN",
            "PERSON_ADDRESS",
            "PERSON_BIRTHDAY",
            "PERSON_DEPARTMENT",
            "PERSON_DESK_LOCATION",
            "PERSON_EMAIL",
            "PERSON_JOB_TITLE",
            "PERSON_PHONE"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAnswerAnswerListLabeledAnswer": {
      "description": "An answer with a corresponding label.",
      "id": "EnterpriseTopazSidekickAnswerAnswerListLabeledAnswer",
      "properties": {
        "answer": {
          "description": "The free text answer.",
          "type": "string"
        },
        "label": {
          "description": "A localized label for the answer (e.g. \"Cell phone\" vs \"Desk phone\").",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAnswerSuggestedQueryAnswerCard": {
      "description": "Contains a list of suggested queries. Allows the user to determine what natural language queries they can ask Cloud Search (e.g. \"what can I search for?\").",
      "id": "EnterpriseTopazSidekickAnswerSuggestedQueryAnswerCard",
      "properties": {
        "suggestedQueryCategory": {
          "description": "A list of queries to suggest.",
          "items": {
            "$ref": "EnterpriseTopazSidekickAnswerSuggestedQueryCategory"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAnswerSuggestedQueryCategory": {
      "description": "Contains a list of suggested queries for a single category.",
      "id": "EnterpriseTopazSidekickAnswerSuggestedQueryCategory",
      "properties": {
        "category": {
          "description": "The query list category.",
          "enum": [
            "UNKNOWN",
            "CALENDAR",
            "DOCUMENT",
            "PEOPLE"
          ],
          "enumDescriptions": [
            "Unknown.",
            "Calendar based queries (e.g. \"my agenda for tomorrow\").",
            "Document based queries (e.g. \"files shared with me\").",
            "People based queries (e.g. \"what is x's email address?\")."
          ],
          "type": "string"
        },
        "isEnabled": {
          "description": "Whether this category is enabled.",
          "type": "boolean"
        },
        "query": {
          "description": "List of suggested queries to show the user.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAssistCardProto": {
      "description": "Wrapper proto for the Assist cards.",
      "id": "EnterpriseTopazSidekickAssistCardProto",
      "properties": {
        "agendaGroupCardProto": {
          "$ref": "EnterpriseTopazSidekickAgendaGroupCardProto",
          "description": "Agenda group card."
        },
        "cardMetadata": {
          "$ref": "EnterpriseTopazSidekickCardMetadata",
          "description": "Card metadata such as chronology and render mode of the card."
        },
        "cardType": {
          "description": "Card type.",
          "enum": [
            "UNKNOWN_TYPE",
            "AGENDA",
            "CHANGELISTS",
            "CONFLICTING_MEETINGS",
            "CREATE_NOTES_FOR_MEETING",
            "CREATE_NOTES_FOR_MEETING_REQUEST",
            "CUSTOMER_NEWS",
            "FIND_MEETING_TIME",
            "NEXT_MEETING",
            "PERSONALIZED_DOCS",
            "TRENDING_DOCS",
            "UPCOMING_TRIP",
            "SUMMARY",
            "MEETINGS",
            "HOMEPAGE",
            "SHARE_MEETING_DOCS",
            "DISCOVER_PEOPLE",
            "HOMEPAGE_V3",
            "AGENDA_GROUP",
            "WORK_IN_PROGRESS",
            "GET_AND_KEEP_AHEAD",
            "GENERIC_ANSWER_CARD",
            "THIRD_PARTY_ANSWER_CARD",
            "DOMAIN_TRENDING_DOCS",
            "TEAM_TRENDING_DOCS",
            "DOCUMENT_LIST_ANSWER_CARD",
            "SUGGESTED_QUERY_ANSWER_CARD",
            "PERSON_ANSWER_CARD",
            "RELATED_PEOPLE_ANSWER_CARD",
            "PERSON_KNOWLEDGE_CARD",
            "PEOPLE_SEARCH_PROMOTION_CARD"
          ],
          "enumDeprecated": [
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false
          ],
          "enumDescriptions": [
            "The default type, an unknown card type.",
            "The user's agenda for the day.",
            "Changelists.",
            "Any group of meetings for the day that are overlapping.",
            "Create notes for a meeting specified in the request.",
            "Create notes for meeting query.",
            "News about your SFDC customers.",
            "Find a time for two people to meet.",
            "The user's next non-declined meeting.",
            "Important documents for you since you have viewed them in the last month and there's some action going on.",
            "Documents that are trending in your company. A TRENDING_DOCS card can be of two types: TRENDING_IN_COLLABORATORS (i.e., Stay in the Loop) and TRENDING_IN_DOMAIN (i.e., Popular Content). Use DOMAIN_TRENDING_DOCS/TEAM_TRENDING_DOCS instead.",
            "An upcoming trip with all trip information along with calendar events in the destination timezone.",
            "The Morning/Evening Summary Card for the next working day.",
            "A meeting. When requesting meetings, the service will return a MEETING card for each meeting the user has in his agenda.",
            "All cards related to the homepage (agenda, conflicting-meetings, summary, etc...). This type should no longer be used. Use HOMEPAGE_V3 instead.",
            "A card to with specifics to share meeting documents with all attendees.",
            "Represents a set of users that the requesting user has low affinity with.",
            "All cards related to the homepage-v3 (agenda-group, WIP, etc...)",
            "A group of agenda-events (meeting, conflicts)",
            "The documents that you were recently working on.",
            "(v3) The \"get and keep ahead\" card for today and tomorrow",
            "Generic answer card.",
            "Third party answer card.",
            "Documents that are trending in your company/domain (i.e., Popular Content).",
            "Documents that are trending in your team (i.e., Stay in the Loop).",
            "Documents that match the user's query (e.g. sheets shared with me).",
            "A help card that provides examples of queries the user can ask.",
            "Answer card for a single person (e.g. what is x's phone number).",
            "Answer card for a list of people related to the person that is the subject of the query (e.g. who reports to x).",
            "Knowledge card for a single person and their related people.",
            "People Search promotion card."
          ],
          "type": "string"
        },
        "conflictingMeetingsCard": {
          "$ref": "EnterpriseTopazSidekickConflictingEventsCardProto",
          "deprecated": true,
          "description": "Conflicting events card."
        },
        "documentListCard": {
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList",
          "description": "Answer card for documents that are applicable to the current query."
        },
        "documentsWithMentions": {
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList",
          "deprecated": true,
          "description": "Documents with mentions."
        },
        "findMeetingTimeCard": {
          "$ref": "EnterpriseTopazSidekickFindMeetingTimeCardProto",
          "description": "Find meeting time card."
        },
        "genericAnswerCard": {
          "$ref": "EnterpriseTopazSidekickGenericAnswerCard",
          "description": "Generic answer card."
        },
        "getAndKeepAheadCard": {
          "$ref": "EnterpriseTopazSidekickGetAndKeepAheadCardProto",
          "description": "Get and keep ahead card."
        },
        "meeting": {
          "$ref": "EnterpriseTopazSidekickAgendaEntry",
          "deprecated": true,
          "description": "Meeting card."
        },
        "meetingNotesCard": {
          "$ref": "EnterpriseTopazSidekickMeetingNotesCardProto",
          "description": "Meeting notes card."
        },
        "meetingNotesCardRequest": {
          "$ref": "EnterpriseTopazSidekickMeetingNotesCardRequest",
          "description": "Request for meeting notes card."
        },
        "peopleDisambiguationCard": {
          "$ref": "EnterpriseTopazSidekickPeopleDisambiguationCard",
          "description": "The people disambiguation card."
        },
        "peoplePromotionCard": {
          "$ref": "PeoplePromotionCard",
          "description": "People Search promotion card."
        },
        "personAnswerCard": {
          "$ref": "EnterpriseTopazSidekickPeopleAnswerPersonAnswerCard",
          "description": "Answer card that represents a single person."
        },
        "personProfileCard": {
          "$ref": "EnterpriseTopazSidekickPersonProfileCard",
          "description": "Full profile card."
        },
        "personalizedDocsCard": {
          "$ref": "EnterpriseTopazSidekickPersonalizedDocsCardProto",
          "deprecated": true,
          "description": "Card with recommended documents for the user."
        },
        "relatedPeopleAnswerCard": {
          "$ref": "EnterpriseTopazSidekickPeopleAnswerRelatedPeopleAnswerCard",
          "description": "Answer card that represents a list of people related to a person."
        },
        "shareMeetingDocsCard": {
          "$ref": "EnterpriseTopazSidekickShareMeetingDocsCardProto",
          "deprecated": true,
          "description": "Sahre meeting docs card."
        },
        "sharedDocuments": {
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList",
          "deprecated": true,
          "description": "Shared documents."
        },
        "suggestedQueryAnswerCard": {
          "$ref": "EnterpriseTopazSidekickAnswerSuggestedQueryAnswerCard",
          "description": "Answer card for what natural language queries the user can ask."
        },
        "thirdPartyAnswerCard": {
          "$ref": "ThirdPartyGenericCard",
          "description": "Third party answer cards."
        },
        "workInProgressCardProto": {
          "$ref": "EnterpriseTopazSidekickRecentDocumentsCardProto",
          "description": "Work In Progress card."
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCardMetadata": {
      "description": "Card metadata.",
      "id": "EnterpriseTopazSidekickCardMetadata",
      "properties": {
        "cardCategory": {
          "description": "Declares a preference for how this card should be packed in MSCR. All cards in a response must correspond to a single category. As a result, cards may be dropped from the response if this field is set. Any card that does not match the category of the card with the highest priority in the response will be dropped.",
          "enum": [
            "DEFAULT",
            "ANSWER",
            "KNOWLEDGE",
            "HOMEPAGE"
          ],
          "enumDescriptions": [
            "Let MSCR decide how this card should be packed. Most cards should choose this type. This type should largely be considered equivalent to ANSWER. However, this is not guaranteed to be the case as the request to MSCR may override the static configuration.",
            "This card should be rendered as an answer card.",
            "This card should be rendered as a knowledge card (a non-organic result).",
            "This card should be rendered in the Homepage."
          ],
          "type": "string"
        },
        "cardId": {
          "description": "An ID to identify the card and match actions to it. Be thoughtful of new card IDs since actions will be associated to that ID. E.g., if two card IDs collide, the system will think that the actions have been applied to the same card. Similarly, if EAS can return multiple cards of the same type (e.g., Meetings), ensure that the card_id identifies a given instance of the card so that, e.g., dismissals only affect the dismissed card as opposed to affecting all meeting cards[...]",
          "type": "string"
        },
        "chronology": {
          "description": "Chronology.",
          "enum": [
            "UNKNOWN",
            "PAST",
            "RECENTLY_PAST",
            "PRESENT",
            "NEAR_FUTURE",
            "FUTURE"
          ],
          "enumDescriptions": [
            "Unknown chronology (default).",
            "Past.",
            "Recently past.",
            "Present.",
            "Near future.",
            "Future."
          ],
          "type": "string"
        },
        "debugInfo": {
          "description": "Debug info (only reported if request's debug_level > 0).",
          "type": "string"
        },
        "nlpMetadata": {
          "$ref": "EnterpriseTopazSidekickNlpMetadata",
          "description": "Information about the NLP done to get the card."
        },
        "rankingParams": {
          "$ref": "EnterpriseTopazSidekickRankingParams",
          "description": "Ranking params."
        },
        "renderMode": {
          "description": "Render mode.",
          "enum": [
            "UNKNOWN_RENDER",
            "COLLAPSED",
            "EXPANDED"
          ],
          "enumDescriptions": [
            "Unknown mode (default).",
            "Collapsed.",
            "Expanded."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCommonDebugInfo": {
      "description": "Container of debugging information in all object levels. Extend as needed.",
      "id": "EnterpriseTopazSidekickCommonDebugInfo",
      "properties": {
        "message": {
          "description": "Debug message.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCommonDocument": {
      "description": "Representation of a document. NEXT_TAG: 15",
      "id": "EnterpriseTopazSidekickCommonDocument",
      "properties": {
        "accessType": {
          "description": "Access type, i.e., whether the user has access to the document or not.",
          "enum": [
            "UNKNOWN_ACCESS",
            "ALLOWED",
            "NOT_ALLOWED"
          ],
          "enumDescriptions": [
            "Unknown access type.",
            "Access allowed.",
            "Access not allowed."
          ],
          "type": "string"
        },
        "debugInfo": {
          "$ref": "EnterpriseTopazSidekickCommonDebugInfo",
          "description": "Information for debugging."
        },
        "documentId": {
          "description": "Document id.",
          "type": "string"
        },
        "driveDocumentMetadata": {
          "$ref": "EnterpriseTopazSidekickCommonDocumentDriveDocumentMetadata",
          "description": "Drive document metadata."
        },
        "genericUrl": {
          "description": "Generic Drive-based url in the format of drive.google.com/open to be used for deeplink",
          "type": "string"
        },
        "justification": {
          "$ref": "EnterpriseTopazSidekickCommonDocumentJustification",
          "description": "Justification on why the document is selected."
        },
        "mimeType": {
          "description": "MIME type",
          "type": "string"
        },
        "provenance": {
          "deprecated": true,
          "description": "Document provenance.",
          "enum": [
            "UNKNOWN_PROVENANCE",
            "CALENDAR_DESCRIPTION",
            "CALENDAR_ATTACHMENT",
            "MINED",
            "CALENDAR_ASSIST_ATTACHMENT"
          ],
          "enumDescriptions": [
            "Unknown provenance.",
            "Calendar event description.",
            "Calendar event attachment.",
            "Mined (extracted by some offline/online analysis).",
            "Attachment created by enterprise assist."
          ],
          "type": "string"
        },
        "reason": {
          "deprecated": true,
          "description": "Justification of why this document is being returned.",
          "enum": [
            "UNKNOWN",
            "TRENDING_IN_COLLABORATORS",
            "TRENDING_IN_DOMAIN",
            "FREQUENTLY_VIEWED",
            "FREQUENTLY_EDITED",
            "NEW_UPDATES",
            "NEW_COMMENTS",
            "EVENT_DESCRIPTION",
            "EVENT_ATTACHMENT",
            "EVENT_METADATA_ATTACHMENT",
            "MINED_DOCUMENT",
            "NEW_MENTIONS",
            "NEW_SHARES"
          ],
          "enumDescriptions": [
            "Unknown justification.",
            "Popular documents within collaborators.",
            "Popular documents within the domain.",
            "Documents being reviewed frequently by the current user .",
            "Documents being edited frequently by the current user .",
            "Documents updated since user's last visit.",
            "Documents that receive comments since user's last visit.",
            "Documents in the calendar event description.",
            "Documents in the calendar event attachments section.",
            "Documents attached in calendar event metadata instead of the attachment section. Event metadata is not visible to the final user. Enterprise assist uses this metadata to store auto-generated documents such as meeting notes.",
            "Documents mined, and so, probably related to the request context. For example, this category includes documents related to a meeting.",
            "Documents that contains mentions of the user.",
            "Documents that are shared with the user."
          ],
          "type": "string"
        },
        "snippet": {
          "description": "A sampling of the text from the document.",
          "type": "string"
        },
        "thumbnailUrl": {
          "description": "Thumbnail URL.",
          "type": "string"
        },
        "title": {
          "description": "Title of the document.",
          "type": "string"
        },
        "type": {
          "description": "Type of the document.",
          "enum": [
            "UNKNOWN",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "PDF",
            "IMAGE",
            "BINARY_BLOB",
            "FUSION_TABLE",
            "FOLDER",
            "DRAWING",
            "VIDEO",
            "FORM",
            "LINK_URL",
            "LINK_GO",
            "LINK_GOO_GL",
            "LINK_BIT_LY",
            "LINK_GMAIL",
            "LINK_MAILTO",
            "VIDEO_YOUTUBE",
            "VIDEO_LIVE",
            "GROUPS",
            "NEWS",
            "SITES",
            "HANGOUT",
            "AUDIO",
            "MS_WORD",
            "MS_POWERPOINT",
            "MS_EXCEL",
            "MS_OUTLOOK"
          ],
          "enumDescriptions": [
            "If the type is unknown or not represented in this enum.",
            "Drive document types Writely, Word, etc.",
            "Presently, PowerPoint, etc.",
            "Trix, Excel, etc.",
            "File types for Gdrive objects are below. PDF.",
            "Image.",
            "Fall-back for unknown Gdrive types.",
            "Fusion table.",
            "Folder.",
            "Drawing.",
            "Video.",
            "Form.",
            "Link formats uncategorized URL links",
            "meaningful links that should be renderred specifically",
            "Link to goo.gl.",
            "Link to bit_ly.",
            "Link to Gmail.",
            "Mailto link.",
            "Videos Youtube videos.",
            "Live streams (e.g., liveplayer.googleplex.com)",
            "Other types. Google Groups.",
            "Google News.",
            "Google Sites.",
            "Google Hangout.",
            "Audio files.",
            "Microsoft-specific file types.",
            "",
            "",
            ""
          ],
          "type": "string"
        },
        "url": {
          "description": "Absolute URL of the document.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCommonDocumentDriveDocumentMetadata": {
      "description": "Meta data for drive documents.",
      "id": "EnterpriseTopazSidekickCommonDocumentDriveDocumentMetadata",
      "properties": {
        "documentId": {
          "deprecated": true,
          "description": "The drive document cosmo id. Client could use the id to build a URL to open a document. Please use Document.document_id.",
          "type": "string"
        },
        "isPrivate": {
          "description": "Additional field to identify whether a document is private since scope set to LIMITED can mean both that the doc is private or that it's shared with others. is_private indicates whether the doc is not shared with anyone except for the owner.",
          "type": "boolean"
        },
        "lastCommentTimeMs": {
          "description": "Timestamp of the most recent comment added to the document in milliseconds since epoch.",
          "format": "uint64",
          "type": "string"
        },
        "lastEditTimeMs": {
          "description": "Timestamp of the most recent edit from the current user in milliseconds since epoch.",
          "format": "uint64",
          "type": "string"
        },
        "lastModificationTimeMillis": {
          "description": "Last modification time of the document (independent of the user that modified it).",
          "format": "int64",
          "type": "string"
        },
        "lastUpdatedTimeMs": {
          "description": "Timestamp of the last updated time of the document in milliseconds since epoch.",
          "format": "uint64",
          "type": "string"
        },
        "lastViewTimeMs": {
          "description": "Timestamp of the most recent view from the current user in milliseconds since epoch.",
          "format": "uint64",
          "type": "string"
        },
        "owner": {
          "$ref": "EnterpriseTopazSidekickCommonPerson",
          "description": "The owner of the document."
        },
        "scope": {
          "description": "ACL scope of the document which identifies the sharing status of the doc (e.g., limited, shared with link, team drive, ...).",
          "enum": [
            "UNKNOWN_DOCUMENT_SCOPE",
            "LIMITED",
            "DASHER_DOMAIN_WITH_LINK",
            "DASHER_DOMAIN",
            "PUBLIC_WITH_LINK",
            "PUBLIC",
            "TEAM_DRIVE"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCommonDocumentJustification": {
      "description": "Justification of why we are reporting the document.",
      "id": "EnterpriseTopazSidekickCommonDocumentJustification",
      "properties": {
        "justification": {
          "description": "A locale aware message that explains why this document was selected.",
          "type": "string"
        },
        "reason": {
          "description": "Reason on why the document is selected. Populate for trending documents.",
          "enum": [
            "UNKNOWN",
            "TRENDING_IN_COLLABORATORS",
            "TRENDING_IN_DOMAIN",
            "FREQUENTLY_VIEWED",
            "FREQUENTLY_EDITED",
            "NEW_UPDATES",
            "NEW_COMMENTS",
            "EVENT_DESCRIPTION",
            "EVENT_ATTACHMENT",
            "EVENT_METADATA_ATTACHMENT",
            "MINED_DOCUMENT",
            "NEW_MENTIONS",
            "NEW_SHARES"
          ],
          "enumDescriptions": [
            "Unknown justification.",
            "Popular documents within collaborators.",
            "Popular documents within the domain.",
            "Documents being reviewed frequently by the current user .",
            "Documents being edited frequently by the current user .",
            "Documents updated since user's last visit.",
            "Documents that receive comments since user's last visit.",
            "Documents in the calendar event description.",
            "Documents in the calendar event attachments section.",
            "Documents attached in calendar event metadata instead of the attachment section. Event metadata is not visible to the final user. Enterprise assist uses this metadata to store auto-generated documents such as meeting notes.",
            "Documents mined, and so, probably related to the request context. For example, this category includes documents related to a meeting.",
            "Documents that contains mentions of the user.",
            "Documents that are shared with the user."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCommonPerson": {
      "description": "Common representation of a person.",
      "id": "EnterpriseTopazSidekickCommonPerson",
      "properties": {
        "birthday": {
          "$ref": "EnterpriseTopazSidekickCommonPersonBirthday",
          "description": "The birthday."
        },
        "cellPhone": {
          "description": "Cell phone number.",
          "type": "string"
        },
        "department": {
          "description": "The department the person works in (e.g. Engineering).",
          "type": "string"
        },
        "deskLocation": {
          "description": "Desk location (e.g. US-MTV-PR55-5-5B1I).",
          "type": "string"
        },
        "deskPhone": {
          "description": "Work desk phone number.",
          "type": "string"
        },
        "displayName": {
          "description": "The full name.",
          "type": "string"
        },
        "email": {
          "description": "Email.",
          "type": "string"
        },
        "familyName": {
          "description": "The last name.",
          "type": "string"
        },
        "fullAddress": {
          "description": "The fully formatted address (e.g. 1255 Pear Avenue, Mountain View 94043, United States).",
          "type": "string"
        },
        "gaiaId": {
          "deprecated": true,
          "description": "This field is deprecated. The obfuscated_id should be used instead.",
          "format": "int64",
          "type": "string"
        },
        "givenName": {
          "description": "The first name.",
          "type": "string"
        },
        "jobTitle": {
          "description": "The person's job title (e.g. Software Engineer).",
          "type": "string"
        },
        "manager": {
          "$ref": "EnterpriseTopazSidekickCommonPerson",
          "description": "The manager."
        },
        "obfuscatedId": {
          "description": "The obfuscated GAIA ID.",
          "type": "string"
        },
        "photoUrl": {
          "description": "The URL for the Focus profile picture.",
          "type": "string"
        },
        "streetAddress": {
          "description": "The street address (e.g. 1255 Pear Avenue).",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCommonPersonBirthday": {
      "id": "EnterpriseTopazSidekickCommonPersonBirthday",
      "properties": {
        "value": {
          "description": "Unstructured birthday.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickConflictingEventsCardProto": {
      "description": "Conflicting meetings card proto.",
      "id": "EnterpriseTopazSidekickConflictingEventsCardProto",
      "properties": {
        "conflictingEvent": {
          "description": "All the events that conflict with main_event.",
          "items": {
            "$ref": "EnterpriseTopazSidekickAgendaEntry"
          },
          "type": "array"
        },
        "mainEvent": {
          "$ref": "EnterpriseTopazSidekickAgendaEntry",
          "description": "The event identified as being the most important."
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickDocumentGroup": {
      "description": "Represents a mapping between a document type and its corresponding documents. Use for Work in Progress card in v1 homepage.",
      "id": "EnterpriseTopazSidekickDocumentGroup",
      "properties": {
        "groupType": {
          "deprecated": true,
          "description": "Document group type",
          "enum": [
            "UNKNOWN_TYPE",
            "ALL"
          ],
          "enumDescriptions": [
            "Unknown type.",
            "A mix of all the document types."
          ],
          "type": "string"
        },
        "personalizedDocument": {
          "description": "The list of corresponding documents.",
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonDocument"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickDocumentPerCategoryList": {
      "id": "EnterpriseTopazSidekickDocumentPerCategoryList",
      "properties": {
        "documents": {
          "items": {
            "$ref": "EnterpriseTopazSidekickDocumentPerCategoryListDocumentPerCategoryListEntry"
          },
          "type": "array"
        },
        "helpMessage": {
          "description": "Localized message explaining how the documents were derived (e.g. from the last 30 days activity). This field is optional.",
          "type": "string"
        },
        "listType": {
          "enum": [
            "UNKNOWN_LIST_TYPE",
            "MENTIONS",
            "SHARES",
            "NEEDS_ATTENTION",
            "VIEWS",
            "EDITS"
          ],
          "enumDescriptions": [
            "",
            "All documents in the list correspond to one of the mention categories.",
            "All documents in the list correspond to one of the share categories.",
            "A mixture of document categories that correspond to documents that need the users attention (e.g. documents that have been explicitly shared with the user but have not been viewed and documents where the user was mentioned but has not replied).",
            "All documents in the list correspond to one of the view categories.",
            "All documents in the list correspond to one of the edit categories."
          ],
          "type": "string"
        },
        "listTypeDescription": {
          "description": "Description of the types of documents present in the list.",
          "type": "string"
        },
        "responseMessage": {
          "description": "Response message in case no documents are present in the card.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickDocumentPerCategoryListDocumentPerCategoryListEntry": {
      "id": "EnterpriseTopazSidekickDocumentPerCategoryListDocumentPerCategoryListEntry",
      "properties": {
        "category": {
          "enum": [
            "UNKNOWN_DOCUMENT",
            "ACTIONABLE",
            "VIEWED",
            "REPLIED",
            "MENTION_VIEWED",
            "MENTION_REPLIED",
            "MENTION_NOT_VIEWED",
            "SHARED_AND_VIEWED",
            "SHARED_NOT_VIEWED",
            "EDITED"
          ],
          "enumDeprecated": [
            false,
            true,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Mention categories. The mention has been viewed by the user, but the user has not replied.",
            "The user has replied to the mention.",
            "The mention has not been viewed by the user.",
            "Share categories. Consists of documents that have been explicitly shared with the user. Document has been viewed.",
            "Document has not been viewed.",
            "Document has been edited."
          ],
          "type": "string"
        },
        "document": {
          "$ref": "EnterpriseTopazSidekickCommonDocument"
        },
        "rationale": {
          "description": "Reason this document was selected.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickFindMeetingTimeCardProto": {
      "description": "Response to find meeting time among a set of people.",
      "id": "EnterpriseTopazSidekickFindMeetingTimeCardProto",
      "properties": {
        "commonAvailableTimeSlots": {
          "description": "Slots when all attendees have availability.",
          "items": {
            "$ref": "EnterpriseTopazSidekickTimeSlot"
          },
          "type": "array"
        },
        "invitees": {
          "description": "Invitees to the event.",
          "items": {
            "$ref": "EnterpriseTopazSidekickPerson"
          },
          "type": "array"
        },
        "requester": {
          "$ref": "EnterpriseTopazSidekickPerson",
          "description": "Requester."
        },
        "scheduledMeeting": {
          "$ref": "EnterpriseTopazSidekickScheduledMeeting",
          "description": "Details about the scheduled meeting, if one exists."
        },
        "skippedInvitees": {
          "description": "Invitees that have been skipped in the computation, most likely because they are groups.",
          "items": {
            "$ref": "EnterpriseTopazSidekickPerson"
          },
          "type": "array"
        },
        "timeBoundaries": {
          "$ref": "EnterpriseTopazSidekickTimeSlot",
          "description": "Min and max timestamp used to find a common available timeslot."
        },
        "timezoneId": {
          "description": "Timezone ID.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickGap": {
      "id": "EnterpriseTopazSidekickGap",
      "properties": {
        "displayRemainingTime": {
          "description": "Localized time string in the format: 1 hour 15 minutes",
          "type": "string"
        },
        "endTime": {
          "description": "Localized time string in the format:(Locale CZ) 8:30 odp.",
          "type": "string"
        },
        "endTimeMs": {
          "format": "uint64",
          "type": "string"
        },
        "remainingTime": {
          "format": "google-duration",
          "type": "string"
        },
        "startTime": {
          "description": "Localized time string in the format:(Locale CZ) 8:30 odp.",
          "type": "string"
        },
        "startTimeMs": {
          "format": "uint64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickGenericAnswerCard": {
      "id": "EnterpriseTopazSidekickGenericAnswerCard",
      "properties": {
        "answer": {
          "description": "The answer.",
          "type": "string"
        },
        "title": {
          "description": "Title or header of the card.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickGetAndKeepAheadCardProto": {
      "description": "Get and keep ahead card",
      "id": "EnterpriseTopazSidekickGetAndKeepAheadCardProto",
      "properties": {
        "declinedEvents": {
          "$ref": "EnterpriseTopazSidekickGetAndKeepAheadCardProtoDeclinedEvents"
        },
        "mentionedDocuments": {
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList"
        },
        "sharedDocuments": {
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickGetAndKeepAheadCardProtoDeclinedEvents": {
      "description": "A list of events where all guests declined.",
      "id": "EnterpriseTopazSidekickGetAndKeepAheadCardProtoDeclinedEvents",
      "properties": {
        "events": {
          "items": {
            "$ref": "EnterpriseTopazSidekickAgendaEntry"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickMeetingNotesCardError": {
      "description": "Errors in the creation of meeting notes.",
      "id": "EnterpriseTopazSidekickMeetingNotesCardError",
      "properties": {
        "description": {
          "description": "The description of the reason why create-meeting-notes failed.",
          "type": "string"
        },
        "event": {
          "$ref": "EnterpriseTopazSidekickAgendaEntry",
          "description": "The event to request meeting notes creation"
        },
        "reason": {
          "description": "The reason why create-meeting-notes failed.",
          "enum": [
            "NONE",
            "NOT_OWNER",
            "UNKNOWN"
          ],
          "enumDescriptions": [
            "No reason (default value).",
            "The user is not an owner.",
            "Unknown reason."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickMeetingNotesCardProto": {
      "description": "Information about the meeting notes created.",
      "id": "EnterpriseTopazSidekickMeetingNotesCardProto",
      "properties": {
        "event": {
          "$ref": "EnterpriseTopazSidekickAgendaEntry",
          "description": "The event to request meeting notes creation."
        },
        "fileId": {
          "description": "Google Drive ID (a.k.a. resource ID) of the file.",
          "type": "string"
        },
        "title": {
          "description": "Title we want to show for meeting notes in the answer card",
          "type": "string"
        },
        "url": {
          "description": "New URL.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickMeetingNotesCardRequest": {
      "description": "Meeting notes card request.",
      "id": "EnterpriseTopazSidekickMeetingNotesCardRequest",
      "properties": {
        "canCreateFor": {
          "description": "Who are the meeting notes created for.",
          "items": {
            "enum": [
              "UNKNOWN",
              "MYSELF",
              "ALL_ATTENDEES"
            ],
            "enumDescriptions": [
              "Unknown (default).",
              "For the requester.",
              "For all the meeting attendees."
            ],
            "type": "string"
          },
          "type": "array"
        },
        "error": {
          "$ref": "EnterpriseTopazSidekickMeetingNotesCardError",
          "description": "The error and reason if known error occured."
        },
        "event": {
          "$ref": "EnterpriseTopazSidekickAgendaEntry",
          "description": "The event to request meeting notes creation"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickNlpMetadata": {
      "description": "Metadata about the NLP interpretation of the query.",
      "id": "EnterpriseTopazSidekickNlpMetadata",
      "properties": {
        "confidence": {
          "description": "Confidence of the interpretation that generated this card.",
          "format": "float",
          "type": "number"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfo": {
      "description": "Metadata for disambiguation.",
      "id": "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfo",
      "properties": {
        "disambiguation": {
          "description": "A list of people that also matched the query. This list is not complete.",
          "items": {
            "$ref": "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfoDisambiguationPerson"
          },
          "type": "array"
        },
        "name": {
          "description": "The name that was extracted from the query. This may be in the form of the given name, last name, full name, LDAP, or email address. This name can be considered suitable for displaying to the user and can largely be considered to be normalized (e.g. \"Bob's\" -> \"Bob\").",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfoDisambiguationPerson": {
      "description": "A person that also matches the query, but was not selected due to a lower affinity with the requesting user.",
      "id": "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfoDisambiguationPerson",
      "properties": {
        "person": {
          "$ref": "EnterpriseTopazSidekickCommonPerson",
          "description": "The profile of this person."
        },
        "query": {
          "description": "The query that can be used to produce an answer card with the same attribute, but for this person.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPeopleAnswerPeopleAnswerCardHeader": {
      "description": "Recommended header to display for the card.",
      "id": "EnterpriseTopazSidekickPeopleAnswerPeopleAnswerCardHeader",
      "properties": {
        "title": {
          "description": "The suggested title to display. This defaults to the user's query.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPeopleAnswerPersonAnswerCard": {
      "description": "An answer card for a single person.",
      "id": "EnterpriseTopazSidekickPeopleAnswerPersonAnswerCard",
      "properties": {
        "answer": {
          "deprecated": true,
          "description": "List of answers.",
          "items": {
            "$ref": "SafeHtmlProto"
          },
          "type": "array"
        },
        "answerText": {
          "$ref": "EnterpriseTopazSidekickAnswerAnswerList",
          "description": "List of answers."
        },
        "disambiguationInfo": {
          "$ref": "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfo",
          "description": "Disambiguation information."
        },
        "header": {
          "$ref": "EnterpriseTopazSidekickPeopleAnswerPeopleAnswerCardHeader",
          "description": "The header to display for the card."
        },
        "responseStatus": {
          "description": "The response status.",
          "enum": [
            "UNKNOWN",
            "SUCCESS",
            "MISSING_PERSON",
            "MISSING_DATA"
          ],
          "enumDescriptions": [
            "Unknown.",
            "Success.",
            "No such person was found in the user's domain.",
            "A person was found to match the query, but an answer could not be obtained."
          ],
          "type": "string"
        },
        "statusMessage": {
          "description": "Localized user friendly message to display to the user in the case of missing data or an error.",
          "type": "string"
        },
        "subject": {
          "$ref": "EnterpriseTopazSidekickCommonPerson",
          "description": "The profile of the person that was the subject of the query."
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPeopleAnswerRelatedPeopleAnswerCard": {
      "description": "An answer card for a list of people that are related to the subject of the query.",
      "id": "EnterpriseTopazSidekickPeopleAnswerRelatedPeopleAnswerCard",
      "properties": {
        "disambiguationInfo": {
          "$ref": "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfo",
          "description": "Disambiguation information."
        },
        "header": {
          "$ref": "EnterpriseTopazSidekickPeopleAnswerPeopleAnswerCardHeader",
          "description": "The header to display for the card."
        },
        "relatedPeople": {
          "description": "A list of people that are related to the query subject.",
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonPerson"
          },
          "type": "array"
        },
        "relationType": {
          "description": "Defines the type of relation the list of people have with the subject of the card.",
          "enum": [
            "UNKNOWN",
            "DIRECT_REPORTS",
            "MANAGER",
            "PEERS"
          ],
          "enumDescriptions": [
            "Unknown.",
            "Direct reports.",
            "The manager.",
            "The teammates/peers of the subject."
          ],
          "type": "string"
        },
        "responseStatus": {
          "description": "The response status.",
          "enum": [
            "UNKNOWN",
            "SUCCESS",
            "MISSING_PERSON",
            "MISSING_DATA"
          ],
          "enumDescriptions": [
            "Unknown.",
            "Success.",
            "No such person was found in the user's domain.",
            "A person was found to match the query, but an answer could not be obtained."
          ],
          "type": "string"
        },
        "statusMessage": {
          "description": "Localized user friendly message to display to the user in the case of missing data or an error.",
          "type": "string"
        },
        "subject": {
          "$ref": "EnterpriseTopazSidekickCommonPerson",
          "description": "The profile of the person that was the subject of the query."
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPeopleDisambiguationCard": {
      "id": "EnterpriseTopazSidekickPeopleDisambiguationCard",
      "properties": {
        "person": {
          "description": "Candidate persons for the query.",
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonPerson"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPerson": {
      "description": "Person.",
      "id": "EnterpriseTopazSidekickPerson",
      "properties": {
        "affinityLevel": {
          "description": "The level of affinity this person has with the requesting user.",
          "enum": [
            "UNKNOWN",
            "LOW",
            "MEDIUM",
            "HIGH"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        },
        "attendingStatus": {
          "description": "Attendance status of the person when included in a meeting event.",
          "enum": [
            "AWAITING",
            "YES",
            "NO",
            "MAYBE"
          ],
          "enumDescriptions": [
            "Awaiting for the user to set the status.",
            "Attending.",
            "Not attending.",
            "Tentatively attending."
          ],
          "type": "string"
        },
        "email": {
          "description": "Email.",
          "type": "string"
        },
        "gaiaId": {
          "deprecated": true,
          "description": "Gaia id.",
          "format": "int64",
          "type": "string"
        },
        "isGroup": {
          "description": "Whether the invitee is a group.",
          "type": "boolean"
        },
        "name": {
          "description": "Name.",
          "type": "string"
        },
        "obfuscatedGaiaId": {
          "description": "Obfuscated Gaia id.",
          "type": "string"
        },
        "photoUrl": {
          "description": "Absolute URL to the profile photo of the person.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPersonProfileCard": {
      "id": "EnterpriseTopazSidekickPersonProfileCard",
      "properties": {
        "relatedPeople": {
          "items": {
            "$ref": "EnterpriseTopazSidekickPersonProfileCardRelatedPeople"
          },
          "type": "array"
        },
        "subject": {
          "$ref": "EnterpriseTopazSidekickCommonPerson",
          "description": "The subject of the card."
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPersonProfileCardRelatedPeople": {
      "id": "EnterpriseTopazSidekickPersonProfileCardRelatedPeople",
      "properties": {
        "relatedPerson": {
          "description": "Related people.",
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonPerson"
          },
          "type": "array"
        },
        "relation": {
          "description": "Relation type.",
          "enum": [
            "UNKNOWN",
            "MANAGER",
            "DIRECT_REPORT"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPersonalizedDocsCardProto": {
      "description": "Personalized docs card proto.",
      "id": "EnterpriseTopazSidekickPersonalizedDocsCardProto",
      "properties": {
        "documentGroup": {
          "description": "Document group.",
          "items": {
            "$ref": "EnterpriseTopazSidekickDocumentGroup"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickRankingParams": {
      "description": "Ranking params.",
      "id": "EnterpriseTopazSidekickRankingParams",
      "properties": {
        "endTimeMs": {
          "description": "The end-time that this object will expect to occur. If the type is marked as FIXED, then this end-time will persist after bidding. If the type is marked as FLEXIBLE, this field is NOT expected to be filled and will be filled in after it has won a bid. Expected to be set when type is set to FIXED.",
          "format": "uint64",
          "type": "string"
        },
        "priority": {
          "description": "The priority to determine between objects that have the same start_time_ms The lower-value of priority == ranked higher. Max-priority = 0. Expected to be set for all types.",
          "enum": [
            "UNKNOWN",
            "CRITICAL",
            "IMPORTANT",
            "HIGH",
            "NORMAL",
            "BEST_EFFORT"
          ],
          "enumDescriptions": [
            "Unknown (default).",
            "Critical.",
            "Important.",
            "High.",
            "Normal.",
            "Best effort."
          ],
          "type": "string"
        },
        "score": {
          "description": "The score of the card to be used to break priority-ties",
          "format": "float",
          "type": "number"
        },
        "spanMs": {
          "description": "The span that this card will take in the stream Expected to be set when type is set to FLEXIBLE.",
          "format": "uint64",
          "type": "string"
        },
        "startTimeMs": {
          "description": "The start-time that this object will bid-for If the type is marked as FIXED, then this start-time will persist after bidding. If the type is marked as FLEXIBLE, then it will occur at the given time or sometime after the requested time. Expected to be set for all types.",
          "format": "uint64",
          "type": "string"
        },
        "type": {
          "description": "The packing type of this object.",
          "enum": [
            "FIXED",
            "FLEXIBLE"
          ],
          "enumDescriptions": [
            "Fixed, i.e., the card is time sensitive.",
            "Flexible, i.e., the card is not time sensitive."
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickRecentDocumentsCardProto": {
      "id": "EnterpriseTopazSidekickRecentDocumentsCardProto",
      "properties": {
        "document": {
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonDocument"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickScheduledMeeting": {
      "description": "Details about scheduled meetings.",
      "id": "EnterpriseTopazSidekickScheduledMeeting",
      "properties": {
        "meetingLocation": {
          "description": "The meeting location.",
          "type": "string"
        },
        "meetingTime": {
          "$ref": "EnterpriseTopazSidekickTimeSlot",
          "description": "The meeting time slot."
        },
        "meetingTitle": {
          "description": "The meeting title.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickShareMeetingDocsCardProto": {
      "description": "Share meeting docs card proto.",
      "id": "EnterpriseTopazSidekickShareMeetingDocsCardProto",
      "properties": {
        "document": {
          "description": "Documents to share for the given meeting.",
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonDocument"
          },
          "type": "array"
        },
        "event": {
          "$ref": "EnterpriseTopazSidekickAgendaEntry",
          "description": "Event."
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickTimeSlot": {
      "description": "Slot of time.",
      "id": "EnterpriseTopazSidekickTimeSlot",
      "properties": {
        "endTimeDay": {
          "description": "Day end time at the user's timezone.",
          "type": "string"
        },
        "endTimeHourAndMinute": {
          "description": "Hour and minute of the end time at the user's timezone.",
          "type": "string"
        },
        "endTimeInMillis": {
          "description": "End time in milliseconds.",
          "format": "int64",
          "type": "string"
        },
        "startTimeDay": {
          "description": "Day start time at user's timezone.",
          "type": "string"
        },
        "startTimeHourAndMinute": {
          "description": "Hour and minute of the start time at the user's timezone.",
          "type": "string"
        },
        "startTimeInMillis": {
          "description": "Start time in milliseconds.",
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnumOperatorOptions": {
      "description": "Used to provide a search operator for enum properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched. For example, if you provide no operator for a *priority* enum property with possible values *p0* and *p1*, a query that contains the term *p0* returns items that have *p0* as the value of the *priority* property, as well as any items that contain the string *p0* in other fields. If you provide [...]",
      "id": "EnumOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the enum property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:<value>* show results only where the value of the property named *priorityVal* matches *<value>*. By contrast, a search that uses the same *<value>* without an operator returns all items where *<value>* matches the value of any String properties or text within the content[...]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnumPropertyOptions": {
      "description": "The options for enum properties, which allow you to define a restricted set of strings to match user queries, set rankings for those string values, and define an operator name to be paired with those strings so that users can narrow results to only items with a specific value. For example, for items in a request tracking system with priority information, you could define *p0* as an allowable enum value and tie this enum to the operator name *priority* so that search users c[...]",
      "id": "EnumPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "EnumOperatorOptions",
          "description": "If set, describes how the enum should be used as a search operator."
        },
        "orderedRanking": {
          "description": "Used to specify the ordered ranking for the enumeration that determines how the integer values provided in the possible EnumValuePairs are used to rank results. If specified, integer values must be provided for all possible EnumValuePair values given for this property. Can only be used if isRepeatable is false.",
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "enumDescriptions": [
            "There is no ranking order for the property. Results aren't adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ],
          "type": "string"
        },
        "possibleValues": {
          "description": "The list of possible values for the enumeration property. All EnumValuePairs must provide a string value. If you specify an integer value for one EnumValuePair, then all possible EnumValuePairs must provide an integer value. Both the string value and integer value must be unique over all possible values. Once set, possible values cannot be removed or modified. If you supply an ordered ranking and think you might insert additional enum values in the future, leave gaps in[...]",
          "items": {
            "$ref": "EnumValuePair"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "EnumValuePair": {
      "description": "The enumeration value pair defines two things: a required string value and an optional integer value. The string value defines the necessary query term required to retrieve that item, such as *p0* for a priority item. The integer value determines the ranking of that string value relative to other enumerated values for the same property. For example, you might associate *p0* with *0* and define another enum pair such as *p1* and *1*. You must use the integer value in combina[...]",
      "id": "EnumValuePair",
      "properties": {
        "integerValue": {
          "description": "The integer value of the EnumValuePair which must be non-negative. Optional.",
          "format": "int32",
          "type": "integer"
        },
        "stringValue": {
          "description": "The string value of the EnumValuePair. The maximum length is 32 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnumValues": {
      "description": "List of enum values.",
      "id": "EnumValues",
      "properties": {
        "values": {
          "description": "The maximum allowable length for string values is 32 characters.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ErrorInfo": {
      "description": "Error information about the response.",
      "id": "ErrorInfo",
      "properties": {
        "errorMessages": {
          "items": {
            "$ref": "ErrorMessage"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ErrorMessage": {
      "description": "Error message per source response.",
      "id": "ErrorMessage",
      "properties": {
        "errorMessage": {
          "type": "string"
        },
        "source": {
          "$ref": "Source"
        }
      },
      "type": "object"
    },
    "FacetBucket": {
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise either a single value OR a contiguous range of values, depending on the type of the field bucketed. FacetBucket is currently used only for returning the response object.",
      "id": "FacetBucket",
      "properties": {
        "count": {
          "description": "Number of results that match the bucket value. Counts are only returned for searches when count accuracy is ensured. Cloud Search does not guarantee facet counts for any query and facet counts might be present only intermittently, even for identical queries. Do not build dependencies on facet count existence; instead use facet ount percentages which are always returned.",
          "format": "int32",
          "type": "integer"
        },
        "filter": {
          "$ref": "Filter",
          "description": "Filter to be passed in the search request if the corresponding bucket is selected."
        },
        "percentage": {
          "description": "Percent of results that match the bucket value. The returned value is between (0-100], and is rounded down to an integer if fractional. If the value is not explicitly returned, it represents a percentage value that rounds to 0. Percentages are returned for all searches, but are an estimate. Because percentages are always returned, you should render percentages instead of counts.",
          "format": "int32",
          "type": "integer"
        },
        "value": {
          "$ref": "Value"
        }
      },
      "type": "object"
    },
    "FacetOptions": {
      "description": "Specifies operators to return facet results for. There will be one FacetResult for every source_name/object_type/operator_name combination.",
      "id": "FacetOptions",
      "properties": {
        "integerFacetingOptions": {
          "$ref": "IntegerFacetingOptions",
          "description": "If set, describes integer faceting options for the given integer property. The corresponding integer property in the schema should be marked isFacetable. The number of buckets returned would be minimum of this and num_facet_buckets."
        },
        "numFacetBuckets": {
          "description": "Maximum number of facet buckets that should be returned for this facet. Defaults to 10. Maximum value is 100.",
          "format": "int32",
          "type": "integer"
        },
        "objectType": {
          "description": "If object_type is set, only those objects of that type will be used to compute facets. If empty, then all objects will be used to compute facets.",
          "type": "string"
        },
        "operatorName": {
          "description": "The name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name to facet on. Format: datasources/{source_id} If empty, all data sources will be used.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "FacetResult": {
      "description": "Source specific facet response",
      "id": "FacetResult",
      "properties": {
        "buckets": {
          "description": "FacetBuckets for values in response containing at least a single result with the corresponding filter.",
          "items": {
            "$ref": "FacetBucket"
          },
          "type": "array"
        },
        "objectType": {
          "description": "Object type for which facet results are returned. Can be empty.",
          "type": "string"
        },
        "operatorName": {
          "description": "The name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name for which facet results are returned. Will not be empty.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "FieldViolation": {
      "id": "FieldViolation",
      "properties": {
        "description": {
          "description": "The description of the error.",
          "type": "string"
        },
        "field": {
          "description": "Path of field with violation.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "Filter": {
      "description": "A generic way of expressing filters in a query, which supports two approaches: **1. Setting a ValueFilter.** The name must match an operator_name defined in the schema for your data source. **2. Setting a CompositeFilter.** The filters are evaluated using the logical operator. The top-level operators can only be either an AND or a NOT. AND can appear only at the top-most level. OR can appear only under a top-level AND.",
      "id": "Filter",
      "properties": {
        "compositeFilter": {
          "$ref": "CompositeFilter"
        },
        "valueFilter": {
          "$ref": "ValueFilter"
        }
      },
      "type": "object"
    },
    "FilterOptions": {
      "description": "Filter options to be applied on query.",
      "id": "FilterOptions",
      "properties": {
        "filter": {
          "$ref": "Filter",
          "description": "Generic filter to restrict the search, such as `lang:en`, `site:xyz`."
        },
        "objectType": {
          "description": "If object_type is set, only objects of that type are returned. This should correspond to the name of the object that was registered within the definition of schema. The maximum length is 256 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "FreshnessOptions": {
      "description": "Indicates which freshness property to use when adjusting search ranking for an item. Fresher, more recent dates indicate higher quality. Use the freshness option property that best works with your data. For fileshare documents, last modified time is most relevant. For calendar event data, the time when the event occurs is a more relevant freshness indicator. In this way, calendar events that occur closer to the time of the search query are considered higher quality and rank[...]",
      "id": "FreshnessOptions",
      "properties": {
        "freshnessDuration": {
          "description": "The duration after which an object should be considered stale. The default value is 180 days (in seconds).",
          "format": "google-duration",
          "type": "string"
        },
        "freshnessProperty": {
          "description": "This property indicates the freshness level of the object in the index. If set, this property must be a top-level property within the property definitions and it must be a timestamp type or date type. Otherwise, the Indexing API uses updateTime as the freshness indicator. The maximum length is 256 characters. When a property is used to calculate freshness, the value defaults to 2 years from the current time.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "GSuitePrincipal": {
      "id": "GSuitePrincipal",
      "properties": {
        "gsuiteDomain": {
          "description": "This principal represents all users of the Google Workspace domain of the customer.",
          "type": "boolean"
        },
        "gsuiteGroupEmail": {
          "description": "This principal references a Google Workspace group name.",
          "type": "string"
        },
        "gsuiteUserEmail": {
          "description": "This principal references a Google Workspace user account.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "GeostoreFeatureIdProto": {
      "description": "A globally unique identifier associated with each feature. We use 128-bit identifiers so that we have lots of bits available to distinguish between features. The feature id currently consists of a 64-bit \"cell id\" that **sometimes** corresponds to the approximate centroid of the feature, plus a 64-bit fingerprint of other identifying information. See more on each respective field in its comments. Feature ids are first assigned when the data is created in MapFacts. After i[...]",
      "id": "GeostoreFeatureIdProto",
      "properties": {
        "cellId": {
          "description": "The S2CellId corresponding to the approximate location of this feature as of when it was first created. This can be of variable accuracy, ranging from the exact centroid of the feature at creation, a very large S2 Cell, or even being completely randomized for locationless features. Cell ids have the nice property that they follow a space-filling curve over the surface of the earth. (See s2cellid.h for details.) WARNING: Clients should only use cell IDs to perform spatia[...]",
          "format": "uint64",
          "type": "string"
        },
        "fprint": {
          "description": "A 64-bit fingerprint used to identify features. Most clients should rely on MapFacts or OneRing to choose fingerprints. If creating new fprints, the strategy should be chosen so that the chance of collision is remote or non-existent, and the distribution should be reasonably uniform. For example, if the source data assigns unique ids to features, then a fingerprint of the provider name, version, and source id is sufficient.",
          "format": "uint64",
          "type": "string"
        },
        "temporaryData": {
          "$ref": "MessageSet",
          "description": "A place for clients to attach arbitrary data to a feature ID. Never set in MapFacts."
        }
      },
      "type": "object"
    },
    "GeostoreFieldMetadataProto": {
      "description": "Internal field metadata. This part is not exposed to downstream consumers of the repository (read-only clients) but is available to upstream providers to the repository (read-write clients).",
      "id": "GeostoreFieldMetadataProto",
      "properties": {
        "internal": {
          "$ref": "GeostoreInternalFieldMetadataProto"
        }
      },
      "type": "object"
    },
    "GeostoreInternalFieldMetadataProto": {
      "id": "GeostoreInternalFieldMetadataProto",
      "properties": {
        "isAuto": {
          "description": "Whether or not the piece of data has been generated automatically (i.e., by a bot/automated process based on heuristics/algorithms rather than coming as a fact set by some human user or data provider based on their knowledge). Note that this does NOT imply that the value was set as a result of a bot operation on the repository, since it is conceivable to use a bot/automated process simply as a way of convenience to ingest large amount of canonical/ground truth data.",
          "type": "boolean"
        },
        "sourceSummary": {
          "$ref": "GeostoreInternalSourceSummaryProto",
          "description": "Information about the source providing the piece of data this metadata is attached to."
        }
      },
      "type": "object"
    },
    "GeostoreInternalSourceSummaryProto": {
      "id": "GeostoreInternalSourceSummaryProto",
      "properties": {
        "dataset": {
          "description": "Within the above provider, the dataset from which this piece of data was generated. For fields that are auto-generated the \"dataset\" is likely to be some algorithm's or program's name. Similar to SourceInfoProto.dataset but with the difference that it is required to always be set. Providers that don't have a concept of dataset may use \"default\".",
          "type": "string"
        },
        "provider": {
          "description": "The data provider from which this piece of data was generated. Equivalent to SourceInfoProto.provider in the public schema.",
          "enum": [
            "PROVIDER_ANY",
            "PROVIDER_UNKNOWN",
            "PROVIDER_NAVTEQ",
            "PROVIDER_TELE_ATLAS",
            "PROVIDER_TELE_ATLAS_MULTINET",
            "PROVIDER_TELE_ATLAS_CODEPOINT",
            "PROVIDER_TELE_ATLAS_GEOPOST",
            "PROVIDER_TELE_ATLAS_DATAGEO",
            "PROVIDER_TELE_ATLAS_ADDRESS_POINTS",
            "PROVIDER_TELCONTAR",
[...]
