{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/datamanager": {
          "description": "See, edit, create, import, or delete your customer data in Google Ads, Google Marketing Platform (Campaign Manager 360, Search Ads 360, Display & Video 360), and Google Analytics"
        },
        "https://www.googleapis.com/auth/datamanager.partnerlink": {
          "description": "View, create, or delete your partner links in Google Ads, Marketing Platform (Campaign Manager 360, Search Ads 360, Display & Video 360), and Analytics"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://datamanager.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Data Manager",
  "description": "A unified ingestion API for data partners, agencies and advertisers to connect first-party data across Google advertising products.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/data-manager",
  "fullyEncodeReservedExpansion": true,
  "id": "datamanager:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://datamanager.mtls.googleapis.com/",
  "name": "datamanager",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "accountTypes": {
      "resources": {
        "accounts": {
          "resources": {
            "insights": {
              "methods": {
                "retrieve": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/insights:retrieve",
                  "httpMethod": "POST",
                  "id": "datamanager.accountTypes.accounts.insights.retrieve",
                  "path": "v1/{+parent}/insights:retrieve",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                }
              }
            },
            "partnerLinks": {
              "methods": {
                "create": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/partnerLinks",
                  "httpMethod": "POST",
                  "id": "datamanager.accountTypes.accounts.partnerLinks.create",
                  "path": "v1/{+parent}/partnerLinks",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager",
                    "https://www.googleapis.com/auth/datamanager.partnerlink"
                  ]
                },
                "delete": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/partnerLinks/{partnerLinksId}",
                  "httpMethod": "DELETE",
                  "id": "datamanager.accountTypes.accounts.partnerLinks.delete",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager",
                    "https://www.googleapis.com/auth/datamanager.partnerlink"
                  ]
                },
                "search": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/partnerLinks:search",
                  "httpMethod": "GET",
                  "id": "datamanager.accountTypes.accounts.partnerLinks.search",
                  "path": "v1/{+parent}/partnerLinks:search",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager",
                    "https://www.googleapis.com/auth/datamanager.partnerlink"
                  ]
                }
              }
            },
            "userListDirectLicenses": {
              "methods": {
                "create": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListDirectLicenses",
                  "httpMethod": "POST",
                  "id": "datamanager.accountTypes.accounts.userListDirectLicenses.create",
                  "path": "v1/{+parent}/userListDirectLicenses",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "get": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListDirectLicenses/{userListDirectLicensesId}",
                  "httpMethod": "GET",
                  "id": "datamanager.accountTypes.accounts.userListDirectLicenses.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "list": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListDirectLicenses",
                  "httpMethod": "GET",
                  "id": "datamanager.accountTypes.accounts.userListDirectLicenses.list",
                  "path": "v1/{+parent}/userListDirectLicenses",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "patch": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListDirectLicenses/{userListDirectLicensesId}",
                  "httpMethod": "PATCH",
                  "id": "datamanager.accountTypes.accounts.userListDirectLicenses.patch",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                }
              }
            },
            "userListGlobalLicenses": {
              "methods": {
                "create": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses",
                  "httpMethod": "POST",
                  "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.create",
                  "path": "v1/{+parent}/userListGlobalLicenses",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "get": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses/{userListGlobalLicensesId}",
                  "httpMethod": "GET",
                  "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "list": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses",
                  "httpMethod": "GET",
                  "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.list",
                  "path": "v1/{+parent}/userListGlobalLicenses",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "patch": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses/{userListGlobalLicensesId}",
                  "httpMethod": "PATCH",
                  "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.patch",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                }
              },
              "resources": {
                "userListGlobalLicenseCustomerInfos": {
                  "methods": {
                    "list": {
                      "description": "",
                      "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses/{userListGlobalLicensesId}/userListGlobalLicenseCustomerInfos",
                      "httpMethod": "GET",
                      "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.userListGlobalLicenseCustomerInfos.list",
                      "path": "v1/{+parent}/userListGlobalLicenseCustomerInfos",
                      "scopes": [
                        "https://www.googleapis.com/auth/datamanager"
                      ]
                    }
                  }
                }
              }
            },
            "userLists": {
              "methods": {
                "create": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists",
                  "httpMethod": "POST",
                  "id": "datamanager.accountTypes.accounts.userLists.create",
                  "path": "v1/{+parent}/userLists",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "delete": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists/{userListsId}",
                  "httpMethod": "DELETE",
                  "id": "datamanager.accountTypes.accounts.userLists.delete",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "get": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists/{userListsId}",
                  "httpMethod": "GET",
                  "id": "datamanager.accountTypes.accounts.userLists.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "list": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists",
                  "httpMethod": "GET",
                  "id": "datamanager.accountTypes.accounts.userLists.list",
                  "path": "v1/{+parent}/userLists",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                },
                "patch": {
                  "description": "",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists/{userListsId}",
                  "httpMethod": "PATCH",
                  "id": "datamanager.accountTypes.accounts.userLists.patch",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "adEvents": {
      "methods": {
        "ingest": {
          "description": "",
          "flatPath": "v1/adEvents:ingest",
          "httpMethod": "POST",
          "id": "datamanager.adEvents.ingest",
          "path": "v1/adEvents:ingest",
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ]
        }
      }
    },
    "audienceMembers": {
      "methods": {
        "ingest": {
          "description": "",
          "flatPath": "v1/audienceMembers:ingest",
          "httpMethod": "POST",
          "id": "datamanager.audienceMembers.ingest",
          "path": "v1/audienceMembers:ingest",
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ]
        },
        "remove": {
          "description": "",
          "flatPath": "v1/audienceMembers:remove",
          "httpMethod": "POST",
          "id": "datamanager.audienceMembers.remove",
          "path": "v1/audienceMembers:remove",
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ]
        },
        "removeAll": {
          "description": "",
          "flatPath": "v1/audienceMembers:removeAll",
          "httpMethod": "POST",
          "id": "datamanager.audienceMembers.removeAll",
          "path": "v1/audienceMembers:removeAll",
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ]
        }
      }
    },
    "events": {
      "methods": {
        "ingest": {
          "description": "",
          "flatPath": "v1/events:ingest",
          "httpMethod": "POST",
          "id": "datamanager.events.ingest",
          "path": "v1/events:ingest",
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ]
        }
      }
    },
    "requestStatus": {
      "methods": {
        "retrieve": {
          "description": "",
          "flatPath": "v1/requestStatus:retrieve",
          "httpMethod": "GET",
          "id": "datamanager.requestStatus.retrieve",
          "path": "v1/requestStatus:retrieve",
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ]
        }
      }
    }
  },
  "revision": "20260904",
  "rootUrl": "https://datamanager.googleapis.com/",
  "servicePath": "",
  "title": "Data Manager API",
  "version": "v1",
  "version_module": true
}