{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Display Video",
  "description": "Display & Video 360 API allows users to manage and create campaigns and reports.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/display-video/",
  "fullyEncodeReservedExpansion": true,
  "id": "displayvideo:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "name": "displayvideo",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "advertisers": {
      "methods": {
        "bulkEditAdvertiserAssignedTargetingOptions": {
          "description": "Bulk edits targeting options under a single advertiser.\nThe operation will delete the assigned targeting options provided in\nBulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and\nthen create the assigned targeting options provided in\nBulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "flatPath": "v1/advertisers/{advertisersId}:bulkEditAdvertiserAssignedTargetingOptions",
          "httpMethod": "POST",
          "id": "displayvideo.advertisers.bulkEditAdvertiserAssignedTargetingOptions",
          "path": "v1/advertisers/{+advertiserId}:bulkEditAdvertiserAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "bulkListAdvertiserAssignedTargetingOptions": {
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "flatPath": "v1/advertisers/{advertisersId}:bulkListAdvertiserAssignedTargetingOptions",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.bulkListAdvertiserAssignedTargetingOptions",
          "path": "v1/advertisers/{+advertiserId}:bulkListAdvertiserAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "description": "Creates a new advertiser.\nReturns the newly created advertiser if successful.\nThis method can take up to 180 seconds to complete.",
          "flatPath": "v1/advertisers",
          "httpMethod": "POST",
          "id": "displayvideo.advertisers.create",
          "path": "v1/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "description": "Deletes an advertiser.\nDeleting an advertiser will delete all of its child resources, for example,\ncampaigns, insertion orders and line items.\nA deleted advertiser cannot be recovered.",
          "flatPath": "v1/advertisers/{advertisersId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.advertisers.delete",
          "path": "v1/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "description": "Gets an advertiser.",
          "flatPath": "v1/advertisers/{advertisersId}",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.get",
          "path": "v1/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "description": "Lists advertisers that are accessible to the current user.\n\nThe order is defined by the order_by\nparameter.\n\nA single partner_id is required.\nCross-partner listing is not supported.",
          "flatPath": "v1/advertisers",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.list",
          "path": "v1/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "description": "Updates an existing advertiser.\nReturns the updated advertiser if successful.",
          "flatPath": "v1/advertisers/{advertisersId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.advertisers.patch",
          "path": "v1/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "assets": {
          "methods": {
            "upload": {
              "description": "Uploads an asset.\nReturns the ID of the newly uploaded asset if successful.\nThe asset file size should be no more than 10 MB for images, 200 MB for\nZIP files, and 1 GB for videos.",
              "flatPath": "v1/advertisers/{advertisersId}/assets",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.assets.upload",
              "path": "v1/advertisers/{+advertiserId}/assets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaUpload": true
            }
          }
        },
        "campaigns": {
          "methods": {
            "create": {
              "description": "Creates a new campaign.\nReturns the newly created campaign if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.campaigns.create",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered.\nThe campaign should be archived first, i.e. set\nentity_status to `ENTITY_STATUS_ARCHIVED`, to be\nable to delete it.",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.campaigns.delete",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets a campaign.",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.get",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists campaigns in an advertiser.\n\nThe order is defined by the order_by\nparameter.\nIf a filter by\nentity_status is not specified, campaigns with\n`ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.list",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates an existing campaign.\nReturns the updated campaign if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.campaigns.patch",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "channels": {
          "methods": {
            "get": {
              "description": "Updates an existing inventory source.\nReturns the updated inventory source if successful.\nGets a channel for a partner or advertiser.",
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.channels.get",
              "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "flatPath": "v1/advertisers/{advertisersId}/channels",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.channels.list",
              "path": "v1/advertisers/{+advertiserId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.channels.patch",
              "path": "v1/advertisers/{+advertiserId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "description": "Bulk edits sites under a single channel.\n\nThe operation will delete the sites provided in\nBulkEditSitesRequest.deleted_sites and then create the sites\nprovided in BulkEditSitesRequest.created_sites.",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "description": "Creates a site in a channel.",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "description": "Lists sites in a channel.",
                  "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "creatives": {
          "methods": {
            "create": {
              "description": "Creates a new creative.\nReturns the newly created creative if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.creatives.create",
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "description": "Deletes a creative.\nReturns error code `NOT_FOUND` if the creative does not exist.\nThe creative should be archived first, i.e. set\nentity_status to `ENTITY_STATUS_ARCHIVED`, before\nit can be deleted.",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.creatives.delete",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets a creative.",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.creatives.get",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists creatives in an advertiser.\n\nThe order is defined by the order_by\nparameter.\nIf a filter by\nentity_status is not specified, creatives with\n`ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.creatives.list",
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates an existing creative.\nReturns the updated creative if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.creatives.patch",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "create": {
              "description": "Creates a new insertion order.\nReturns the newly created insertion order if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.insertionOrders.create",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "description": "Deletes an insertion order.\nReturns error code `NOT_FOUND` if the insertion order does not exist.\nThe insertion order should be archived first, i.e. set\nentity_status to `ENTITY_STATUS_ARCHIVED`,\nto be able to delete it.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets an insertion order.\nReturns error code `NOT_FOUND` if the insertion order does not exist.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists insertion orders in an advertiser.\n\nThe order is defined by the order_by\nparameter.\nIf a filter by\nentity_status is not specified, insertion\norders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates an existing insertion order.\nReturns the updated insertion order if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "lineItems": {
          "methods": {
            "bulkEditLineItemAssignedTargetingOptions": {
              "description": "Bulk edits targeting options under a single line item.\nThe operation will delete the assigned targeting options provided in\nBulkEditLineItemAssignedTargetingOptionsRequest.delete_requests and\nthen create the assigned targeting options provided in\nBulkEditLineItemAssignedTargetingOptionsRequest.create_requests .",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkEditLineItemAssignedTargetingOptions",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.bulkEditLineItemAssignedTargetingOptions",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkEditLineItemAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkListLineItemAssignedTargetingOptions": {
              "description": "Lists assigned targeting options of a line item across targeting types.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkListLineItemAssignedTargetingOptions",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.bulkListLineItemAssignedTargetingOptions",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkListLineItemAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "description": "Creates a new line item.\nReturns the newly created line item if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.create",
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "description": "Deletes a line item.\nReturns error code `NOT_FOUND` if the line item does not exist.\nThe line item should be archived first, i.e. set\nentity_status to `ENTITY_STATUS_ARCHIVED`, to be\nable to delete it.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.lineItems.delete",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets a line item.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.get",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists line items in an advertiser.\n\nThe order is defined by the order_by\nparameter.\nIf a filter by\nentity_status is not specified, line items with\n`ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.list",
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates an existing line item.\nReturns the updated line item if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.lineItems.patch",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "description": "Assigns a targeting option to a line item.\nReturns the assigned targeting option if successful.",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "delete": {
                      "description": "Deletes an assigned targeting option from a line item.",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "get": {
                      "description": "Gets a single targeting option assigned to a line item.",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "description": "Lists the targeting options assigned to a line item.",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "locationLists": {
          "methods": {
            "create": {
              "description": "Creates a new location list. Returns the newly created location list if\nsuccessful.",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.locationLists.create",
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets a location list.",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.get",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists location lists based on a given advertiser id.",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.list",
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates a location list. Returns the updated location list if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.locationLists.patch",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "bulkEdit": {
                  "description": "Bulk edits multiple assignments between locations and a single location\nlist.\n\nThe operation will delete the assigned locations provided in\nBulkEditAssignedLocationsRequest.deleted_assigned_locations and then\ncreate the assigned locations provided in\nBulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "description": "Creates an assignment between a location and a location list.",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "description": "Deletes the assignment between a location and a location list.",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "description": "Lists locations assigned to a location list.",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "create": {
              "description": "Creates a new negative keyword list. Returns the newly created negative\nkeyword list if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "description": "Deletes a negative keyword list given an advertiser ID and a negative\nkeyword list ID.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword\nlist ID.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates a negative keyword list. Returns the updated negative keyword list\nif successful.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "bulkEdit": {
                  "description": "Bulk edits negative keywords in a single negative keyword list.\n\nThe operation will delete the negative keywords provided in\nBulkEditNegativeKeywordsRequest.deleted_negative_keywords and then\ncreate the negative keywords provided in\nBulkEditNegativeKeywordsRequest.created_negative_keywords.\n\nThis operation is guaranteed to be atomic and will never result in a\npartial success or partial failure.",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "description": "Lists negative keywords in a negative keyword list.",
                  "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "description": "Assigns a targeting option to an advertiser.\nReturns the assigned targeting option if successful.",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "get": {
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "description": "Gets a combined audience.",
          "flatPath": "v1/combinedAudiences/{combinedAudiencesId}",
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.get",
          "path": "v1/combinedAudiences/{+combinedAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "description": "Lists combined audiences.\n\nThe order is defined by the\norder_by parameter.",
          "flatPath": "v1/combinedAudiences",
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.list",
          "path": "v1/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "description": "Gets a custom list.",
          "flatPath": "v1/customLists/{customListsId}",
          "httpMethod": "GET",
          "id": "displayvideo.customLists.get",
          "path": "v1/customLists/{+customListId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "description": "Lists custom lists.\n\nThe order is defined by the order_by\nparameter.",
          "flatPath": "v1/customLists",
          "httpMethod": "GET",
          "id": "displayvideo.customLists.list",
          "path": "v1/customLists",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "get": {
          "description": "Gets a first and third party audience.",
          "flatPath": "v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "httpMethod": "GET",
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "description": "Lists first and third party audiences.\n\nThe order is defined by the\norder_by parameter.",
          "flatPath": "v1/firstAndThirdPartyAudiences",
          "httpMethod": "GET",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "path": "v1/firstAndThirdPartyAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "description": "Gets a Floodlight group.",
          "flatPath": "v1/floodlightGroups/{floodlightGroupsId}",
          "httpMethod": "GET",
          "id": "displayvideo.floodlightGroups.get",
          "path": "v1/floodlightGroups/{+floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "description": "Updates an existing Floodlight group.\nReturns the updated Floodlight group if successful.",
          "flatPath": "v1/floodlightGroups/{floodlightGroupId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.floodlightGroups.patch",
          "path": "v1/floodlightGroups/{floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "description": "Gets a Google audience.",
          "flatPath": "v1/googleAudiences/{googleAudiencesId}",
          "httpMethod": "GET",
          "id": "displayvideo.googleAudiences.get",
          "path": "v1/googleAudiences/{+googleAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "description": "Lists Google audiences.\n\nThe order is defined by the order_by\nparameter.",
          "flatPath": "v1/googleAudiences",
          "httpMethod": "GET",
          "id": "displayvideo.googleAudiences.list",
          "path": "v1/googleAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "create": {
          "description": "Creates a new inventory source group. Returns the newly created inventory\nsource group if successful.",
          "flatPath": "v1/inventorySourceGroups",
          "httpMethod": "POST",
          "id": "displayvideo.inventorySourceGroups.create",
          "path": "v1/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "description": "Deletes an inventory source group.",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.inventorySourceGroups.delete",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "description": "Gets an inventory source group.",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySourceGroups.get",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "description": "Lists inventory source groups that are accessible to the current user.\n\nThe order is defined by the\norder_by parameter.",
          "flatPath": "v1/inventorySourceGroups",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySourceGroups.list",
          "path": "v1/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "description": "Updates an inventory source group. Returns the updated inventory source\ngroup if successful.",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.inventorySourceGroups.patch",
          "path": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "bulkEdit": {
              "description": "Bulk edits multiple assignments between inventory sources and a single\ninventory source group.\n\nThe operation will delete the assigned inventory sources provided in\nBulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources\nand then create the assigned inventory sources provided in\nBulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "description": "Creates an assignment between an inventory source and an inventory source\ngroup.",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "POST",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "description": "Deletes the assignment between an inventory source and an inventory source\ngroup.",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists inventory sources assigned to an inventory source group.",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "GET",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "get": {
          "description": "Gets an inventory source.",
          "flatPath": "v1/inventorySources/{inventorySourcesId}",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.get",
          "path": "v1/inventorySources/{+inventorySourceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "description": "Lists inventory sources that are accessible to the current user.\n\nThe order is defined by the\norder_by parameter.\nIf a filter by\nentity_status is not\nspecified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED`\nwill not be included in the results.",
          "flatPath": "v1/inventorySources",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.list",
          "path": "v1/inventorySources",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.`\n\n**Note**: Download requests will not be successful without including `alt=media` query string.",
          "flatPath": "download/{downloadId}",
          "httpMethod": "GET",
          "id": "displayvideo.media.download",
          "path": "download/{+resourceName}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "supportsMediaDownload": true
        }
      }
    },
    "partners": {
      "resources": {
        "channels": {
          "methods": {
            "get": {
              "description": "Updates an existing inventory source.\nReturns the updated inventory source if successful.\nGets a channel for a partner or advertiser.",
              "flatPath": "v1/partners/{partnersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "id": "displayvideo.partners.channels.get",
              "path": "v1/partners/{+partnerId}/channels/{+channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "flatPath": "v1/partners/{partnersId}/channels",
              "httpMethod": "GET",
              "id": "displayvideo.partners.channels.list",
              "path": "v1/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v1/partners/{partnersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.partners.channels.patch",
              "path": "v1/partners/{+partnerId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "description": "Bulk edits sites under a single channel.\n\nThe operation will delete the sites provided in\nBulkEditSitesRequest.deleted_sites and then create the sites\nprovided in BulkEditSitesRequest.created_sites.",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "description": "Creates a site in a channel.",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.channels.sites.create",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "description": "Lists sites in a channel.",
                  "flatPath": "v1/partners/{partnersId}/channels/{channelsId}/sites",
                  "httpMethod": "GET",
                  "id": "displayvideo.partners.channels.sites.list",
                  "path": "v1/partners/{+partnerId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "description": "Creates an SDF Download Task. Returns an\nOperation.\n\nAn SDF Download Task is a long-running, asynchronous operation. The\nmetadata type of this operation is\nSdfDownloadTaskMetadata. If the request is successful, the\nresponse type of the operation is\nSdfDownloadTask. The response will not include the download files,\nwhich must be retrieved with\nmedia.download. The state of\noperation can be retrieved with\nsdfdownloadtask.operations.get.\n\nAny errors can be foun[...]",
          "flatPath": "v1/sdfdownloadtasks",
          "httpMethod": "POST",
          "id": "displayvideo.sdfdownloadtasks.create",
          "path": "v1/sdfdownloadtasks",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v1/sdfdownloadtasks/operations/{operationsId}",
              "httpMethod": "GET",
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ]
            }
          }
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "description": "Gets a single targeting option.",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "httpMethod": "GET",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists targeting options of a given type.",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions",
              "httpMethod": "GET",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    }
  },
  "revision": "20200611",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "servicePath": "",
  "title": "Display & Video 360 API",
  "version": "v1",
  "version_module": true
}