{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/fitness.activity.read": {
          "description": "Use Google Fit to see and store your physical activity data"
        },
        "https://www.googleapis.com/auth/fitness.activity.write": {
          "description": "See and add to your Google Fit physical activity data"
        },
        "https://www.googleapis.com/auth/fitness.blood_glucose.read": {
          "description": "See info about your blood glucose in Google Fit. I consent to Google sharing my blood glucose information with this app."
        },
        "https://www.googleapis.com/auth/fitness.blood_glucose.write": {
          "description": "See and add info about your blood glucose to Google Fit. I consent to Google sharing my blood glucose information with this app."
        },
        "https://www.googleapis.com/auth/fitness.blood_pressure.read": {
          "description": "See info about your blood pressure in Google Fit. I consent to Google sharing my blood pressure information with this app."
        },
        "https://www.googleapis.com/auth/fitness.blood_pressure.write": {
          "description": "See and add info about your blood pressure in Google Fit. I consent to Google sharing my blood pressure information with this app."
        },
        "https://www.googleapis.com/auth/fitness.body.read": {
          "description": "See info about your body measurements and heart rate in Google Fit"
        },
        "https://www.googleapis.com/auth/fitness.body.write": {
          "description": "See and add info about your body measurements and heart rate to Google Fit"
        },
        "https://www.googleapis.com/auth/fitness.body_temperature.read": {
          "description": "See info about your body temperature in Google Fit. I consent to Google sharing my body temperature information with this app."
        },
        "https://www.googleapis.com/auth/fitness.body_temperature.write": {
          "description": "See and add to info about your body temperature in Google Fit. I consent to Google sharing my body temperature information with this app."
        },
        "https://www.googleapis.com/auth/fitness.location.read": {
          "description": "See your Google Fit speed and distance data"
        },
        "https://www.googleapis.com/auth/fitness.location.write": {
          "description": "See and add to your Google Fit location data"
        },
        "https://www.googleapis.com/auth/fitness.nutrition.read": {
          "description": "See info about your nutrition in Google Fit"
        },
        "https://www.googleapis.com/auth/fitness.nutrition.write": {
          "description": "See and add to info about your nutrition in Google Fit"
        },
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.read": {
          "description": "See info about your oxygen saturation in Google Fit. I consent to Google sharing my oxygen saturation information with this app."
        },
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write": {
          "description": "See and add info about your oxygen saturation in Google Fit. I consent to Google sharing my oxygen saturation information with this app."
        },
        "https://www.googleapis.com/auth/fitness.reproductive_health.read": {
          "description": "See info about your reproductive health in Google Fit. I consent to Google sharing my reporductive health information with this app."
        },
        "https://www.googleapis.com/auth/fitness.reproductive_health.write": {
          "description": "See and add info about your reproductive health in Google Fit. I consent to Google sharing my reporductive health information with this app."
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://www.googleapis.com/",
  "batchPath": "batch/fitness/v1",
  "description": "The Fitness API for managing users' fitness tracking data.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/fit/rest/v1/get-started",
  "id": "fitness:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "name": "fitness",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "users": {
      "resources": {
        "dataSources": {
          "methods": {
            "create": {
              "description": "Creates a new data source that is unique across all data sources belonging\nto this user.\n\nA data source is a unique source of sensor data. Data sources can expose\nraw data coming from hardware sensors on local or companion devices. They\ncan also expose derived data, created by transforming or merging other data\nsources. Multiple data sources can exist for the same data type. Every data\npoint in every dataset inserted into or read from the Fitness API has an\n[...]",
              "flatPath": "fitness/v1/users/{userId}/dataSources",
              "httpMethod": "POST",
              "id": "fitness.users.dataSources.create",
              "path": "fitness/v1/users/{userId}/dataSources",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
              ]
            },
            "delete": {
              "description": "Deletes the specified data source. The request will fail if the data\nsource contains any data points.",
              "flatPath": "fitness/v1/users/{userId}/dataSources/{dataSourceId}",
              "httpMethod": "DELETE",
              "id": "fitness.users.dataSources.delete",
              "path": "fitness/v1/users/{userId}/dataSources/{dataSourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
              ]
            },
            "get": {
              "description": "Returns the specified data source.",
              "flatPath": "fitness/v1/users/{userId}/dataSources/{dataSourceId}",
              "httpMethod": "GET",
              "id": "fitness.users.dataSources.get",
              "path": "fitness/v1/users/{userId}/dataSources/{dataSourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.read",
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.read",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.location.read",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.read",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
              ]
            },
            "list": {
              "description": "Lists all data sources that are visible to the developer, using the OAuth\nscopes provided. The list is not exhaustive; the user may have private\ndata sources that are only visible to other developers, or calls using\nother scopes.",
              "flatPath": "fitness/v1/users/{userId}/dataSources",
              "httpMethod": "GET",
              "id": "fitness.users.dataSources.list",
              "path": "fitness/v1/users/{userId}/dataSources",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.read",
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.read",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.location.read",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.read",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
              ]
            },
            "update": {
              "description": "Updates the specified data source. The <code>dataStreamId</code>,\n<code>dataType</code>, <code>type</code>, <code>dataStreamName</code>, and\n<code>device</code> properties with the exception of <code>version</code>,\ncannot be modified.\n\nData sources are identified by their <code>dataStreamId</code>.",
              "flatPath": "fitness/v1/users/{userId}/dataSources/{dataSourceId}",
              "httpMethod": "PUT",
              "id": "fitness.users.dataSources.update",
              "path": "fitness/v1/users/{userId}/dataSources/{dataSourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
              ]
            }
          },
          "resources": {
            "dataPointChanges": {
              "methods": {
                "list": {
                  "description": "Queries for user's data point changes for a particular data source.",
                  "flatPath": "fitness/v1/users/{userId}/dataSources/{dataSourceId}/dataPointChanges",
                  "httpMethod": "GET",
                  "id": "fitness.users.dataSources.dataPointChanges.list",
                  "path": "fitness/v1/users/{userId}/dataSources/{dataSourceId}/dataPointChanges",
                  "scopes": [
                    "https://www.googleapis.com/auth/fitness.activity.read",
                    "https://www.googleapis.com/auth/fitness.activity.write",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                    "https://www.googleapis.com/auth/fitness.body.read",
                    "https://www.googleapis.com/auth/fitness.body.write",
                    "https://www.googleapis.com/auth/fitness.body_temperature.read",
                    "https://www.googleapis.com/auth/fitness.body_temperature.write",
                    "https://www.googleapis.com/auth/fitness.location.read",
                    "https://www.googleapis.com/auth/fitness.location.write",
                    "https://www.googleapis.com/auth/fitness.nutrition.read",
                    "https://www.googleapis.com/auth/fitness.nutrition.write",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                  ]
                }
              }
            },
            "datasets": {
              "methods": {
                "delete": {
                  "description": "Performs an inclusive delete of all data points whose start and end times\nhave any overlap with the time range specified by the dataset ID. For most\ndata types, the entire data point will be deleted. For data types where the\ntime span represents a consistent value (such as\n<code>com.google.activity.segment</code>), and a data point straddles\neither end point of the dataset, only the overlapping portion of the data\npoint will be deleted.",
                  "flatPath": "fitness/v1/users/{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "httpMethod": "DELETE",
                  "id": "fitness.users.dataSources.datasets.delete",
                  "path": "fitness/v1/users/{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/fitness.activity.write",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                    "https://www.googleapis.com/auth/fitness.body.write",
                    "https://www.googleapis.com/auth/fitness.body_temperature.write",
                    "https://www.googleapis.com/auth/fitness.location.write",
                    "https://www.googleapis.com/auth/fitness.nutrition.write",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                  ]
                },
                "get": {
                  "description": "Returns a dataset containing all data points whose start and end times\noverlap with the specified range of the dataset minimum start time and\nmaximum end time. Specifically, any data point whose start time is less\nthan or equal to the dataset end time and whose end time is greater than or\nequal to the dataset start time.",
                  "flatPath": "fitness/v1/users/{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "httpMethod": "GET",
                  "id": "fitness.users.dataSources.datasets.get",
                  "path": "fitness/v1/users/{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/fitness.activity.read",
                    "https://www.googleapis.com/auth/fitness.activity.write",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                    "https://www.googleapis.com/auth/fitness.body.read",
                    "https://www.googleapis.com/auth/fitness.body.write",
                    "https://www.googleapis.com/auth/fitness.body_temperature.read",
                    "https://www.googleapis.com/auth/fitness.body_temperature.write",
                    "https://www.googleapis.com/auth/fitness.location.read",
                    "https://www.googleapis.com/auth/fitness.location.write",
                    "https://www.googleapis.com/auth/fitness.nutrition.read",
                    "https://www.googleapis.com/auth/fitness.nutrition.write",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                  ]
                },
                "patch": {
                  "description": "Adds data points to a dataset. The dataset need not be previously created.\nAll points within the given dataset will be returned with subsquent calls\nto retrieve this dataset. Data points can belong to more than one dataset.\nThis method does not use patch semantics.",
                  "flatPath": "fitness/v1/users/{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "httpMethod": "PATCH",
                  "id": "fitness.users.dataSources.datasets.patch",
                  "path": "fitness/v1/users/{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/fitness.activity.write",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                    "https://www.googleapis.com/auth/fitness.body.write",
                    "https://www.googleapis.com/auth/fitness.body_temperature.write",
                    "https://www.googleapis.com/auth/fitness.location.write",
                    "https://www.googleapis.com/auth/fitness.nutrition.write",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                  ]
                }
              }
            }
          }
        },
        "dataset": {
          "methods": {
            "aggregate": {
              "description": "Aggregates data of a certain type or stream into buckets divided by a given\ntype of boundary. Multiple data sets of multiple types and from multiple\nsources can be aggregated into exactly one bucket type per request.",
              "flatPath": "fitness/v1/users/{userId}/dataset:aggregate",
              "httpMethod": "POST",
              "id": "fitness.users.dataset.aggregate",
              "path": "fitness/v1/users/{userId}/dataset:aggregate",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.read",
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.read",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.location.read",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.read",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
              ]
            }
          }
        },
        "sessions": {
          "methods": {
            "delete": {
              "description": "Deletes a session specified by the given session ID.",
              "flatPath": "fitness/v1/users/{userId}/sessions/{sessionId}",
              "httpMethod": "DELETE",
              "id": "fitness.users.sessions.delete",
              "path": "fitness/v1/users/{userId}/sessions/{sessionId}",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write"
              ]
            },
            "list": {
              "description": "Lists sessions previously created.",
              "flatPath": "fitness/v1/users/{userId}/sessions",
              "httpMethod": "GET",
              "id": "fitness.users.sessions.list",
              "path": "fitness/v1/users/{userId}/sessions",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.read",
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.read",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.location.read",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.read",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
              ]
            },
            "update": {
              "description": "Updates or insert a given session.",
              "flatPath": "fitness/v1/users/{userId}/sessions/{sessionId}",
              "httpMethod": "PUT",
              "id": "fitness.users.sessions.update",
              "path": "fitness/v1/users/{userId}/sessions/{sessionId}",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write"
              ]
            }
          }
        }
      }
    }
  },
  "revision": "20200601",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "",
  "title": "Fitness API",
  "version": "v1"
}