{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Insert mail into your mailbox"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "Manage mailbox labels"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "View and modify but not delete your email"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "Manage your basic mail settings"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://www.googleapis.com/",
  "batchPath": "batch/gmail/v1",
  "canonicalName": "Gmail",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like\n    threads, messages, and labels.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/gmail/api/",
  "id": "gmail:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "name": "gmail",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "users": {
      "methods": {
        "getProfile": {
          "description": "Gets the current user's Gmail profile.",
          "flatPath": "gmail/v1/users/{userId}/profile",
          "httpMethod": "GET",
          "id": "gmail.users.getProfile",
          "path": "gmail/v1/users/{userId}/profile",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        },
        "stop": {
          "description": "Stop receiving push notifications for the given user mailbox.",
          "flatPath": "gmail/v1/users/{userId}/stop",
          "httpMethod": "POST",
          "id": "gmail.users.stop",
          "path": "gmail/v1/users/{userId}/stop",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        },
        "watch": {
          "description": "Set up or update a push notification watch on the given user mailbox.",
          "flatPath": "gmail/v1/users/{userId}/watch",
          "httpMethod": "POST",
          "id": "gmail.users.watch",
          "path": "gmail/v1/users/{userId}/watch",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        }
      },
      "resources": {
        "drafts": {
          "methods": {
            "create": {
              "description": "Creates a new draft with the <code>DRAFT</code> label.",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "POST",
              "id": "gmail.users.drafts.create",
              "path": "gmail/v1/users/{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            },
            "delete": {
              "description": "Immediately and permanently deletes the specified draft.\nDoes not simply trash it.",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "DELETE",
              "id": "gmail.users.drafts.delete",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "get": {
              "description": "Gets the specified draft.",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.drafts.get",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "list": {
              "description": "Lists the drafts in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "GET",
              "id": "gmail.users.drafts.list",
              "path": "gmail/v1/users/{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "send": {
              "description": "Sends the specified, existing draft to the recipients in the\n<code>To</code>, <code>Cc</code>, and <code>Bcc</code> headers.",
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "httpMethod": "POST",
              "id": "gmail.users.drafts.send",
              "path": "gmail/v1/users/{userId}/drafts/send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            },
            "update": {
              "description": "Replaces a draft's content.",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "PUT",
              "id": "gmail.users.drafts.update",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "description": "Lists the history of all changes to the given mailbox. History results are\nreturned in chronological order (increasing <code>historyId</code>).",
              "flatPath": "gmail/v1/users/{userId}/history",
              "httpMethod": "GET",
              "id": "gmail.users.history.list",
              "path": "gmail/v1/users/{userId}/history",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            }
          }
        },
        "labels": {
          "methods": {
            "create": {
              "description": "Creates a new label.",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "httpMethod": "POST",
              "id": "gmail.users.labels.create",
              "path": "gmail/v1/users/{userId}/labels",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "description": "Immediately and permanently deletes the specified label and removes it from\nany messages and threads that it is applied to.",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "DELETE",
              "id": "gmail.users.labels.delete",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "get": {
              "description": "Gets the specified label.",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.labels.get",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "list": {
              "description": "Lists all labels in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "httpMethod": "GET",
              "id": "gmail.users.labels.list",
              "path": "gmail/v1/users/{userId}/labels",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "patch": {
              "description": "Patch the specified label.",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "PATCH",
              "id": "gmail.users.labels.patch",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "update": {
              "description": "Updates the specified label.",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "PUT",
              "id": "gmail.users.labels.update",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            }
          }
        },
        "messages": {
          "methods": {
            "batchDelete": {
              "description": "Deletes many messages by message ID.  Provides no guarantees that messages\nwere not already deleted or even existed at all.",
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
              "httpMethod": "POST",
              "id": "gmail.users.messages.batchDelete",
              "path": "gmail/v1/users/{userId}/messages/batchDelete",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "batchModify": {
              "description": "Modifies the labels on the specified messages.",
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
              "httpMethod": "POST",
              "id": "gmail.users.messages.batchModify",
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "description": "Immediately and permanently deletes the specified message. This operation\ncannot be undone.  Prefer <code>messages.trash</code> instead.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "DELETE",
              "id": "gmail.users.messages.delete",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "get": {
              "description": "Gets the specified message.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.messages.get",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "import": {
              "description": "Imports a message into only this user's mailbox, with standard\nemail delivery scanning and classification similar to receiving via SMTP.\nDoes not send a message.",
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "httpMethod": "POST",
              "id": "gmail.users.messages.import",
              "path": "gmail/v1/users/{userId}/messages/import",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            },
            "insert": {
              "description": "Directly inserts a message into only this user's mailbox similar to\n<code>IMAP APPEND</code>, bypassing most scanning and classification.\nDoes not send a message.",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "httpMethod": "POST",
              "id": "gmail.users.messages.insert",
              "path": "gmail/v1/users/{userId}/messages",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            },
            "list": {
              "description": "Lists the messages in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "httpMethod": "GET",
              "id": "gmail.users.messages.list",
              "path": "gmail/v1/users/{userId}/messages",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "modify": {
              "description": "Modifies the labels on the specified message.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "httpMethod": "POST",
              "id": "gmail.users.messages.modify",
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "send": {
              "description": "Sends the specified message to the recipients in the\n<code>To</code>, <code>Cc</code>, and <code>Bcc</code> headers.",
              "flatPath": "gmail/v1/users/{userId}/messages/send",
              "httpMethod": "POST",
              "id": "gmail.users.messages.send",
              "path": "gmail/v1/users/{userId}/messages/send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "supportsMediaUpload": true
            },
            "trash": {
              "description": "Moves the specified message to the trash.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "httpMethod": "POST",
              "id": "gmail.users.messages.trash",
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "untrash": {
              "description": "Removes the specified message from the trash.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "httpMethod": "POST",
              "id": "gmail.users.messages.untrash",
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "description": "Gets the specified message attachment.",
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "httpMethod": "GET",
                  "id": "gmail.users.messages.attachments.get",
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ]
                }
              }
            }
          }
        },
        "settings": {
          "methods": {
            "getAutoForwarding": {
              "description": "Gets the auto-forwarding setting for the specified account.",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getAutoForwarding",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getImap": {
              "description": "Gets IMAP settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getImap",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getLanguage": {
              "description": "Gets language settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getLanguage",
              "path": "gmail/v1/users/{userId}/settings/language",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getPop": {
              "description": "Gets POP settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getPop",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getVacation": {
              "description": "Gets vacation responder settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getVacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateAutoForwarding": {
              "description": "Updates the auto-forwarding setting for the specified account.  A verified\nforwarding address must be specified when auto-forwarding is enabled.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateAutoForwarding",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ]
            },
            "updateImap": {
              "description": "Updates IMAP settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateImap",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateLanguage": {
              "description": "Updates language settings.\n\nIf successful, the return object contains the <code>displayLanguage</code>\nthat was saved for the user, which may differ from the value passed into\nthe request. This is because the requested <code>displayLanguage</code> may\nnot be directly supported by Gmail but have a close variant that is, and so\nthe variant may be chosen and saved instead.",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateLanguage",
              "path": "gmail/v1/users/{userId}/settings/language",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updatePop": {
              "description": "Updates POP settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updatePop",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateVacation": {
              "description": "Updates vacation responder settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateVacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            }
          },
          "resources": {
            "delegates": {
              "methods": {
                "create": {
                  "description": "Adds a delegate with its verification status set directly to\n<code>accepted</code>, without sending any verification email.  The\ndelegate user must be a member of the same G Suite organization as the\ndelegator user.\n\nGmail imposes limitations on the number of delegates and delegators each\nuser in a G Suite organization can have. These limits depend on your\norganization, but in general each user can have up to 25 delegates and\nup to 10 delegators.\n\nNote[...]",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.delegates.create",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "description": "Removes the specified delegate (which can be of any verification status),\nand revokes any verification that may have been required for using it.\n\nNote that a delegate user must be referred to by their primary email\naddress, and not an email alias.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.delegates.delete",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "get": {
                  "description": "Gets the specified delegate.\n\nNote that a delegate user must be referred to by their primary email\naddress, and not an email alias.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.get",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "description": "Lists the delegates for the specified account.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.list",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "filters": {
              "methods": {
                "create": {
                  "description": "Creates a filter.",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.filters.create",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "delete": {
                  "description": "Deletes a filter.",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.filters.delete",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "get": {
                  "description": "Gets a filter.",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.filters.get",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "description": "Lists the message filters of a Gmail user.",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.filters.list",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "forwardingAddresses": {
              "methods": {
                "create": {
                  "description": "Creates a forwarding address.  If ownership verification is required, a\nmessage will be sent to the recipient and the resource's verification\nstatus will be set to <code>pending</code>; otherwise, the resource will be\ncreated with verification status set to <code>accepted</code>.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "description": "Deletes the specified forwarding address and revokes any verification that\nmay have been required.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "get": {
                  "description": "Gets the specified forwarding address.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "description": "Lists the forwarding addresses for the specified account.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.forwardingAddresses.list",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "sendAs": {
              "methods": {
                "create": {
                  "description": "Creates a custom \"from\" send-as alias.  If an SMTP MSA is specified, Gmail\nwill attempt to connect to the SMTP service to validate the configuration\nbefore creating the alias.  If ownership verification is required for the\nalias, a message will be sent to the email address and the resource's\nverification status will be set to <code>pending</code>; otherwise, the\nresource will be created with verification status set to\n<code>accepted</code>.  If a signatu[...]",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.sendAs.create",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "description": "Deletes the specified send-as alias.  Revokes any verification that may\nhave been required for using it.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.sendAs.delete",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "get": {
                  "description": "Gets the specified send-as alias.  Fails with an HTTP 404 error if the\nspecified address is not a member of the collection.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.sendAs.get",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "description": "Lists the send-as aliases for the specified account.  The result includes\nthe primary send-as address associated with the account as well as any\ncustom \"from\" aliases.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.sendAs.list",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "patch": {
                  "description": "Patch the specified send-as alias.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PATCH",
                  "id": "gmail.users.settings.sendAs.patch",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "update": {
                  "description": "Updates a send-as alias.  If a signature is provided, Gmail will sanitize\nthe HTML before saving it with the alias.\n\nAddresses other than the primary address for the account can only be\nupdated by service account clients that have been delegated domain-wide\nauthority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PUT",
                  "id": "gmail.users.settings.sendAs.update",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "verify": {
                  "description": "Sends a verification email to the specified send-as alias address.\nThe verification status must be <code>pending</code>.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.sendAs.verify",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                }
              },
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "delete": {
                      "description": "Deletes the specified S/MIME config for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "DELETE",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "get": {
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "insert": {
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias.\nNote that pkcs12 format is required for the key.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "list": {
                      "description": "Lists S/MIME configs for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "setDefault": {
                      "description": "Sets the default S/MIME config for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "threads": {
          "methods": {
            "delete": {
              "description": "Immediately and permanently deletes the specified thread. This operation\ncannot be undone. Prefer <code>threads.trash</code> instead.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "DELETE",
              "id": "gmail.users.threads.delete",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "get": {
              "description": "Gets the specified thread.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.threads.get",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "list": {
              "description": "Lists the threads in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/threads",
              "httpMethod": "GET",
              "id": "gmail.users.threads.list",
              "path": "gmail/v1/users/{userId}/threads",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "modify": {
              "description": "Modifies the labels applied to the thread. This applies to all messages\nin the thread.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "httpMethod": "POST",
              "id": "gmail.users.threads.modify",
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "trash": {
              "description": "Moves the specified thread to the trash.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "httpMethod": "POST",
              "id": "gmail.users.threads.trash",
              "path": "gmail/v1/users/{userId}/threads/{id}/trash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "untrash": {
              "description": "Removes the specified thread from the trash.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "httpMethod": "POST",
              "id": "gmail.users.threads.untrash",
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            }
          }
        }
      }
    }
  },
  "revision": "20200608",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "",
  "title": "Gmail API",
  "version": "v1"
}