{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly": {
          "description": "See your Google Health activity and fitness data"
        },
        "https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly": {
          "description": "See your Google Health health metrics and measurement data"
        },
        "https://www.googleapis.com/auth/googlehealth.irn.readonly": {
          "description": "See your Google Health Irregular Rhythm Notifications data"
        },
        "https://www.googleapis.com/auth/googlehealth.location.readonly": {
          "description": "See exercise GPS location data in Google Health"
        },
        "https://www.googleapis.com/auth/googlehealth.profile.readonly": {
          "description": "See your Google Health profile data"
        },
        "https://www.googleapis.com/auth/googlehealth.settings.readonly": {
          "description": "See your Google Health settings"
        },
        "https://www.googleapis.com/auth/googlehealth.sleep.readonly": {
          "description": "See your Google Health sleep data"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://health.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Google Health API",
  "description": "The Google Health API lets you view and manage health and fitness metrics and measurement data.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/health",
  "fullyEncodeReservedExpansion": true,
  "id": "health:v4",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://health.mtls.googleapis.com/",
  "name": "health",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "projects": {
      "resources": {
        "subscribers": {
          "methods": {
            "create": {
              "description": "Registers a new subscriber endpoint to receive notifications. A subscriber represents an application or service that wishes to receive data change notifications for users who have granted consent. **Endpoint Verification:** For a subscriber to be successfully created, the provided `endpoint_uri` must be a valid HTTPS endpoint and must pass an automated verification check. The backend will send two HTTP POST requests to the `endpoint_uri`: 1. **Verification with Auth[...]",
              "flatPath": "v4/projects/{projectsId}/subscribers",
              "httpMethod": "POST",
              "id": "health.projects.subscribers.create",
              "path": "v4/{+parent}/subscribers",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "delete": {
              "description": "Deletes a subscriber registration. This will stop all notifications to the subscriber's endpoint.",
              "flatPath": "v4/projects/{projectsId}/subscribers/{subscribersId}",
              "httpMethod": "DELETE",
              "id": "health.projects.subscribers.delete",
              "path": "v4/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "list": {
              "description": "Lists all subscribers registered within the owned Google Cloud Project.",
              "flatPath": "v4/projects/{projectsId}/subscribers",
              "httpMethod": "GET",
              "id": "health.projects.subscribers.list",
              "path": "v4/{+parent}/subscribers",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "patch": {
              "description": "Updates the configuration of an existing subscriber, such as the endpoint URI or the data types it's interested in. **Endpoint Verification:** If the `endpoint_uri` or `endpoint_authorization` field is included in the `update_mask`, the backend will re-verify the endpoint. The verification process is the same as described in `CreateSubscriber`: 1. **Verification with Authorization:** POST to the new or existing `endpoint_uri` with the new or existing `Authorization`[...]",
              "flatPath": "v4/projects/{projectsId}/subscribers/{subscribersId}",
              "httpMethod": "PATCH",
              "id": "health.projects.subscribers.patch",
              "path": "v4/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            }
          },
          "resources": {
            "subscriptions": {
              "methods": {
                "create": {
                  "description": "Creates a subscription for a specific user to a specific subscriber. This method requires the subscriber to have a `SubscriptionCreatePolicy` set to `MANUAL` for the given data types.",
                  "flatPath": "v4/projects/{projectsId}/subscribers/{subscribersId}/subscriptions",
                  "httpMethod": "POST",
                  "id": "health.projects.subscribers.subscriptions.create",
                  "path": "v4/{+parent}/subscriptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "delete": {
                  "description": "Deletes a specific user subscription, stopping notifications for this user to this subscriber.",
                  "flatPath": "v4/projects/{projectsId}/subscribers/{subscribersId}/subscriptions/{subscriptionsId}",
                  "httpMethod": "DELETE",
                  "id": "health.projects.subscribers.subscriptions.delete",
                  "path": "v4/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "list": {
                  "description": "Lists all active subscriptions for a given subscriber. This can be filtered, for example, by user or data type.",
                  "flatPath": "v4/projects/{projectsId}/subscribers/{subscribersId}/subscriptions",
                  "httpMethod": "GET",
                  "id": "health.projects.subscribers.subscriptions.list",
                  "path": "v4/{+parent}/subscriptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "patch": {
                  "description": "Updates the data types for an existing user subscription.",
                  "flatPath": "v4/projects/{projectsId}/subscribers/{subscribersId}/subscriptions/{subscriptionsId}",
                  "httpMethod": "PATCH",
                  "id": "health.projects.subscribers.subscriptions.patch",
                  "path": "v4/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "users": {
      "methods": {
        "getIdentity": {
          "description": "Gets the user's identity. It includes the legacy Fitbit user ID and the Google user ID and it can be used by migrating clients to map identifiers between the two systems.",
          "flatPath": "v4/users/{usersId}/identity",
          "httpMethod": "GET",
          "id": "health.users.getIdentity",
          "path": "v4/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly",
            "https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly",
            "https://www.googleapis.com/auth/googlehealth.profile.readonly",
            "https://www.googleapis.com/auth/googlehealth.settings.readonly",
            "https://www.googleapis.com/auth/googlehealth.sleep.readonly"
          ]
        },
        "getIrnProfile": {
          "description": "Returns user's IRN Profile details.",
          "flatPath": "v4/users/{usersId}/irnProfile",
          "httpMethod": "GET",
          "id": "health.users.getIrnProfile",
          "path": "v4/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/googlehealth.irn.readonly"
          ]
        },
        "getProfile": {
          "description": "Returns user Profile details.",
          "flatPath": "v4/users/{usersId}/profile",
          "httpMethod": "GET",
          "id": "health.users.getProfile",
          "path": "v4/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/googlehealth.profile.readonly"
          ]
        },
        "getSettings": {
          "description": "Returns user settings details.",
          "flatPath": "v4/users/{usersId}/settings",
          "httpMethod": "GET",
          "id": "health.users.getSettings",
          "path": "v4/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/googlehealth.settings.readonly"
          ]
        },
        "updateProfile": {
          "description": "Updates the user's profile details.",
          "flatPath": "v4/users/{usersId}/profile",
          "httpMethod": "PATCH",
          "id": "health.users.updateProfile",
          "path": "v4/{+name}"
        },
        "updateSettings": {
          "description": "Updates the user's settings details.",
          "flatPath": "v4/users/{usersId}/settings",
          "httpMethod": "PATCH",
          "id": "health.users.updateSettings",
          "path": "v4/{+name}"
        }
      },
      "resources": {
        "dataTypes": {
          "resources": {
            "dataPoints": {
              "methods": {
                "batchDelete": {
                  "description": "Delete a batch of identifyable data points.",
                  "flatPath": "v4/users/{usersId}/dataTypes/{dataTypesId}/dataPoints:batchDelete",
                  "httpMethod": "POST",
                  "id": "health.users.dataTypes.dataPoints.batchDelete",
                  "path": "v4/{+parent}/dataPoints:batchDelete"
                },
                "create": {
                  "description": "Creates a single identifiable data point.",
                  "flatPath": "v4/users/{usersId}/dataTypes/{dataTypesId}/dataPoints",
                  "httpMethod": "POST",
                  "id": "health.users.dataTypes.dataPoints.create",
                  "path": "v4/{+parent}/dataPoints"
                },
                "dailyRollUp": {
                  "description": "Roll up data points over civil time intervals for supported data types.",
                  "flatPath": "v4/users/{usersId}/dataTypes/{dataTypesId}/dataPoints:dailyRollUp",
                  "httpMethod": "POST",
                  "id": "health.users.dataTypes.dataPoints.dailyRollUp",
                  "path": "v4/{+parent}/dataPoints:dailyRollUp",
                  "scopes": [
                    "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly",
                    "https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly",
                    "https://www.googleapis.com/auth/googlehealth.location.readonly",
                    "https://www.googleapis.com/auth/googlehealth.sleep.readonly"
                  ]
                },
                "exportExerciseTcx": {
                  "description": "Exports exercise data in TCX format. **IMPORTANT:** HTTP clients must append `?alt=media` to the request URL to download the raw TCX file. Example: `https://health.googleapis.com/v4/users/me/dataTypes/exercise/dataPoints/EXERCISE_ID:exportExerciseTcx?alt=media` Without `alt=media`, the server returns a JSON response (`ExportExerciseTcxResponse`) which is intended primarily for gRPC clients. **Note:** While the Authorization section below states that any one of t[...]",
                  "flatPath": "v4/users/{usersId}/dataTypes/{dataTypesId}/dataPoints/{dataPointsId}:exportExerciseTcx",
                  "httpMethod": "GET",
                  "id": "health.users.dataTypes.dataPoints.exportExerciseTcx",
                  "path": "v4/{+name}:exportExerciseTcx",
                  "scopes": [
                    "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly",
                    "https://www.googleapis.com/auth/googlehealth.location.readonly"
                  ],
                  "supportsMediaDownload": true,
                  "useMediaDownloadService": true
                },
                "get": {
                  "description": "Get a single identifyable data point.",
                  "flatPath": "v4/users/{usersId}/dataTypes/{dataTypesId}/dataPoints/{dataPointsId}",
                  "httpMethod": "GET",
                  "id": "health.users.dataTypes.dataPoints.get",
                  "path": "v4/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly",
                    "https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly",
                    "https://www.googleapis.com/auth/googlehealth.location.readonly",
                    "https://www.googleapis.com/auth/googlehealth.sleep.readonly"
                  ]
                },
                "list": {
                  "description": "Query user health and fitness data points.",
                  "flatPath": "v4/users/{usersId}/dataTypes/{dataTypesId}/dataPoints",
                  "httpMethod": "GET",
                  "id": "health.users.dataTypes.dataPoints.list",
                  "path": "v4/{+parent}/dataPoints",
                  "scopes": [
                    "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly",
                    "https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly",
                    "https://www.googleapis.com/auth/googlehealth.location.readonly",
                    "https://www.googleapis.com/auth/googlehealth.sleep.readonly"
                  ]
                },
                "patch": {
                  "description": "Updates a single identifiable data point. If a data point with the specified `name` is not found, the request will fail.",
                  "flatPath": "v4/users/{usersId}/dataTypes/{dataTypesId}/dataPoints/{dataPointsId}",
                  "httpMethod": "PATCH",
                  "id": "health.users.dataTypes.dataPoints.patch",
                  "path": "v4/{+name}"
                },
                "reconcile": {
                  "description": "Reconcile data points from multiple data sources into a single data stream.",
                  "flatPath": "v4/users/{usersId}/dataTypes/{dataTypesId}/dataPoints:reconcile",
                  "httpMethod": "GET",
                  "id": "health.users.dataTypes.dataPoints.reconcile",
                  "path": "v4/{+parent}/dataPoints:reconcile",
                  "scopes": [
                    "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly",
                    "https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly",
                    "https://www.googleapis.com/auth/googlehealth.location.readonly",
                    "https://www.googleapis.com/auth/googlehealth.sleep.readonly"
                  ]
                },
                "rollUp": {
                  "description": "Roll up data points over physical time intervals for supported data types.",
                  "flatPath": "v4/users/{usersId}/dataTypes/{dataTypesId}/dataPoints:rollUp",
                  "httpMethod": "POST",
                  "id": "health.users.dataTypes.dataPoints.rollUp",
                  "path": "v4/{+parent}/dataPoints:rollUp",
                  "scopes": [
                    "https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly",
                    "https://www.googleapis.com/auth/googlehealth.health_metrics_and_measurements.readonly",
                    "https://www.googleapis.com/auth/googlehealth.location.readonly",
                    "https://www.googleapis.com/auth/googlehealth.sleep.readonly"
                  ]
                }
              }
            }
          }
        },
        "pairedDevices": {
          "methods": {
            "get": {
              "description": "Returns user's Device.",
              "flatPath": "v4/users/{usersId}/pairedDevices/{pairedDevicesId}",
              "httpMethod": "GET",
              "id": "health.users.pairedDevices.get",
              "path": "v4/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/googlehealth.settings.readonly"
              ]
            },
            "list": {
              "description": "Returns the user's list of paired 1P trackers and smartwatches.",
              "flatPath": "v4/users/{usersId}/pairedDevices",
              "httpMethod": "GET",
              "id": "health.users.pairedDevices.list",
              "path": "v4/{+parent}/pairedDevices",
              "scopes": [
                "https://www.googleapis.com/auth/googlehealth.settings.readonly"
              ]
            }
          }
        }
      }
    }
  },
  "revision": "20260525",
  "rootUrl": "https://health.googleapis.com/",
  "servicePath": "",
  "title": "Google Health API",
  "version": "v4",
  "version_module": true
}