{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/meetings.space.created": {
          "description": "Create, edit, and see information about your Google Meet conferences created by the app."
        },
        "https://www.googleapis.com/auth/meetings.space.readonly": {
          "description": "Read information about any of your Google Meet conferences"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://meet.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Meet",
  "description": "Create and manage meetings in Google Meet.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/meet/api",
  "fullyEncodeReservedExpansion": true,
  "id": "meet:v2",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://meet.mtls.googleapis.com/",
  "name": "meet",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "conferenceRecords": {
      "methods": {
        "get": {
          "description": "Gets a conference record by conference ID.",
          "flatPath": "v2/conferenceRecords/{conferenceRecordsId}",
          "httpMethod": "GET",
          "id": "meet.conferenceRecords.get",
          "path": "v2/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        },
        "list": {
          "description": "Lists the conference records. By default, ordered by start time and in descending order.",
          "flatPath": "v2/conferenceRecords",
          "httpMethod": "GET",
          "id": "meet.conferenceRecords.list",
          "path": "v2/conferenceRecords",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        }
      },
      "resources": {
        "participants": {
          "methods": {
            "get": {
              "description": "Gets a participant by participant ID.",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}",
              "httpMethod": "GET",
              "id": "meet.conferenceRecords.participants.get",
              "path": "v2/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ]
            },
            "list": {
              "description": "Lists the participants in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted, this API defaults to `'participants/*, next_page_token'`.",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/participants",
              "httpMethod": "GET",
              "id": "meet.conferenceRecords.participants.list",
              "path": "v2/{+parent}/participants",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ]
            }
          },
          "resources": {
            "participantSessions": {
              "methods": {
                "get": {
                  "description": "Gets a participant session by participant session ID.",
                  "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions/{participantSessionsId}",
                  "httpMethod": "GET",
                  "id": "meet.conferenceRecords.participants.participantSessions.get",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ]
                },
                "list": {
                  "description": "Lists the participant sessions of a participant in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted this API defaults to `'participantsessions/*, next_page_token'`.",
                  "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions",
                  "httpMethod": "GET",
                  "id": "meet.conferenceRecords.participants.participantSessions.list",
                  "path": "v2/{+parent}/participantSessions",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ]
                }
              }
            }
          }
        },
        "recordings": {
          "methods": {
            "get": {
              "description": "Gets a recording by recording ID.",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/recordings/{recordingsId}",
              "httpMethod": "GET",
              "id": "meet.conferenceRecords.recordings.get",
              "path": "v2/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ]
            },
            "list": {
              "description": "Lists the recording resources from the conference record. By default, ordered by start time and in ascending order.",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/recordings",
              "httpMethod": "GET",
              "id": "meet.conferenceRecords.recordings.list",
              "path": "v2/{+parent}/recordings",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ]
            }
          }
        },
        "transcripts": {
          "methods": {
            "get": {
              "description": "Gets a transcript by transcript ID.",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}",
              "httpMethod": "GET",
              "id": "meet.conferenceRecords.transcripts.get",
              "path": "v2/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ]
            },
            "list": {
              "description": "Lists the set of transcripts from the conference record. By default, ordered by start time and in ascending order.",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/transcripts",
              "httpMethod": "GET",
              "id": "meet.conferenceRecords.transcripts.list",
              "path": "v2/{+parent}/transcripts",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ]
            }
          },
          "resources": {
            "entries": {
              "methods": {
                "get": {
                  "description": "Gets a `TranscriptEntry` resource by entry ID. Note: The transcript entries returned by the Google Meet API might not match the transcription found in the Google Docs transcript file. This can occur when the Google Docs transcript file is modified after generation.",
                  "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries/{entriesId}",
                  "httpMethod": "GET",
                  "id": "meet.conferenceRecords.transcripts.entries.get",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ]
                },
                "list": {
                  "description": "Lists the structured transcript entries per transcript. By default, ordered by start time and in ascending order. Note: The transcript entries returned by the Google Meet API might not match the transcription found in the Google Docs transcript file. This can occur when the Google Docs transcript file is modified after generation.",
                  "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries",
                  "httpMethod": "GET",
                  "id": "meet.conferenceRecords.transcripts.entries.list",
                  "path": "v2/{+parent}/entries",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "spaces": {
      "methods": {
        "create": {
          "description": "Creates a space.",
          "flatPath": "v2/spaces",
          "httpMethod": "POST",
          "id": "meet.spaces.create",
          "path": "v2/spaces",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created"
          ]
        },
        "endActiveConference": {
          "description": "Ends an active conference (if there's one).",
          "flatPath": "v2/spaces/{spacesId}:endActiveConference",
          "httpMethod": "POST",
          "id": "meet.spaces.endActiveConference",
          "path": "v2/{+name}:endActiveConference",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created"
          ]
        },
        "get": {
          "description": "Gets a space by `space_id` or `meeting_code`.",
          "flatPath": "v2/spaces/{spacesId}",
          "httpMethod": "GET",
          "id": "meet.spaces.get",
          "path": "v2/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        },
        "patch": {
          "description": "Updates a space.",
          "flatPath": "v2/spaces/{spacesId}",
          "httpMethod": "PATCH",
          "id": "meet.spaces.patch",
          "path": "v2/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created"
          ]
        }
      }
    }
  },
  "revision": "20240626",
  "rootUrl": "https://meet.googleapis.com/",
  "servicePath": "",
  "title": "Google Meet API",
  "version": "v2",
  "version_module": true
}