{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://vault.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Vault",
  "description": "Archiving and eDiscovery for G Suite.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/vault",
  "fullyEncodeReservedExpansion": true,
  "id": "vault:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "name": "vault",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "matters": {
      "methods": {
        "addPermissions": {
          "description": "Adds an account as a matter collaborator.",
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "httpMethod": "POST",
          "id": "vault.matters.addPermissions",
          "path": "v1/matters/{matterId}:addPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "close": {
          "description": "Closes the specified matter. Returns matter with updated state.",
          "flatPath": "v1/matters/{matterId}:close",
          "httpMethod": "POST",
          "id": "vault.matters.close",
          "path": "v1/matters/{matterId}:close",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "count": {
          "description": "Counts the artifacts within the context of a matter and returns a detailed breakdown of metrics.",
          "flatPath": "v1/matters/{matterId}:count",
          "httpMethod": "POST",
          "id": "vault.matters.count",
          "path": "v1/matters/{matterId}:count",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "create": {
          "description": "Creates a new matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "flatPath": "v1/matters",
          "httpMethod": "POST",
          "id": "vault.matters.create",
          "path": "v1/matters",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "delete": {
          "description": "Deletes the specified matter. Returns matter with updated state.",
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "DELETE",
          "id": "vault.matters.delete",
          "path": "v1/matters/{matterId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "get": {
          "description": "Gets the specified matter.",
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "GET",
          "id": "vault.matters.get",
          "path": "v1/matters/{matterId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "list": {
          "description": "Lists matters the user has access to.",
          "flatPath": "v1/matters",
          "httpMethod": "GET",
          "id": "vault.matters.list",
          "path": "v1/matters",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "removePermissions": {
          "description": "Removes an account as a matter collaborator.",
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "httpMethod": "POST",
          "id": "vault.matters.removePermissions",
          "path": "v1/matters/{matterId}:removePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "reopen": {
          "description": "Reopens the specified matter. Returns matter with updated state.",
          "flatPath": "v1/matters/{matterId}:reopen",
          "httpMethod": "POST",
          "id": "vault.matters.reopen",
          "path": "v1/matters/{matterId}:reopen",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "undelete": {
          "description": "Undeletes the specified matter. Returns matter with updated state.",
          "flatPath": "v1/matters/{matterId}:undelete",
          "httpMethod": "POST",
          "id": "vault.matters.undelete",
          "path": "v1/matters/{matterId}:undelete",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "update": {
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "PUT",
          "id": "vault.matters.update",
          "path": "v1/matters/{matterId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        }
      },
      "resources": {
        "exports": {
          "methods": {
            "create": {
              "description": "Creates an Export.",
              "flatPath": "v1/matters/{matterId}/exports",
              "httpMethod": "POST",
              "id": "vault.matters.exports.create",
              "path": "v1/matters/{matterId}/exports",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "delete": {
              "description": "Deletes an Export.",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "DELETE",
              "id": "vault.matters.exports.delete",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "get": {
              "description": "Gets an Export.",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "GET",
              "id": "vault.matters.exports.get",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "list": {
              "description": "Lists Exports.",
              "flatPath": "v1/matters/{matterId}/exports",
              "httpMethod": "GET",
              "id": "vault.matters.exports.list",
              "path": "v1/matters/{matterId}/exports",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            }
          }
        },
        "holds": {
          "methods": {
            "addHeldAccounts": {
              "description": "Adds HeldAccounts to a hold. Returns a list of accounts that have been successfully added. Accounts can only be added to an existing account-based hold.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "httpMethod": "POST",
              "id": "vault.matters.holds.addHeldAccounts",
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "create": {
              "description": "Creates a hold in the given matter.",
              "flatPath": "v1/matters/{matterId}/holds",
              "httpMethod": "POST",
              "id": "vault.matters.holds.create",
              "path": "v1/matters/{matterId}/holds",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "delete": {
              "description": "Removes a hold by ID. This will release any HeldAccounts on this Hold.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "DELETE",
              "id": "vault.matters.holds.delete",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "get": {
              "description": "Gets a hold by ID.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "GET",
              "id": "vault.matters.holds.get",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "list": {
              "description": "Lists holds within a matter. An empty page token in ListHoldsResponse denotes no more holds to list.",
              "flatPath": "v1/matters/{matterId}/holds",
              "httpMethod": "GET",
              "id": "vault.matters.holds.list",
              "path": "v1/matters/{matterId}/holds",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "removeHeldAccounts": {
              "description": "Removes HeldAccounts from a hold. Returns a list of statuses in the same order as the request. If this request leaves the hold with no held accounts, the hold will not apply to any accounts.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "httpMethod": "POST",
              "id": "vault.matters.holds.removeHeldAccounts",
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "update": {
              "description": "Updates the OU and/or query parameters of a hold. You cannot add accounts to a hold that covers an OU, nor can you add OUs to a hold that covers individual accounts. Accounts listed in the hold will be ignored.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "PUT",
              "id": "vault.matters.holds.update",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            }
          },
          "resources": {
            "accounts": {
              "methods": {
                "create": {
                  "description": "Adds a HeldAccount to a hold. Accounts can only be added to a hold that has no held_org_unit set. Attempting to add an account to an OU-based hold will result in an error.",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "POST",
                  "id": "vault.matters.holds.accounts.create",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ]
                },
                "delete": {
                  "description": "Removes a HeldAccount from a hold. If this request leaves the hold with no held accounts, the hold will not apply to any accounts.",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "httpMethod": "DELETE",
                  "id": "vault.matters.holds.accounts.delete",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ]
                },
                "list": {
                  "description": "Lists HeldAccounts for a hold. This will only list individually specified held accounts. If the hold is on an OU, then use Admin SDK to enumerate its members.",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "GET",
                  "id": "vault.matters.holds.accounts.list",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ]
                }
              }
            }
          }
        },
        "savedQueries": {
          "methods": {
            "create": {
              "description": "Creates a saved query.",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "POST",
              "id": "vault.matters.savedQueries.create",
              "path": "v1/matters/{matterId}/savedQueries",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "delete": {
              "description": "Deletes a saved query by Id.",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "DELETE",
              "id": "vault.matters.savedQueries.delete",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "get": {
              "description": "Retrieves a saved query by Id.",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "GET",
              "id": "vault.matters.savedQueries.get",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "list": {
              "description": "Lists saved queries within a matter. An empty page token in ListSavedQueriesResponse denotes no more saved queries to list.",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "GET",
              "id": "vault.matters.savedQueries.list",
              "path": "v1/matters/{matterId}/savedQueries",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "httpMethod": "POST",
          "id": "vault.operations.cancel",
          "path": "v1/{+name}:cancel"
        },
        "delete": {
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "DELETE",
          "id": "vault.operations.delete",
          "path": "v1/{+name}"
        },
        "get": {
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "id": "vault.operations.get",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "list": {
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the operatio[...]",
          "flatPath": "v1/operations",
          "httpMethod": "GET",
          "id": "vault.operations.list",
          "path": "v1/{+name}"
        }
      }
    }
  },
  "revision": "20210406",
  "rootUrl": "https://vault.googleapis.com/",
  "servicePath": "",
  "title": "G Suite Vault API",
  "version": "v1",
  "version_module": true
}