{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage": {
          "description": "Private Service: https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage"
        },
        "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.readonly": {
          "description": "See and review your subscription information"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://webcontentpublisher.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Web Content Publisher",
  "description": "webcontentpublisher.googleapis.com API, a service for web content publishers.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/news/subscribe",
  "fullyEncodeReservedExpansion": true,
  "id": "webcontentpublisher:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://webcontentpublisher.mtls.googleapis.com/",
  "name": "webcontentpublisher",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "organizations": {
      "resources": {
        "publications": {
          "methods": {
            "create": {
              "description": "Creates a publication.",
              "flatPath": "v1/organizations/{organizationsId}/publications",
              "httpMethod": "POST",
              "id": "webcontentpublisher.organizations.publications.create",
              "path": "v1/{+parent}/publications",
              "scopes": [
                "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage"
              ]
            },
            "get": {
              "description": "Gets a publication.",
              "flatPath": "v1/organizations/{organizationsId}/publications/{publicationsId}",
              "httpMethod": "GET",
              "id": "webcontentpublisher.organizations.publications.get",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage",
                "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.readonly"
              ]
            },
            "list": {
              "description": "Lists publications.",
              "flatPath": "v1/organizations/{organizationsId}/publications",
              "httpMethod": "GET",
              "id": "webcontentpublisher.organizations.publications.list",
              "path": "v1/{+parent}/publications",
              "scopes": [
                "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage",
                "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.readonly"
              ]
            },
            "patch": {
              "description": "Updates a publication.",
              "flatPath": "v1/organizations/{organizationsId}/publications/{publicationsId}",
              "httpMethod": "PATCH",
              "id": "webcontentpublisher.organizations.publications.patch",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage"
              ]
            }
          },
          "resources": {
            "ctas": {
              "methods": {
                "create": {
                  "description": "Creates a CTA.",
                  "flatPath": "v1/organizations/{organizationsId}/publications/{publicationsId}/ctas",
                  "httpMethod": "POST",
                  "id": "webcontentpublisher.organizations.publications.ctas.create",
                  "path": "v1/{+parent}/ctas",
                  "scopes": [
                    "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage"
                  ]
                },
                "get": {
                  "description": "Gets a CTA.",
                  "flatPath": "v1/organizations/{organizationsId}/publications/{publicationsId}/ctas/{ctasId}",
                  "httpMethod": "GET",
                  "id": "webcontentpublisher.organizations.publications.ctas.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage",
                    "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.readonly"
                  ]
                },
                "list": {
                  "description": "Lists CTAs.",
                  "flatPath": "v1/organizations/{organizationsId}/publications/{publicationsId}/ctas",
                  "httpMethod": "GET",
                  "id": "webcontentpublisher.organizations.publications.ctas.list",
                  "path": "v1/{+parent}/ctas",
                  "scopes": [
                    "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage",
                    "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.readonly"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "publications": {
      "methods": {
        "checkFreeAccess": {
          "description": "Checks if a user is eligible for free article access.",
          "flatPath": "v1/publications/{publicationsId}:checkFreeAccess",
          "httpMethod": "GET",
          "id": "webcontentpublisher.publications.checkFreeAccess",
          "path": "v1/{+name}:checkFreeAccess",
          "scopes": [
            "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.manage",
            "https://www.googleapis.com/auth/subscribewithgoogle.publications.entitlements.readonly"
          ]
        }
      }
    }
  },
  "revision": "20260724",
  "rootUrl": "https://webcontentpublisher.googleapis.com/",
  "servicePath": "",
  "title": "Web Content Publisher API",
  "version": "v1",
  "version_module": true
}