{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chat.app.memberships": {
          "description": "On their own behalf, apps in Google Chat can see, add, update, and remove members from conversations and spaces"
        },
        "https://www.googleapis.com/auth/chat.app.messages.readonly": {
          "description": "On their own behalf, apps in Google Chat can see all messages and their associated reactions and message content"
        },
        "https://www.googleapis.com/auth/chat.app.spaces": {
          "description": "On their own behalf, apps in Google Chat can create conversations and spaces and see or update their metadata (including history settings and access settings)"
        },
        "https://www.googleapis.com/auth/chat.bot": {
          "description": "Private Service: https://www.googleapis.com/auth/chat.bot"
        },
        "https://www.googleapis.com/auth/chat.memberships": {
          "description": "See, add, update, and remove members from conversations and spaces in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.memberships.readonly": {
          "description": "View members in Google Chat conversations."
        },
        "https://www.googleapis.com/auth/chat.messages": {
          "description": "See, compose, send, update, and delete messages as well as their message content; add, see, and delete reactions to messages."
        },
        "https://www.googleapis.com/auth/chat.messages.reactions": {
          "description": "See, add, and delete reactions as well as their reaction content to messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.reactions.readonly": {
          "description": "View reactions as well as their reaction content to messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.readonly": {
          "description": "See messages as well as their reactions and message content in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.spaces": {
          "description": "Create conversations and spaces and see or update metadata (including history settings and access settings) in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.spaces.readonly": {
          "description": "View chat and spaces in Google Chat"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/meetings.space.created": {
          "description": "Create, edit, and see information about your Google Meet conferences created by the app."
        },
        "https://www.googleapis.com/auth/meetings.space.readonly": {
          "description": "Read information about any of your Google Meet conferences"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://workspaceevents.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Workspace Events",
  "description": "The Google Workspace Events API lets you subscribe to events and manage change notifications across Google Workspace applications.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/workspace/events",
  "fullyEncodeReservedExpansion": true,
  "id": "workspaceevents:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://workspaceevents.mtls.googleapis.com/",
  "name": "workspaceevents",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "message": {
      "methods": {
        "stream": {
          "description": "SendStreamingMessage is a streaming call that will return a stream of task update events until the Task is in an interrupted or terminal state.",
          "flatPath": "v1/message:stream",
          "httpMethod": "POST",
          "id": "workspaceevents.message.stream",
          "path": "v1/message:stream"
        }
      }
    },
    "operations": {
      "methods": {
        "get": {
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "id": "workspaceevents.operations.get",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.memberships",
            "https://www.googleapis.com/auth/chat.memberships.readonly",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.reactions",
            "https://www.googleapis.com/auth/chat.messages.reactions.readonly",
            "https://www.googleapis.com/auth/chat.messages.readonly",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        }
      }
    },
    "subscriptions": {
      "methods": {
        "create": {
          "description": "Creates a Google Workspace subscription. To learn how to use this method, see [Create a Google Workspace subscription](https://developers.google.com/workspace/events/guides/create-subscription). For a subscription on a [Chat target resource](https://developers.google.com/workspace/events/guides/events-chat), you can create a subscription as: - A Chat app by specifying an authorization scope that begins with `chat.app` and getting one-time administrator approval ([Develo[...]",
          "flatPath": "v1/subscriptions",
          "httpMethod": "POST",
          "id": "workspaceevents.subscriptions.create",
          "path": "v1/subscriptions",
          "scopes": [
            "https://www.googleapis.com/auth/chat.app.memberships",
            "https://www.googleapis.com/auth/chat.app.messages.readonly",
            "https://www.googleapis.com/auth/chat.app.spaces",
            "https://www.googleapis.com/auth/chat.memberships",
            "https://www.googleapis.com/auth/chat.memberships.readonly",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.reactions",
            "https://www.googleapis.com/auth/chat.messages.reactions.readonly",
            "https://www.googleapis.com/auth/chat.messages.readonly",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        },
        "delete": {
          "description": "Deletes a Google Workspace subscription. To learn how to use this method, see [Delete a Google Workspace subscription](https://developers.google.com/workspace/events/guides/delete-subscription).",
          "flatPath": "v1/subscriptions/{subscriptionsId}",
          "httpMethod": "DELETE",
          "id": "workspaceevents.subscriptions.delete",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.memberships",
            "https://www.googleapis.com/auth/chat.memberships.readonly",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.reactions",
            "https://www.googleapis.com/auth/chat.messages.reactions.readonly",
            "https://www.googleapis.com/auth/chat.messages.readonly",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        },
        "get": {
          "description": "Gets details about a Google Workspace subscription. To learn how to use this method, see [Get details about a Google Workspace subscription](https://developers.google.com/workspace/events/guides/get-subscription).",
          "flatPath": "v1/subscriptions/{subscriptionsId}",
          "httpMethod": "GET",
          "id": "workspaceevents.subscriptions.get",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.memberships",
            "https://www.googleapis.com/auth/chat.memberships.readonly",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.reactions",
            "https://www.googleapis.com/auth/chat.messages.reactions.readonly",
            "https://www.googleapis.com/auth/chat.messages.readonly",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        },
        "list": {
          "description": "Lists Google Workspace subscriptions. To learn how to use this method, see [List Google Workspace subscriptions](https://developers.google.com/workspace/events/guides/list-subscriptions).",
          "flatPath": "v1/subscriptions",
          "httpMethod": "GET",
          "id": "workspaceevents.subscriptions.list",
          "path": "v1/subscriptions",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.memberships",
            "https://www.googleapis.com/auth/chat.memberships.readonly",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.reactions",
            "https://www.googleapis.com/auth/chat.messages.reactions.readonly",
            "https://www.googleapis.com/auth/chat.messages.readonly",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        },
        "patch": {
          "description": "Updates or renews a Google Workspace subscription. To learn how to use this method, see [Update or renew a Google Workspace subscription](https://developers.google.com/workspace/events/guides/update-subscription). For a subscription on a [Chat target resource](https://developers.google.com/workspace/events/guides/events-chat), you can update a subscription as: - A Chat app by specifying an authorization scope that begins with `chat.app` andgetting one-time administrator[...]",
          "flatPath": "v1/subscriptions/{subscriptionsId}",
          "httpMethod": "PATCH",
          "id": "workspaceevents.subscriptions.patch",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/chat.app.memberships",
            "https://www.googleapis.com/auth/chat.app.messages.readonly",
            "https://www.googleapis.com/auth/chat.app.spaces",
            "https://www.googleapis.com/auth/chat.memberships",
            "https://www.googleapis.com/auth/chat.memberships.readonly",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.reactions",
            "https://www.googleapis.com/auth/chat.messages.reactions.readonly",
            "https://www.googleapis.com/auth/chat.messages.readonly",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        },
        "reactivate": {
          "description": "Reactivates a suspended Google Workspace subscription. This method resets your subscription's `State` field to `ACTIVE`. Before you use this method, you must fix the error that suspended the subscription. This method will ignore or reject any subscription that isn't currently in a suspended state. To learn how to use this method, see [Reactivate a Google Workspace subscription](https://developers.google.com/workspace/events/guides/reactivate-subscription). For a subscri[...]",
          "flatPath": "v1/subscriptions/{subscriptionsId}:reactivate",
          "httpMethod": "POST",
          "id": "workspaceevents.subscriptions.reactivate",
          "path": "v1/{+name}:reactivate",
          "scopes": [
            "https://www.googleapis.com/auth/chat.app.memberships",
            "https://www.googleapis.com/auth/chat.app.messages.readonly",
            "https://www.googleapis.com/auth/chat.app.spaces",
            "https://www.googleapis.com/auth/chat.memberships",
            "https://www.googleapis.com/auth/chat.memberships.readonly",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.reactions",
            "https://www.googleapis.com/auth/chat.messages.reactions.readonly",
            "https://www.googleapis.com/auth/chat.messages.readonly",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        }
      }
    },
    "tasks": {
      "methods": {
        "cancel": {
          "description": "Cancel a task from the agent. If supported one should expect no more task updates for the task.",
          "flatPath": "v1/tasks/{tasksId}:cancel",
          "httpMethod": "POST",
          "id": "workspaceevents.tasks.cancel",
          "path": "v1/{+name}:cancel"
        },
        "get": {
          "description": "Get the current state of a task from the agent.",
          "flatPath": "v1/tasks/{tasksId}",
          "httpMethod": "GET",
          "id": "workspaceevents.tasks.get",
          "path": "v1/{+name}"
        },
        "subscribe": {
          "description": "TaskSubscription is a streaming call that will return a stream of task update events. This attaches the stream to an existing in process task. If the task is complete the stream will return the completed task (like GetTask) and close the stream.",
          "flatPath": "v1/tasks/{tasksId}:subscribe",
          "httpMethod": "GET",
          "id": "workspaceevents.tasks.subscribe",
          "path": "v1/{+name}:subscribe"
        }
      },
      "resources": {
        "pushNotificationConfigs": {
          "methods": {
            "create": {
              "description": "Set a push notification config for a task.",
              "flatPath": "v1/tasks/{tasksId}/pushNotificationConfigs",
              "httpMethod": "POST",
              "id": "workspaceevents.tasks.pushNotificationConfigs.create",
              "path": "v1/{+parent}"
            },
            "delete": {
              "description": "Delete a push notification config for a task.",
              "flatPath": "v1/tasks/{tasksId}/pushNotificationConfigs/{pushNotificationConfigsId}",
              "httpMethod": "DELETE",
              "id": "workspaceevents.tasks.pushNotificationConfigs.delete",
              "path": "v1/{+name}"
            },
            "get": {
              "description": "Get a push notification config for a task.",
              "flatPath": "v1/tasks/{tasksId}/pushNotificationConfigs/{pushNotificationConfigsId}",
              "httpMethod": "GET",
              "id": "workspaceevents.tasks.pushNotificationConfigs.get",
              "path": "v1/{+name}"
            },
            "list": {
              "description": "Get a list of push notifications configured for a task.",
              "flatPath": "v1/tasks/{tasksId}/pushNotificationConfigs",
              "httpMethod": "GET",
              "id": "workspaceevents.tasks.pushNotificationConfigs.list",
              "path": "v1/{+parent}/pushNotificationConfigs"
            }
          }
        }
      }
    }
  },
  "revision": "20251118",
  "rootUrl": "https://workspaceevents.googleapis.com/",
  "servicePath": "",
  "title": "Google Workspace Events API",
  "version": "v1",
  "version_module": true
}