/**
 * Copyright 2017 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*! THIS FILE IS AUTO-GENERATED */

import {GoogleApis} from './lib/googleapis';
const google = new GoogleApis();
export {google, GoogleApis};

export {abusiveexperiencereport_v1} from './apis/abusiveexperiencereport/v1';
export {acceleratedmobilepageurl_v1} from './apis/acceleratedmobilepageurl/v1';
export {adexchangebuyer_v1_2} from './apis/adexchangebuyer/v1.2';
export {adexchangebuyer_v1_3} from './apis/adexchangebuyer/v1.3';
export {adexchangebuyer_v1_4} from './apis/adexchangebuyer/v1.4';
export {adexchangebuyer2_v2beta1} from './apis/adexchangebuyer2/v2beta1';
export {adexchangeseller_v1_1} from './apis/adexchangeseller/v1.1';
export {adexchangeseller_v1} from './apis/adexchangeseller/v1';
export {adexchangeseller_v2_0} from './apis/adexchangeseller/v2.0';
export {adexperiencereport_v1} from './apis/adexperiencereport/v1';
export {admin_datatransfer_v1} from './apis/admin/datatransfer_v1';
export {admin_directory_v1} from './apis/admin/directory_v1';
export {admin_reports_v1} from './apis/admin/reports_v1';
export {adsense_v1_4} from './apis/adsense/v1.4';
export {adsensehost_v4_1} from './apis/adsensehost/v4.1';
export {analytics_v2_4} from './apis/analytics/v2.4';
export {analytics_v3} from './apis/analytics/v3';
export {analyticsreporting_v4} from './apis/analyticsreporting/v4';
export {androiddeviceprovisioning_v1} from './apis/androiddeviceprovisioning/v1';
export {androidenterprise_v1} from './apis/androidenterprise/v1';
export {androidmanagement_v1} from './apis/androidmanagement/v1';
export {androidpublisher_v1_1} from './apis/androidpublisher/v1.1';
export {androidpublisher_v1} from './apis/androidpublisher/v1';
export {androidpublisher_v2} from './apis/androidpublisher/v2';
export {appengine_v1} from './apis/appengine/v1';
export {appengine_v1alpha} from './apis/appengine/v1alpha';
export {appengine_v1beta} from './apis/appengine/v1beta';
export {appengine_v1beta4} from './apis/appengine/v1beta4';
export {appengine_v1beta5} from './apis/appengine/v1beta5';
export {appsactivity_v1} from './apis/appsactivity/v1';
export {appstate_v1} from './apis/appstate/v1';
export {bigquery_v2} from './apis/bigquery/v2';
export {bigquerydatatransfer_v1} from './apis/bigquerydatatransfer/v1';
export {blogger_v2} from './apis/blogger/v2';
export {blogger_v3} from './apis/blogger/v3';
export {books_v1} from './apis/books/v1';
export {calendar_v3} from './apis/calendar/v3';
export {chat_v1} from './apis/chat/v1';
export {civicinfo_v2} from './apis/civicinfo/v2';
export {classroom_v1} from './apis/classroom/v1';
export {cloudbilling_v1} from './apis/cloudbilling/v1';
export {cloudbuild_v1} from './apis/cloudbuild/v1';
export {clouddebugger_v2} from './apis/clouddebugger/v2';
export {clouderrorreporting_v1beta1} from './apis/clouderrorreporting/v1beta1';
export {cloudfunctions_v1} from './apis/cloudfunctions/v1';
export {cloudfunctions_v1beta2} from './apis/cloudfunctions/v1beta2';
export {cloudiot_v1} from './apis/cloudiot/v1';
export {cloudkms_v1} from './apis/cloudkms/v1';
export {cloudresourcemanager_v1} from './apis/cloudresourcemanager/v1';
export {cloudresourcemanager_v1beta1} from './apis/cloudresourcemanager/v1beta1';
export {cloudresourcemanager_v2} from './apis/cloudresourcemanager/v2';
export {cloudresourcemanager_v2beta1} from './apis/cloudresourcemanager/v2beta1';
export {cloudshell_v1} from './apis/cloudshell/v1';
export {cloudshell_v1alpha1} from './apis/cloudshell/v1alpha1';
export {cloudtasks_v2beta2} from './apis/cloudtasks/v2beta2';
export {cloudtrace_v1} from './apis/cloudtrace/v1';
export {cloudtrace_v2} from './apis/cloudtrace/v2';
export {composer_v1beta1} from './apis/composer/v1beta1';
export {compute_alpha} from './apis/compute/alpha';
export {compute_beta} from './apis/compute/beta';
export {compute_v1} from './apis/compute/v1';
export {container_v1} from './apis/container/v1';
export {container_v1beta1} from './apis/container/v1beta1';
export {content_v2} from './apis/content/v2';
export {content_v2sandbox} from './apis/content/v2sandbox';
export {customsearch_v1} from './apis/customsearch/v1';
export {dataflow_v1b3} from './apis/dataflow/v1b3';
export {dataproc_v1} from './apis/dataproc/v1';
export {dataproc_v1beta2} from './apis/dataproc/v1beta2';
export {datastore_v1} from './apis/datastore/v1';
export {datastore_v1beta1} from './apis/datastore/v1beta1';
export {datastore_v1beta3} from './apis/datastore/v1beta3';
export {deploymentmanager_alpha} from './apis/deploymentmanager/alpha';
export {deploymentmanager_v2} from './apis/deploymentmanager/v2';
export {deploymentmanager_v2beta} from './apis/deploymentmanager/v2beta';
export {dfareporting_v2_8} from './apis/dfareporting/v2.8';
export {dfareporting_v3_0} from './apis/dfareporting/v3.0';
export {dialogflow_v2} from './apis/dialogflow/v2';
export {dialogflow_v2beta1} from './apis/dialogflow/v2beta1';
export {digitalassetlinks_v1} from './apis/digitalassetlinks/v1';
export {discovery_v1} from './apis/discovery/v1';
export {dlp_v2} from './apis/dlp/v2';
export {dns_v1} from './apis/dns/v1';
export {dns_v1beta2} from './apis/dns/v1beta2';
export {dns_v2beta1} from './apis/dns/v2beta1';
export {doubleclickbidmanager_v1} from './apis/doubleclickbidmanager/v1';
export {doubleclicksearch_v2} from './apis/doubleclicksearch/v2';
export {drive_v2} from './apis/drive/v2';
export {drive_v3} from './apis/drive/v3';
export {firebasedynamiclinks_v1} from './apis/firebasedynamiclinks/v1';
export {firebaserules_v1} from './apis/firebaserules/v1';
export {firestore_v1beta1} from './apis/firestore/v1beta1';
export {fitness_v1} from './apis/fitness/v1';
export {fusiontables_v1} from './apis/fusiontables/v1';
export {fusiontables_v2} from './apis/fusiontables/v2';
export {games_v1} from './apis/games/v1';
export {gamesConfiguration_v1configuration} from './apis/gamesConfiguration/v1configuration';
export {gamesManagement_v1management} from './apis/gamesManagement/v1management';
export {genomics_v1} from './apis/genomics/v1';
export {genomics_v1alpha2} from './apis/genomics/v1alpha2';
export {genomics_v2alpha1} from './apis/genomics/v2alpha1';
export {gmail_v1} from './apis/gmail/v1';
export {groupsmigration_v1} from './apis/groupsmigration/v1';
export {groupssettings_v1} from './apis/groupssettings/v1';
export {iam_v1} from './apis/iam/v1';
export {identitytoolkit_v3} from './apis/identitytoolkit/v3';
export {kgsearch_v1} from './apis/kgsearch/v1';
export {language_v1} from './apis/language/v1';
export {language_v1beta1} from './apis/language/v1beta1';
export {language_v1beta2} from './apis/language/v1beta2';
export {licensing_v1} from './apis/licensing/v1';
export {logging_v2} from './apis/logging/v2';
export {logging_v2beta1} from './apis/logging/v2beta1';
export {manufacturers_v1} from './apis/manufacturers/v1';
export {mirror_v1} from './apis/mirror/v1';
export {ml_v1} from './apis/ml/v1';
export {monitoring_v3} from './apis/monitoring/v3';
export {oauth2_v1} from './apis/oauth2/v1';
export {oauth2_v2} from './apis/oauth2/v2';
export {oslogin_v1} from './apis/oslogin/v1';
export {oslogin_v1alpha} from './apis/oslogin/v1alpha';
export {oslogin_v1beta} from './apis/oslogin/v1beta';
export {pagespeedonline_v1} from './apis/pagespeedonline/v1';
export {pagespeedonline_v2} from './apis/pagespeedonline/v2';
export {pagespeedonline_v4} from './apis/pagespeedonline/v4';
export {partners_v2} from './apis/partners/v2';
export {people_v1} from './apis/people/v1';
export {playcustomapp_v1} from './apis/playcustomapp/v1';
export {plus_v1} from './apis/plus/v1';
export {plusDomains_v1} from './apis/plusDomains/v1';
export {poly_v1} from './apis/poly/v1';
export {proximitybeacon_v1beta1} from './apis/proximitybeacon/v1beta1';
export {pubsub_v1} from './apis/pubsub/v1';
export {pubsub_v1beta1a} from './apis/pubsub/v1beta1a';
export {pubsub_v1beta2} from './apis/pubsub/v1beta2';
export {redis_v1beta1} from './apis/redis/v1beta1';
export {replicapool_v1beta1} from './apis/replicapool/v1beta1';
export {replicapool_v1beta2} from './apis/replicapool/v1beta2';
export {replicapoolupdater_v1beta1} from './apis/replicapoolupdater/v1beta1';
export {reseller_v1} from './apis/reseller/v1';
export {resourceviews_v1beta1} from './apis/resourceviews/v1beta1';
export {resourceviews_v1beta2} from './apis/resourceviews/v1beta2';
export {runtimeconfig_v1} from './apis/runtimeconfig/v1';
export {runtimeconfig_v1beta1} from './apis/runtimeconfig/v1beta1';
export {safebrowsing_v4} from './apis/safebrowsing/v4';
export {script_v1} from './apis/script/v1';
export {searchconsole_v1} from './apis/searchconsole/v1';
export {servicebroker_v1} from './apis/servicebroker/v1';
export {servicebroker_v1alpha1} from './apis/servicebroker/v1alpha1';
export {servicebroker_v1beta1} from './apis/servicebroker/v1beta1';
export {serviceconsumermanagement_v1} from './apis/serviceconsumermanagement/v1';
export {servicecontrol_v1} from './apis/servicecontrol/v1';
export {servicemanagement_v1} from './apis/servicemanagement/v1';
export {serviceusage_v1beta1} from './apis/serviceusage/v1beta1';
export {serviceuser_v1} from './apis/serviceuser/v1';
export {sheets_v4} from './apis/sheets/v4';
export {siteVerification_v1} from './apis/siteVerification/v1';
export {slides_v1} from './apis/slides/v1';
export {sourcerepo_v1} from './apis/sourcerepo/v1';
export {spanner_v1} from './apis/spanner/v1';
export {spectrum_v1explorer} from './apis/spectrum/v1explorer';
export {speech_v1} from './apis/speech/v1';
export {speech_v1beta1} from './apis/speech/v1beta1';
export {sqladmin_v1beta3} from './apis/sqladmin/v1beta3';
export {sqladmin_v1beta4} from './apis/sqladmin/v1beta4';
export {storage_v1} from './apis/storage/v1';
export {storage_v1beta1} from './apis/storage/v1beta1';
export {storage_v1beta2} from './apis/storage/v1beta2';
export {storagetransfer_v1} from './apis/storagetransfer/v1';
export {streetviewpublish_v1} from './apis/streetviewpublish/v1';
export {surveys_v2} from './apis/surveys/v2';
export {tagmanager_v1} from './apis/tagmanager/v1';
export {tagmanager_v2} from './apis/tagmanager/v2';
export {tasks_v1} from './apis/tasks/v1';
export {testing_v1} from './apis/testing/v1';
export {texttospeech_v1beta1} from './apis/texttospeech/v1beta1';
export {toolresults_v1beta3} from './apis/toolresults/v1beta3';
export {tpu_v1alpha1} from './apis/tpu/v1alpha1';
export {translate_v2} from './apis/translate/v2';
export {urlshortener_v1} from './apis/urlshortener/v1';
export {vault_v1} from './apis/vault/v1';
export {videointelligence_v1} from './apis/videointelligence/v1';
export {videointelligence_v1beta1} from './apis/videointelligence/v1beta1';
export {videointelligence_v1beta2} from './apis/videointelligence/v1beta2';
export {vision_v1} from './apis/vision/v1';
export {vision_v1p1beta1} from './apis/vision/v1p1beta1';
export {vision_v1p2beta1} from './apis/vision/v1p2beta1';
export {webfonts_v1} from './apis/webfonts/v1';
export {webmasters_v3} from './apis/webmasters/v3';
export {websecurityscanner_v1alpha} from './apis/websecurityscanner/v1alpha';
export {youtube_v3} from './apis/youtube/v3';
export {youtubeAnalytics_v1} from './apis/youtubeAnalytics/v1';
export {youtubeAnalytics_v1beta1} from './apis/youtubeAnalytics/v1beta1';
export {youtubeAnalytics_v2} from './apis/youtubeAnalytics/v2';
export {youtubereporting_v1} from './apis/youtubereporting/v1';
