name: no_response
on:
  schedule:
    - cron: '30 1 * * *' # Run every day at 01:30
  workflow_dispatch:
  issue_comment:

jobs:
  close:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/close-unresponsive.cjs')
            await script({github, context})

  remove_label:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/remove-response-label.cjs')
            await script({github, context})
